### ISSUE TITLE
Add option to install KDE

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#106]
As an alternative to Cinnamon.

```
$ export MLGS_DE=kde
```

**Comment by ekultails** [comment]
Make it the default since SteamOS 3 uses it.

**Comment by LukeShortCloud** [comment]
The new environment variable will be `WINESAPOS_DE`.

**Comment by LukeShortCloud** [comment]
KDE and all of its extra packages take up a LOT of space. It fails to install on our build due to limited space.

```
error: Partition / too full: 1110486 blocks needed, 804905 blocks free
error: not enough free disk space
error: failed to commit transaction (not enough free disk space)
```

After a build which skips installing KDE, there is 6.2 GiB free of the 12 GiB dedicated for the root partition.

Our options are either to (1) install less packages which may be a sub-par experience, (2) decrease the size of the "flash drive" partition (currently uses 14.9 GiB), or (3) increase our minimum requirement of a flash drive size for winesapOS to 64 GB.

**Comment by LukeShortCloud** [comment]
Interestingly enough, running the install again on a larger disk, here are the disk statistics for it as reported by `pacman` itself:

```
$ sudo arch-chroot /mnt pacman -S plasma-meta kde-applications-meta plasma-nm kio-extras
...
Total Download Size:     1232.22 MiB
Total Installed Size:    3964.18 Mib
```

**Comment by LukeShortCloud** [comment]
I have an educated guess as to why KDE Plasma does not have enough storage when it tries to install: package cache. The `pacman` and `yay` cache may be too large. We should test clearing it out right before installing KDE Plasma.

**Comment by LukeShortCloud** [comment]
Clearing out the `pacman` cache before installing Plasma KDE works like a charm.
