### ISSUE TITLE
Rebrand Mac Linux Gaming Stick

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapos#107]
The original name "Mac Linux Gaming Stick" is generic and confusing at a first glance. We should change the name of the project.

**Comment by ekultails** [comment]
Possible apple names to use:

- Mutsu
- Pazazz
- Winesap

https://www.jessicagavin.com/types-of-apples/

Apple names to avoid (used by other technological projects):

- Ambrosia = Microsoft programming language. https://github.com/microsoft/AMBROSIA
- Cameo = Cameo-OSX GTK theme. https://www.gnome-look.org/p/1395239/
- Empire = Lots of open source projects use this name.
- Envy = Envy OS. https://www.findbestopensource.com/product/envyos
- Fuji = Too many projects related to Fujifilm.
- Gala = The window manager for Pantheon (elementaryOS). https://github.com/elementary/gala
- McIntosh = Too close to Macintosh.

**Comment by ekultails** [comment]
winesapOS may be the best fit. One of the primary goals of this project is to use Wine for gaming.

**Comment by ekultails** [comment]
pommeOS could also be used (pomme being the French word for "apple").

**Comment by ekultails** [comment]
Also rename scripts:

- install-manjaro.sh --> install-winesapos.sh OR winesapos-install.sh
- tests-arch-linux.sh --> tests-winesapos.sh OR winesapos-tests.sh
- upgrade-arch-linux.sh --> upgrade-winesapos.sh OR winesapos-upgrade.sh

**Comment by ekultails** [comment]
Update scripts to point to `/etc/winesapos/`. Possibly symlink that to `/etc/mac-linux-gaming-stick/`. Since we will not support version 2 to 3 upgrades that may not be necessary.
