### ISSUE TITLE
Use GitHub Actions

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#155]
We need to test building a chroot via a CI pipeline.

**Comment by LukeShortCloud** [comment]
Related: https://github.com/LukeShortCloud/winesapOS/issues/99

**Comment by LukeShortCloud** [comment]
My number one priority for 3.1.0 is to add CI. We need to ensure that winesapOS stays as stable as possible so adding more automated testing would be a big win.

Since running CI in a nested VM on a hosted provider for free is almost impossible to find, a good place I was thinking to start would be support for building a container. That would just be the root file system built into a chroot. No bootloader or disk management components would be installed or setup. That container image tarball will be part of our GitHub Releases. Users could use LXC or, with some elbow-grease, podman/docker to run it with full graphics and sound support. We'll provide examples on how to do that.

GitHub Actions also supports our own custom runners so I might be able to dedicate a server towards CI. That might solve our normal VM build use-case.

@Thijzer I know you mentioned that you were going to look into some Ansible testing automation. [1] I'm not sure if that would directly relate to CI or not. For testing today, we have integration testing that automatically runs after every build. [2] If you have any thoughts on how we get a good CI pipeline going, I'm all ears! :-)

1. https://github.com/LukeShortCloud/winesapOS/issues/297#issuecomment-1079413493
2. https://github.com/LukeShortCloud/winesapOS/blob/3.0.0-rc.0/scripts/winesapos-tests.sh

**Comment by Thijzer** [comment]
Hey @LukeShortCloud,

Adding a build script and setting up a github actions is something I should be able to achieve.  Assign me please :)

**Comment by LukeShortCloud** [comment]
Assigned! Thanks for volunteering. :-) Ping me anytime if you need help with anything.

My exposure to GitHub Actions is minimal but I'd love to start using it more across all of my open source projects. I've historically been using TravisCI for all of my upstream projects outside of work and absolutely hate it. GitHub Actions seems way better.

**Comment by Thijzer** [comment]
Okay, the first discussion point has arrived.

https://github.com/LukeShortCloud/winesapOS/pull/310

To build should use docker to run our build and make our image.
For this to succeed we need to setup an image file, mount that file and build inside that file.

The script is expecting a hypervisor with a raw volume and we can't use that.

Here is an example of what we need from chimeraOS but this would mean some major alterations to the script.

https://github.com/ChimeraOS/chimeraos/blob/master/build.sh#L44

**Comment by LukeShortCloud** [comment]
Nice, this is a great start! Thanks for putting this together! I like the containerizing of the build.

We've had some folks ask about removing the check to see if the install is running in a virtual machine. I'll expose an environment variable for that. It's loosely being tracked here [1] for now.

Then we can address the volume with a separate script that will create a raw disk and then expose the partitions via `losetup` (and `kpartx`?). There's a `WINESAPOS_DEVICE` environment variable we can use to target that device. It should be `export WINESAPOS_DEVICE=loop0` by default.

Next problem up on the list is the amount of storage space available on GitHub actions. Right now we require 28 GiB of space. Worst case scenario, we may only have 25 GB (or do they mean GiB?) in the CI environment. [2] Right now we create a 16 GB (14.9 GiB) exFAT partition that is not needed for CI. I want to make that optional anyways for our upcoming "minimal" image. [3]

1. https://github.com/LukeShortCloud/winesapOS/issues/311
2. https://github.com/easimon/maximize-build-space
3. https://github.com/LukeShortCloud/winesapOS/issues/254

**Comment by LukeShortCloud** [comment]
Okay, I created a [device_updates](https://github.com/LukeShortCloud/winesapOS/commits/device_updates) branch that (1) allows building outside of a VM and (2) can automatically create a raw image file to use as a partition. Rebase on-top of that branch and then use these environment variables in GitHub Actions:

```
export WINESAPOS_BUILD_IN_VM_ONLY=false
export WINESAPOS_CREATE_DEVICE=true
```

Hopefully this is all we need for now. I'll look into making the 16 GB exFAT partition optional later this week.

**Comment by Thijzer** [comment]
Hey Luke, so I updated the workflow a bit, it's now producing archived images in an output folder.
So the image-builder flow for docker is almost there.

I do have encountered some issues with the build, to make things a bit easier for testing, I added a test-build.sh file where you could test these builds easily and I also added a build.log file that shows the last build issues.

For context, In docker we place our scripts root directory in the /workdir, the resulting build files are placed inside /workdir/output, this output directory is a volume so after this build process we can easily grab these files.

**Comment by LukeShortCloud** [comment]
I left a code review on the pull request. I'll check out the build log later today when I get a chance.

So far, it looks great!

**Comment by LukeShortCloud** [comment]
I checked out the build.log file. This is something I noticed last night, too, while testing my branch more. It's now fixed. You'll need to rebase on-top of the latest `device_updates` branch. I fixed support for installing and testing using loopback devices (and NVMe drives, for that matter).

**Comment by LukeShortCloud** [comment]
I've merged the `devices_updates` branch into `main` now so you'll need to rebase on-top of that instead.
