### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#223]
Advertise how it is a portable install of SteamOS. Post about it on both Hacker News and Reddit.

**Comment by massatt212** [comment]
does it have the steamdeck UI or new big picture mode?

**Comment by LukeShortCloud** [comment]
Here are some highlights to mention for our eventual stable 3.0.0 release:

- ~100 GitHub stars, up from ~5 since our last release. Thank you to all of our supporters!
- Over 200 commits since the last stable release (2.2.0)
- Over 100 GitHub issues addressed
- Switched from Manjaro to SteamOS
- NVIDIA support

**Comment by LukeShortCloud** [comment]
Our stable release was published 2 weeks ago here: https://github.com/LukeShortCloud/winesapOS/releases/tag/3.0.0
