### ISSUE TITLE
Install an Archive manager 

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#227]
Install the AUR package `peazip-qt-bin`.

**Comment by FabioLolix** [comment]
Why favouring that over the others archivers build from source in the official repo?

**Comment by LukeShortCloud** [comment]
@FabioLolix Thanks for your comment. This is exactly the kind of feedback we're looking for! Do you have any alternative suggestions?

Here are the reasons I originally picked Peazip below. I should have noted this in the original feature request.

(1) It is cross-platform and available on Linux, macOS, and Windows. Users can use a familiar tool no matter the operating system.

(2) It natively has a GTK and Qt build. We allow building winesapOS with one of these two desktop environments: Cinnamon and KDE Plasma (the new default). We can install the appropriate package based on the desktop environment.

(3) These AUR packages for Peazip are binary packages so no source compilation is required. It repackages an official RPM.

I did some testing last night. It does lack some native integration such as drag-and-drop between a file manager and Peazip which is a bit disappointing.

**Comment by LukeShortCloud** [comment]
Here's a full list of archive managers: https://wiki.archlinux.org/title/list_of_applications#Archive_managers

We need to ship with an archive manager and our beta release will be happening really soon. Since we have not gotten any further feedback on this GitHub issue (here or on Twitter), I'll continue with PeaZip for now.

**Comment by FabioLolix** [comment]
Cinnamon: fileroller
KDE Plasma: ark

Anyway I see your point

peazip gtk build is gtk2

How are managed the AUR builds in the long term? On the users?

**Comment by LukeShortCloud** [comment]
Thanks for the suggestions! We may switch off PeaZip in the future.

Yes, we provide Pamac as a graphical package manager with integrations for AUR, Flatpak, and Snap packages.
