### ISSUE TITLE
Install Etcher

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#245]
This is our recommended tool for installing winesapOS. Users will be able to install winesapOS on other devices using winesapOS. It can be also be used to flash any image file to other storage mediums.

Here are where the packages can be found for each Linux distribution we support:

- Arch Linux = aur/etcher-bin
- Manjaro = community/etcher
- SteamOS = holo/balena-etcher

**Comment by LukeShortCloud** [comment]
@arun54321 winesapOS _finally_ supports Ventoy!

https://github.com/winesapOS/winesapOS/releases/tag/4.2.0

**Comment by arun54321** [comment]
Nice
