### ISSUE TITLE
Root file system is not reszied on internal NVMe drives

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#252]
`Qush Aes (@Darklink______ on Twitter)` reported an issue with the root file system not resizing. There is only 3 GB free indicating that our `resize-root-filesystem.service` failed.

Their system:

- 3.0.0-beta.0 performance image
- Internal 1TB SSD (NVMe) drive

**Comment by QushyQushy** [comment]
I just ran `sudo systemctl status resize-root-filesystem` and the service couldn't be found at all. Maybe it's not copied to the proper directory? If you need any more help let me know.

**Comment by LukeShortCloud** [comment]
@QushyQushy Oops, I made a typo and gave you the wrong command. Try `sudo systemctl status resize-root-file-system`.

**Comment by LukeShortCloud** [comment]
@QushyQushy Also, I just remembered that you don't need to reimage to test this. You can re-enable the command to start on boot. It'll automatically disable itself after running. The results may not be completely reliable as it's technically not the first boot but it should be good enough for now to help save you on time.

`sudo systemctl enable resize-root-file-system`.

**Comment by QushyQushy** [comment]
> @QushyQushy Also, I just remembered that you don't need to reimage to test this. You can re-enable the command to start on boot. It'll automatically disable itself after running. The results may not be completely reliable as it's technically not the first boot but it should be good enough for now to help save you on time.
> 
> `sudo systemctl enable resize-root-file-system`.

Yeah it was initially disabled and I enabled it. Gives an error at line 745 `Confusing arg 1` before it is disabled again.

**Comment by LukeShortCloud** [comment]
@QushyQushy Is it possible to provide the full/exact error? Either a screenshot or all the text output? You can use

**Comment by QushyQushy** [comment]
> @QushyQushy Is it possible to provide the full/exact error? Either a screenshot or all the text output? You can use https://pastebin.com/ if the output is too large.

I actually can't use konsole as it doesn't come preinstalled and there's a PGP error when trying to install it. Running `sudo pacman -Syu konsole` makes the system unbootable. I there any way I can update the one PGP key that's failing and install Konsole and Spectacle?

**Comment by LukeShortCloud** [comment]
You can use Terminator as an alternative to Konsole.

Pacman works but installing a package makes the system unbootable? I'm not sure why that would happen. If you're having a keyring issue, try running: `sudo pacman-key --populate archlinux`.

**Comment by QushyQushy** [comment]
Got it. Spectacle didn't have a PGP error so it worked. [Here's the image](https://imgur.com/Ysyovcs).

**Comment by LukeShortCloud** [comment]
Perfect! I've never seen that error before but that's exactly what I need to troubleshoot. Thank you! 🙂

**Comment by LukeShortCloud** [comment]
It turns out that I actually have only been using a SATA SSD for testing, not an NVMe SSD.

I grabbed an NVMe drive for testing and found our problem immediately. We have a bias for traditional device names only having one number and that number being the partition number. NVMe drives have 3 numbers in their name relating to the drive number and PCIe device. We need to modify our `resize-file-system.sh` script to only grab the last number.

```
$ lsblk -o NAME | grep nvme
nvme0n1
├─nvme0n1p1
├─nvme0n1p2
├─nvme0n1p3
├─nvme0n1p4
└─nvme0n1p5
$ root_partition=$(mount | grep 'on \/ ' | awk '{print $1}')
$ root_partition_number=$(echo ${root_partition} | grep -o -P "[0-9]+")
$ echo $root_partition_number 
0
1
5
```

**Comment by LukeShortCloud** [comment]
@QushyQushy I've got a patch up that I've been testing with success. Can you give it a try? Just copy and paste these commands into a terminal and then reboot:

```
sudo mv /usr/local/bin/resize-root-file-system.sh{,_3.0.0-beta.0}
sudo wget https://raw.githubusercontent.com/LukeShortCloud/winesapOS/test/scripts/resize-root-file-system.sh -O /usr/local/bin/resize-root-file-system.sh
sudo chmod +x /usr/local/bin/resize-root-file-system.sh
sudo systemctl enable resize-root-file-system
echo Done
```

If it does not work, could you provide another screenshot of the output of `sudo systemctl status resize-root-file-system`?

**Comment by QushyQushy** [comment]
> @QushyQushy I've got a patch up that I've been testing with success. Can you give it a try? Just copy and paste these commands into a terminal and then reboot:
> 
> ```
> sudo mv /usr/local/bin/resize-root-file-system.sh{,_3.0.0-beta.0}
> sudo wget https://raw.githubusercontent.com/LukeShortCloud/winesapOS/test/scripts/resize-root-file-system.sh -O /usr/local/bin/resize-root-file-system.sh
> sudo chmod +x /usr/local/bin/resize-root-file-system.sh
> sudo systemctl enable resize-root-file-system
> echo Done
> ```
> 
> If it does not work, could you provide another screenshot of the output of `sudo systemctl status resize-root-file-system`?

OMG! you're a LIFE SAVER! I was actually about to nuke my main M.2 cause I had messed up the partitioning and couldn't claim back the Windows space. Sure thing give me 2 minutes.

**Comment by QushyQushy** [comment]
> @QushyQushy I've got a patch up that I've been testing with success. Can you give it a try? Just copy and paste these commands into a terminal and then reboot:
> 
> ```
> sudo mv /usr/local/bin/resize-root-file-system.sh{,_3.0.0-beta.0}
> sudo wget https://raw.githubusercontent.com/LukeShortCloud/winesapOS/test/scripts/resize-root-file-system.sh -O /usr/local/bin/resize-root-file-system.sh
> sudo chmod +x /usr/local/bin/resize-root-file-system.sh
> sudo systemctl enable resize-root-file-system
> echo Done
> ```
> 
> If it does not work, could you provide another screenshot of the output of `sudo systemctl status resize-root-file-system`?

Worked like charm! Flashing it on my main drive right now! Thank you SO much for this! Do I have to blacklist the linux-firmware package as well?

PS: I will have gaming benchmarks between Winesap and Windows 10 ASAP on my Youtube channel if you're also interested.

**Comment by LukeShortCloud** [comment]
Perfect, glad it helped! I'll go ahead and merge it in.

Yes, you will want to configure `/etc/pacman.conf` to add these packages to the ignore list to avoid an unbootable system during a system upgrade:

`IgnorePkg = linux-firmware-neptune grub linux-lts linux-lts-headers`.

SteamOS has some conflicting packages. Unfortunately there are some [limitations](https://github.com/LukeShortCloud/winesapOS/issues/236#issuecomment-1061979151) in Pacman that prevent us from more cleanly creating an allow or block list for packages from certain repositories. I'm still working on a good workaround for that.

Through a Tweet reply on my winesapOS 3 beta announcement, someone posted to a video on your YouTube channel! I've already liked a few videos and subscribed. :-) Thanks for your hard work with benchmarking, I love those kinds of videos and comparisons!

**Comment by QushyQushy** [comment]
> Perfect, glad it helped! I'll go ahead and merge it in.
> 
> Yes, you will want to configure `/etc/pacman.conf` to add these packages to the ignore list to avoid an unbootable system during a system upgrade:
> 
> `IgnorePkg = linux-firmware-neptune grub linux-lts linux-lts-headers`.
> 
> SteamOS has some conflicting packages. Unfortunately there are some [limitations](https://github.com/LukeShortCloud/winesapOS/issues/236#issuecomment-1061979151) in Pacman that prevent us from more cleanly creating an allow or block list for packages from certain repositories. I'm still working on a good workaround for that.
> 
> Through a Tweet reply on my winesapOS 3 beta announcement, someone posted to a video on your YouTube channel! I've already liked a few videos and subscribed. :-) Thanks for your hard work with benchmarking, I love those kinds of videos and comparisons!

Thank you so much for the help and the instructions on how and what to blaklist!
Another bug I found is that if you have two installation of Winesap on the same PC (I flashed my main M.2 from the secondary M.2 so I ended up with two installation temprarily) the system drops you into a rootfs shell compaining `new_root` already exists or something like that. Sorry I didn't get a pic as I was left without an OS.
I installed Windows on the secondary M.2 and the system booted properly. Resizing right now.
Again thank you so much and I'm sure the future is great for this project! :+1:

**Comment by LukeShortCloud** [comment]
I should be the one thanking you for helping us identify issues! This project was fundamentally never made for myself. Historically, we've only had a handful of real-world users. I'm glad to see you're getting use, fun, and content out of our project!

As for your double installation issue, that's something I've never tried before (accidentally or on purpose). I was able to replicate the issue and opened a new issue to track that here: https://github.com/LukeShortCloud/winesapOS/issues/259

**Comment by QushyQushy** [comment]
> I should be the one thanking you for helping us identify issues! This project was fundamentally never made for myself. Historically, we've only had a handful of real-world users. I'm glad to see you're getting use, fun, and content out of our project!
> 
> As for your double installation issue, that's something I've never tried before (accidentally or on purpose). I was able to replicate the issue and opened a new issue to track that here: #259

Oh yeah I love the preinstalled apps, the fact that it's portable and literally everything about this is so well thought-out.

Btw, I'm on my newly installed system right now. I added the ignored packages and when I tried to update through Pamac it would update all of the should-be-ignored packages. `sudo pacman -Syu` ignores them properly. You might want to look into that as well.
