### ISSUE TITLE
Pamac updates ignored Pacman packages

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#260]
> I should be the one thanking you for helping us identify issues! This project was fundamentally never made for myself. Historically, we've only had a handful of real-world users. I'm glad to see you're getting use, fun, and content out of our project!
> 
> As for your double installation issue, that's something I've never tried before (accidentally or on purpose). I was able to replicate the issue and opened a new issue to track that here: #259

Oh yeah I love the preinstalled apps, the fact that it's portable and literally everything about this is so well thought-out.

Btw, I'm on my newly installed system right now. I added the ignored packages and when I tried to update through Pamac it would update all of the should-be-ignored packages. `sudo pacman -Syu` ignores them properly. You might want to look into that as well.

_Originally posted by @QushyQushy in https://github.com/LukeShortCloud/winesapOS/issues/252#issuecomment-1065938681_

**Comment by LukeShortCloud** [comment]
Any package listed in the `/etc/pacman.conf` `IgnorePkg` section will wrongly get upgraded.

If this is in an issue if Pamac itself, there's not much we can do. I'll investigate and do some research into this.

**Comment by LukeShortCloud** [comment]
@QushyQushy I've been testing around with this and looking up related issues on Pamac's GitLab page. It appears that the "Updates" tab is misleading. Yes, ignored packages are displayed but they are not actually selected for upgrade. I was able to verify this by going to `Preferences > Third Party > AUR > Enable AUR Support: Yes > Check for updates: Yes`. It found AUR updates and selected those automatically and left ignored packaged unselected.

It is, apparently, by design of Pamac to let you know that there are upgrades available for your ignored packages.

https://gitlab.manjaro.org/applications/pamac/-/issues/882#note_17262

**Comment by QushyQushy** [comment]
> @QushyQushy I've been testing around with this and looking up related issues on Pamac's GitLab page. It appears that the "Updates" tab is misleading. Yes, ignored packages are displayed but they are not actually selected for upgrade. I was able to verify this by going to `Preferences > Third Party > AUR > Enable AUR Support: Yes > Check for updates: Yes`. It found AUR updates and selected those automatically and left ignored packaged unselected.
> 
> It is, apparently, by design of Pamac to let you know that there are upgrades available for your ignored packages.
> 
> https://gitlab.manjaro.org/applications/pamac/-/issues/882#note_17262

Omg I didn't realize, I'm so sorry. Still it can be confusing for a new user. But if the system doesn't break at least then I guess it's fine for normies. I just tried and it indeed only updates the correct files. This is a weird "feaure" lol.

**Comment by LukeShortCloud** [comment]
Completely agreed, it's weird. No need to apologize, I didn't even know lol. Either way, there's nothing I can do about it besides adding something to our documentation.
