### ISSUE TITLE
Free space not reclaimed automatically after deleting files.

### ISSUE THREAD

**Issue by QushyQushy** [LukeShortCloud/winesapOS#266]
I installed Unreal Engine (which takes roughly 120 GBs of space) and after deleting it to install another version the Free Space in the drive wasn't updated until I re-enabled the `resize-root-file-system` service and rebooted.
I'm running off an NVME internal SSD.

**Comment by LukeShortCloud** [comment]
I don't know why the resize script would have anything to do with fixing it. Did you happen to install any packages before deleting the Unreal Engine? Or was Unreal Engine a package itself?

A Btrfs snapshot is taken everytime a package is installed or uninstalled so the space is kept as a backup. That's the only thing I can think of. Here's our documentation on how to manage and delete those backups:

https://github.com/LukeShortCloud/winesapOS/tree/3.0.0-beta.0#btrfs-backups

**Comment by QushyQushy** [comment]
Hmmm weird, maybe Dolphin was freaking out? Anywho since this is not an issue I'm sorry for the false alarm and I will check again just to be sure.
