### ISSUE TITLE
winesapOS Troubleshooting

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#267]
does it have the steamdeck UI or new big picture mode?

_Originally posted by @massatt212 in https://github.com/LukeShortCloud/winesapOS/issues/223#issuecomment-1069115159_

**Comment by LukeShortCloud** [comment]
Plenty of people have been asking about this. We do not have it implemented, however, it does look easy to setup. We'll look into possibly enabling it as part of our stable 3.0.0 release.

https://www.reddit.com/r/SteamDeck/comments/t57l4t/how_to_get_the_steam_deck_ui_on_windowsany_linux/

**Comment by LukeShortCloud** [comment]
What issues are you having with flashing it? It should be the same exact process as flashing a Manjaro ISO installer. The only difference is that winesapOS is pre-installed.

**Comment by massatt212** [comment]
Can you upload the uncompressed version, anytime o use ark peazip gnome unzipping manager it said file corrupted or some other error

**Comment by massatt212** [comment]
![Screenshot from 2022-03-16 11-53-53](https://user-images.githubusercontent.com/43518479/158632139-08d5a393-03bf-4807-98fa-02184d49800e.png)

**Comment by massatt212** [comment]
Updated system and it broke.

**Comment by LukeShortCloud** [comment]
(1) Are you using an internal NVMe drive? If yes, you may also run into an issue where the root file system does not get resized to use 100% of your storage device.

(2) Yes, we do support upgrades for enhancements to winesapOS via our upgrade script. This is not needed/used for the beta; it's only for stable releases. Otherwise, you can continue to use your operating system as-is with SteamOS and can update via the package manager as Valve releases updates. https://github.com/LukeShortCloud/winesapOS#upgrades

(3) Broken updates in this first beta is a known issue. We have fixed it already and that fix will be in the upcoming 3.0.0-beta.1 release later this week.

Regarding 1 and 3, I have updated our release notes to mention the workarounds: https://github.com/LukeShortCloud/winesapOS/releases/tag/3.0.0-beta.0
