### ISSUE TITLE
Create an independent Mac and Linux image

### ISSUE THREAD

**Issue by Thijzer** [LukeShortCloud/winesapOS#297]
Mac tweaks and Linux tweaks deserve their own image. (separation of concern) Also i will help advance the Linux build.

**Comment by Thijzer** [comment]
I do have a few more reasons to do so. First of is when one targets a mac build you might benefit from working with a specific kernel that works well, a couple of steps that are required, maybe even some specific conditions for specific targeted machines.

In a Linux build I see more of more a latest kernel with latest drivers drivers with Nvidia support. 

Something like that, everything would be a bit more separated with a bit more room for improvements per build.
Maybe a manifest could contain that specific build information.

It's a thought, a small possible optimization, but it might help to serve that diverse wide targeted audience.

For myself, I'm targeting a Linux build, my machine is a proxmox homelab with GPU pass-through enabled. 
I'm able to help with scripting and testing of course.

**Comment by LukeShortCloud** [comment]
Regarding the Linux kernels we ship, we currently ship 3 different ones: Linux LTS 5.15, Linux 5.13 Neptune (from SteamOS 3), and Linux LTS 5.10. If you're using the latest 3.0.0-beta.1 beta, you may have to scroll down in the GRUB menu to see them all. It defaults to the Linux 5.13 Neptune one right now.

If you select Linux LTS 5.15, it will be saved and used the next time you boot. We used to default to that on Arch Linux builds but the naming scheme SteamOS uses for its Linux kernel breaks how GRUB sorts the default Linux kernel for the first boot. It's a complicated fix to force Linux 5.15 to be the first choice again. Not impossible, though, so we can look into that again.

Is there a specific Linux version you are looking for? Linux 5.17 was just released and it's not even in the stable Arch Linux repositories yet. [1] Based on my experiences with NVIDIA graphics drivers on Arch Linux, it may take up to a month for both NVIDIA and Arch Linux to provide an updated driver that works with the latest stable Linux kernel. We try to stick to LTS kernels and, in general, stay upstream wherever possible. We do not provide any custom kernels, only a few custom kernel modules.

1. https://archlinux.org/packages/?sort=&q=linux&maintainer=&flagged=

----

I love the idea of exposing an easy way for users to customize what packages are installed as part of the build process. That could be something you can help implement if you're interested. We have an issue open tracking that here: https://github.com/LukeShortCloud/winesapOS/issues/123

**Comment by LukeShortCloud** [comment]
I opened up a different GitHub issue to track disabling systemd services not relevant for PCs: https://github.com/LukeShortCloud/winesapOS/issues/301

**Comment by LukeShortCloud** [comment]
We will soon have our GRUB theme enabled at a higher resolution by default. That will help show all the Linux kernels that are installed on a single page without scrolling. Refer to: https://github.com/LukeShortCloud/winesapOS/issues/302#issuecomment-1077114955

**Comment by Thijzer** [comment]
Ok I'll see if I can help here.

I love the idea of exposing an easy way for users to customize what packages are installed as part of the build process. That could be something you can help implement if you're interested. We have an issue open tracking that here:

Not only packages could be exposed. Here is a small example of something I worked on from in the past. 
https://github.com/Thijzer/archinstaller/blob/main/manifest, this manifest exposes a lot of user facing variables that normally gets asked during the installation guide. 

Based on your info around the latest kernel, I didn't know that Nividia was that slow with updating their drivers. Anyway it was food for thought, I sometimes would think that Mac are more picky with all the specific unsupported hardware and kernel updates other then LTS might break the system more often.

**Comment by Thijzer** [comment]
I'm going to setup a proxmox VM to test the current build this weekend and I'll try to setup an ansible build process, focus on some automation for testing.

**Comment by LukeShortCloud** [comment]
I'm going to close this issue since the original problem of not having a modern Linux kernel has been cleared up. The reason NVIDIA lags behind is because they have an out-of-tree proprietary driver so they constantly have to update their kernel source code bindings. AMD and Intel don't have this problem since their support is built directly into the Linux kernel which is why they work right away with every new Linux release.

Let's move the discussions for the new features to these related GitHub issues (or feel free to open new ones if you feel these do not address some of the features brought up here): 

- [Allow installing custom packages #123](https://github.com/LukeShortCloud/winesapOS/issues/123)
- [Use GitHub Actions #155](https://github.com/LukeShortCloud/winesapOS/issues/155)
