### ISSUE TITLE
Ship a custom Mesa package

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#309]
Mesa from SteamOS 3 does NOT provide Intel OpenGL drivers. We workaround this in 3.0.0 by installing Mesa from Arch Linux (if a user selects "Intel" graphics during the first-time setup). I want to build and maintain `mesa-steamos` and `lib32-mesa-steamos` on the AUR with all Intel drivers enabled (or, at the very least, the new crocus Intel driver).

As another alternative, @QushyQushy has [shown](https://www.youtube.com/watch?v=cx3D3Dxlg1I) that [mesa-tkg-git](https://github.com/Tk-Glitch/PKGBUILDS) provides better performance than SteamOS drivers. Even on a modern AMD dGPU.

The options for our graphics drivers are to either: (1) align fully with SteamOS and use our own AUR build or (2) use mesa-tkg-git for better performance. I'm inclined to go with option 1 because it's more stable/tested and is part of the overall goal of winesapOS being based on SteamOS.

Related: https://github.com/LukeShortCloud/winesapOS/issues/291

**Comment by LukeShortCloud** [comment]
It turns out the source files were there they were just in a bare repository. I have added documentation to Root Pages on how to handle that. I need to go back and add documentation that is specific to winesapOS.

I've now got two AUR packages up for the 64-bit and 32-bit builds of Mesa from SteamOS 3:

- https://aur.archlinux.org/packages/mesa-steamos
- https://aur.archlinux.org/packages/lib32-mesa-steamos

**Comment by LukeShortCloud** [comment]
@QushyQushy You may be interested in this! We have a custom Mesa build from SteamOS that is now widely available on all Arch Linux distributions. We also re-eneable a lot of drivers that SteamOS 3 disabled. No promises, but I'll try to have support for this on Arch Linux and Manjaro in a git branch by tomorrow.

**Comment by QushyQushy** [comment]
> @QushyQushy You may be interested in this! We have a custom Mesa build from SteamOS that is now widely available on all Arch Linux distributions. We also re-eneable a lot of drivers that SteamOS 3 disabled. No promises, but I'll try to have support for this on Arch Linux and Manjaro in a git branch by tomorrow.

Awesome! I'll definitely try ASAP then! :)

**Comment by LukeShortCloud** [comment]
If you want to try this out today, I'd say install winesapOS with Arch Linux and then install the Mesa packages with `yay -S mesa-steamos lib32-mesa-steamos` (or use Pamac).

This is more complicated than I was hoping when it comes to integrating this into the winesapOS build. In order to build the Mesa packages, you need `libva` and `libglvnd`. The problem is that those install the official `mesa` package as a dependency. Once `mesa-steamos` is built, it tries to install, and then our automation fails because we need to manually select to replace conflicting packages.

The easiest solution would be for us to provide our own package repository. Something we already want to do. Either way, I do want to find an automated way of handling this use-case. I did find one example here using the `expect` command which sounds neat: https://github.com/Jguer/yay/issues/713#issuecomment-887590449

**Comment by LukeShortCloud** [comment]
Building `mesa-steamos` in a clean chroot leads to this warning:

```
resolving dependencies...
warning: cannot resolve "clang-libs", a dependency of "opencl-mesa-steamos"
:: The following package cannot be upgraded due to unresolvable dependencies:
         opencl-mesa-steamos

:: Do you want to skip the above package for this upgrade? [y/N] 
```

**Comment by LukeShortCloud** [comment]
Here is the conflict line that we can use the `expect` command to workaround:

```
looking for conflicting packges...
:: mesa-steamos and mesa are in conflict (mesa-libgl). Remove mesa? [y/N] 
```

Later on we also need to accept the installation:

```
:: Proceed with installation? [Y\n] 
```

**Comment by QushyQushy** [comment]
I have some really unfortunate news. Unity updated their Cloud Service plugin and it doesn't work on Linux anymore so I need to use Windows until that's fixed for work. I will try Winesap again once I can properly work on Linux again. I'm realy sorry for this.

**Comment by LukeShortCloud** [comment]
That really sucks, sorry to hear that. That's no problem, your day job should be top priority. Hopefully by the time the Unity Cloud Service plugin works on Linux again, we'll have a lot more goodies in winesapOS for you. 😉

**Comment by LukeShortCloud** [comment]
This worked on Arch Linux but for some reason it failed on SteamOS.

```
# Install enhanced SteamOS Mesa packages first.
## There is a circular dependency on mesa to build mesa so we need to manually confirm to
## replace the conflicting 'mesa' package with 'mesa-steamos' once it has been built.
## https://github.com/LukeShortCloud/winesapOS/issues/309
arch-chroot ${WINESAPOS_INSTALL_DIR} ${CMD_PACMAN_INSTALL} expect
## These are responses to:
### ==> Diffs to show?\r==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)\r
### ==> Import? [Y/n]
### :: Proceed with installation? [Y/n]
### :: mesa-steamos and mesa are in conflict (mesa-libgl). Remove mesa? [y/N]
### :: Proceed with installation? [Y/n]
### :: lib32-mesa-steamos and lib32-mesa are in conflict (lib32-mesa-libgl). Remove lib32-mesa? [y/N]
### :: Proceed with installation? [Y/n]
arch-chroot ${WINESAPOS_INSTALL_DIR} sudo -u winesap expect -c "
  spawn yay -S --removemake mesa-steamos lib32-mesa-steamos
  set timeout -1
  expect -re \"\\\^4\\\)\r\"; sleep 2; send -- \"N\r\"
  expect -re \".*PGP keys need importing.*\"; sleep 2; send -- \"Y\r\"
  expect -re \".*Proceed with install.*\"; sleep 2; send -- \"Y\r\"
  expect -re \".*are in conflict.*Remove.*\\\?\"; sleep 2; send -- \"Y\r\"
  expect -re \".*Proceed with install.*\"; sleep 2; send -- \"Y\r\"
  expect -re \".*are in conflict.*Remove.*\\\?\"; sleep 2; send -- \"Y\r\"
  expect -re \".*Proceed with install.*\"; sleep 2; send -- \"Y\r\"
  expect eof"
# Install Xorg.
arch-chroot ${WINESAPOS_INSTALL_DIR} ${CMD_PACMAN_INSTALL} xorg-server xorg-server xorg-xinit xterm xf86-input-libinput xf86-video-amdgpu xf86-video-intel xf86-video-nouveau
```

https://github.com/LukeShortCloud/winesapOS/commit/53829e2a87de36684b0dd3ede6df632c9de7e01c

This Reddit post seems to suggest that simply using the `yes` command and piping it to the `yay -S` install command will work. We will try that next.

https://www.reddit.com/r/archlinux/comments/5m58ht/pacman_automatically_say_yes_to_conflict_messages/

**Comment by LukeShortCloud** [comment]
The `expect` workaround is confirmed to be working on Arch Linux and Manjaro but not on SteamOS. I am convinced at this point that it is actually a bug in Pacman's standard input handling that has already been addressed upstream. SteamOS is still using Arch Linux packages from January (4-5 months old at this point).

Here is another potential workaround:

1. Build the `mesa-steamos` and `lib32-mesa-steamos` packages with `makepkg -s` (do not install with `-i`). This will install `mesa` and `lib32-mesa` as build dependencies.
2. Remove the upstream Mesa packages with `pacman -R`.
3. Then install our new packages with `pacman -U`.

**Comment by LukeShortCloud** [comment]
This headache could all probably be avoided if we expedite having our own package repository. Then it would be as simple as `pacman -S winesapos/mesa-steamos winesapos/lib32-mesa-steamos`.
