### ISSUE TITLE
[readme] Document how to build winesapOS for end-users

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#311]
This should be a simpler guide that links to the DEVELOPER.md guide for more details. There are two advantages to building winesapOS: (1) lower disk space requirement (no 50 GiB required to download and extract an image) instead users can use a 8 GB or smaller flash drive with a live CD of an Arch Linux distribution and (2) a fully customizable build. Related to 2:  https://github.com/LukeShortCloud/winesapOS/issues/123 .

Workflow for building winesapOS off a live CD:

1. Setup Arch Linux, Manjaro, or Steam Deck Recovery image on a flash drive using BalenaEtcher.
2. Clone the stable repository.
    2a. For now, delete these lines of code preventing it from running in a VM (I will make this into an environment): https://github.com/LukeShortCloud/winesapOS/blob/3.0.0/scripts/winesapos-install.sh#L29-L34
4. Configure environment variables. At the very least, configure `export WINESAPOS_DEVICE=` to be your physical `/dev/${WINESAPOS_DEVICE}` name.
5. Run the `sudo -E ./winesapos-install.sh`

This is a slighly modified approach to the typical developer build guide: https://github.com/LukeShortCloud/winesapOS/blob/stable/DEVELOPER.md

@QushyQushy I hope this helps you. Let me know if you need any help or run into any problems. I'll let you know when we get more polished up documentation merged in.

**Comment by LukeShortCloud** [comment]
@QushyQushy Okay, I've got a first draft of our complete documentation around this. Here it is and let me know what you think.

https://github.com/LukeShortCloud/winesapOS/tree/311_custom_build_docs#custom-builds

The only change you need to make is that instead of cloning the "stable" branch, clone the "device_updates" branch instead. This is temporary and will not be needed when we release 3.1.0.

**Comment by QushyQushy** [comment]
Hello! Yeah just to clarify things, to install the SteamOS 3.0 version can I make an Arch USB and just clone the repo or do i have to use the Steam 3.0 recovery image? Cause the second option doesn't boot on any of my machines.

**Comment by LukeShortCloud** [comment]
Yeah, you need to use SteamOS Recovery image. Make sure you're using UEFI boot and disable secure boot.

I'm working on a hybrid approach of using Arch Linux as a base and then install a few AUR packages I'll create and maintain for SteamOS specific packages. You get the benefit of faster Arch Linux updates that way.

You can build with an Arch Linux or Manjaro today but it won't install SteamOS packages. Depending on which one you use, set one of these environment variables. We'll eventually add auto detection so this step won't be required.

```
export WINESAPOS_DISTRO=arch
```

```
export WINESAPOS_DISTRO=manjaro
```

**Comment by QushyQushy** [comment]
> Yeah, you need to use SteamOS Recovery image. Make sure you're using UEFI boot and disable secure boot.
> 
> I'm working on a hybrid approach of using Arch Linux as a base and then install a few AUR packages I'll create and maintain for SteamOS specific packages. You get the benefit of faster Arch Linux updates that way.
> 
> You can build with an Arch Linux or Manjaro live USB/DVD today but it won't install SteamOS packages. Depending on which one you use, set one of these environment variables. We'll eventually add auto detection so this step won't be required.
> 
> ```
> export WINESAPOS_DISTRO=arch
> ```
> 
> ```
> export WINESAPOS_DISTRO=manjaro
> ```

Ok, I have tried all methods with SteamOS, it just won't boot so I'll try to do an Arch install today or tommorow and let you know how it goes. :)
