### ISSUE TITLE
Bottles AUR package fails to build on SteamOS 3

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#312]
This is our first "gotcha" of using the AUR and SteamOS 3. The real problem is that SteamOS 3 ships an old version of Arch Linux (currently dating back to January 27th 2022 which is over 2 months old [1]).

The AUR package for `bottles` has recently been updated to require version 1.5 or newer of the `libhandy` dependency. The SteamOS mirror for Arch Linux only ships 1.4.0.

The Bottles maintainers state that they have always developed with a "Flatpak-first" approach [2] so that's even more reason to consider a switch to Flatpak.

1. https://steamdeck-packages.steamos.cloud/archlinux-mirror/
2. https://twitter.com/usebottles/status/1509059350580633603

**Comment by FabioLolix** [comment]
Another old package is ffmpeg that is still at v4.4, AUR pkgbuilds incompatible with ffmpeg 5 now require package `ffmpeg4.4` which don't exist

**Comment by LukeShortCloud** [comment]
Is there a specific package that winesapOS uses that is affected by this? I've done a few builds and so far only the bottles package fails to build. Either way, this will be an ongoing issue unless we do something about having old packages.

Long-term, I think the best route forward is to use Arch Linux as a base and then add our custom packages from SteamOS. I checked into their "source" packages but they don't provide any actual source code, just links to internal Valve GitLab repositories. So we can't rebuild anything from there but we could, for now, download and install the packages manually. Or use the SteamOS repository on Arch Linux.

**Comment by FabioLolix** [comment]
> Is there a specific package that winesapOS uses that is affected by this?

No it was a random rambling

> I checked into their "source" packages but they don't provide any actual source code

they do but not in a pratical way, the tarballs include a sort of git checkout of the sources and other additional sources, but I don't know how to use that

**Comment by FabioLolix** [comment]
> Those are just the base files (think scaffolding or skeleton structure) of a git repository

makepkg with configured common source destination keep git repos like that, so I guess it could be usable with some magick command

I've checked `linux-neptune` the tarball is 2,7GB, into `archlinux-linux-neptune/objects/pack` there are a .pack (2.4GB) and an .idx (289MB), I'm pretty sure the code is there just don't know how to use that

**Comment by LukeShortCloud** [comment]
You were right, all the source code is there and I was able to get it into a usable form! Thanks, I was about to give up on it.

Apparently what they are providing in the source packages are known as a "bare git repository" made via a `git clone --bare` command. I was able to reconstruct a couple of repositories.

- https://github.com/LukeShortCloud/steamos-jupiter-mesa
- https://github.com/LukeShortCloud/steamos-linux-neptune

Here are the notes I took on how I accomplished this:

- https://github.com/LukeShortCloud/rootpages/commit/7fac127741ee0213c66204306799cae1ceb2c8f0
- https://github.com/LukeShortCloud/rootpages/commit/4c30e9e8ab5b95b6e5394e6b4afb5a754855754e

Next steps are to:

1. Modify the PKGBUILDs to add myself as a maintainer, use my git repository, and enable new features for the Mesa package.
2. Publish the PKGBUILDs to the AUR.

I've been reading over the [AUR submission guidelines](https://wiki.archlinux.org/title/AUR_submission_guidelines) page. Is there an approval process for AUR packages? Or is it available as soon as I push something to the AUR package repository? Should I also make a separate git repository on GitHub for each PKGBUILD? I'd like to publish a `linux-steamos` and `mesa-steamos` package. I'm hoping to follow AUR best practices. :-)

**Comment by LukeShortCloud** [comment]
I've got two AUR packages up for the 64-bit and 32-bit builds of Mesa from SteamOS 3:

- https://aur.archlinux.org/packages/mesa-steamos
- https://aur.archlinux.org/packages/lib32-mesa-steamos
