### ISSUE TITLE
Replace MultiMC with PolyMC

### ISSUE THREAD

**Issue by IntoTheVoid-900** [LukeShortCloud/winesapOS#314]
PolyMC is a fork of MultiMC that has more packaging options (like Flatpak), and more general features (like a built-in mod downloader with Curseforge and Modrinth support). Can you consider switching to PolyMC as your built-in MC launcher?

**Comment by LukeShortCloud** [comment]
Thanks for the suggestion! That all sounds good to me. I'll look into it for our next release.

**Comment by LukeShortCloud** [comment]
We are now using PolyMC instead of MultiMC in our latest development branch. This may be included in a stable 3.0.1 release soon.
