### ISSUE TITLE
Support Ventoy

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#316]
How about using ventoy instead of etcher?

_Originally posted by @arun54321 in https://github.com/LukeShortCloud/winesapOS/issues/245#issuecomment-1085967249_

**Comment by LukeShortCloud** [comment]
Hey @arun54321 , thanks for the suggestion! I've never used Ventoy before so maybe you can help me understand the use-case for it.

From what I've read about it here [1] and here [2] it sounds like it allows booting off of different ISOs. We do not provide a live CD Linux distribution that would normally mount the writeable file system into RAM. I'm not sure if that causes complicated with Ventoy. We also preconfigure winesapOS so that it itself has a 16 GB exFAT partition for cross-platform storage and separately a few other system partitions including the root partition which is very small in our build but expands to be 100% of the disk it is on. It is possible to increase the size of the virtual disk, too.

If we can find a good user story for winesapOS and Ventoy, I'd be happy to document that in our README. Today we recommend Etcher as it will take our build image, byte for byte, and apply it to a disk (either an internal drive, flash drive, etc.). There are some biases we have towards that scenario.

1. https://www.ventoy.net/en/index.html
2. https://www.ventoy.net/en/doc_start.html

**Comment by LukeShortCloud** [comment]
winesapOS actually does not work with Ventoy, as reported here: https://github.com/LukeShortCloud/winesapOS/issues/327#issuecomment-1136429702

We can look into supporting this in the future.

**Comment by lordbagel42** [comment]
Would this run in a virtual hard drive?

**Comment by LukeShortCloud** [comment]
As it stands today, yes, you can convert the raw winesapOS release image to be a virtual drive format. We have instructions on how to use winesapOS in VMware Fusion (macOS), WMware Player/Workstation (Linux and Windows), and VirtualBox (Linux, macOS, and Windows). VMware Fusion, Player, and Workstation all provide OpenGL graphics acceleration if you want to do some light and old gaming. VirtualBox has a very broken implementation of graphics support in Linux.

https://github.com/LukeShortCloud/winesapOS/tree/3.2.1#release-builds

@lordbagel42 Does that help answer your quesetion?

**Comment by LukeShortCloud** [comment]
Good news: there's a plugin for Ventoy to support raw images which means winesapOS can work with it. I'll add documentation about this.

https://www.ventoy.net/en/plugin_vtoyboot.html
