### ISSUE TITLE
Steam Machine with NVIDIA GTX 860M Fails to Boot

### ISSUE THREAD

**Issue by mmf1ne** [LukeShortCloud/winesapOS#324]
When starting Linux, it will be stuck on the starting interface, the machine used is steam machine, and the graphics card may be a customized version of gtx860m

**Comment by LukeShortCloud** [comment]
Hey @mmf1ne, sorry to hear about your issue and thanks for reporting it!

The default Linux Neptune kernel from SteamOS sometimes has issues booting on certain devices. I had problems with it myself with my NVIDIA GTX 1080.

When your Steam Machine boots to the GRUB menu, scroll down and select `Arch Linux, with Linux linux-lts (fallback initramfs)`. Let me know if that works or not.

**Comment by mmf1ne** [comment]
I uesd the secure image instead the performance ver now its stack on the passwd step @LukeShortCloud

**Comment by mmf1ne** [comment]
when used the 4th it works thanks for your work sorry for my English

**Comment by LukeShortCloud** [comment]
Changing the password on the secure image is confusing. You need to enter the original password twice and then the new password twice. I will open up a new issue for us to document that.

**Comment by LukeShortCloud** [comment]
You can now boot with the Linux LTS kernel, sign in, but then it says that the Light Display Manager failed to start. Is that correct?

**Comment by mmf1ne** [comment]
yes I konw why I used an es cpu this need the specific version of the graphics card driver

**Comment by LukeShortCloud** [comment]
SteamOS only has partial support for NVIDIA graphics drivers. On a few systems we have tested, it is good enough to login and get to our first-time setup. Then we install the proprietary driver. You cannot even get that far so you may need full NVIDIA support. In a few weeks, we may have an alpha release of 3.1.0 you can try with related improvements.

**Comment by LukeShortCloud** [comment]
@mmf1ne  We have a new alpha release that should fix support for NVIDIA graphics card. Could you try this build and see if it is able to boot properly on your device?

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-alpha.0

**Comment by LukeShortCloud** [comment]
We now have a beta release with these updates rolled in if you want to try that instead: https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-beta.0

**Comment by LukeShortCloud** [comment]
Another possible issue is that if you used Ventoy to load the winesapOS image, it will not work as reported here: https://github.com/LukeShortCloud/winesapOS/issues/327#issuecomment-1136429702

I, ironically, used to own a GTX 860M laptop but sold it to a friend. I'll see if the latest winesapOS beta build works for them.

**Comment by LukeShortCloud** [comment]
My friend's laptop is in the shop and will be for a while. I've been testing the development builds of 3.1.0 on my NVIDIA gaming machine and it works a lot better than 3.0.0 and 3.0.1 did.

Closing as resolved. Feel free to re-open this if you encounter any further issues.

**Comment by LukeShortCloud** [comment]
@mmf1ne Our stable winesapOS 3.1.0 is out now with fixes for this if you want to give it a try again.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0
