### ISSUE TITLE
Install Steam as a Flatpak

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#328]
This is a long-term goal. A Valve employee (Pierre-Loup A. Griffais, known online as Plagman) very recently (last week) said this about known issues with the Steam Flatpak:

```
think it still breaks some stuff around controllers and remote play
there's that whole perf issue with syscall allowlisting too
```

In summary, these are the known issues that need to be addressed before we switch to the Flatpak installation of Steam:

- Controllers do not work.
- Remote play does not work.
- Performance issues due to limited kernel system calls.

Related: https://github.com/LukeShortCloud/winesapOS/issues/300

**Comment by LukeShortCloud** [comment]
For controller support, I found this workaround and confirmed it works:

```
$ sudo flatpak override --filesystem=/run/udev com.valvesoftware.Steam
$ flatpak run com.valvesoftware.Steam
```

https://github.com/flatpak/xdg-desktop-portal/issues/536

This was also needed for the [Controllable](https://www.curseforge.com/minecraft/mc-mods/controllable) Minecraft Forge mod to work when using the PolyMC Flatpak.

```
$ sudo flatpak override --filesystem=/run/udev org.polymc.PolyMC
$ flatpak run org.polymc.PolyMC
```

**Comment by LukeShortCloud** [comment]
Related to this, the MangoHud Flatpak was designed to only work with the Steam flatpak. See: https://www.reddit.com/r/linux_gaming/comments/mxiwxh/does_mangohud_not_work_with_flatpaks/

**Comment by LukeShortCloud** [comment]
Reading through the GitHub issues for the Steam Flatpak, it seems like controller support [1][2], remote play [3], and fsync system calls [4] should work now. I will need to test all of this myself.

1. https://github.com/flathub/com.valvesoftware.Steam/blob/d0eac10e5259dbddd7df60ab5a315526f4885911/com.valvesoftware.Steam.yml#L37
2. https://github.com/flathub/com.valvesoftware.Steam/blob/d0eac10e5259dbddd7df60ab5a315526f4885911/com.valvesoftware.Steam.yml#L40
3. https://github.com/flathub/com.valvesoftware.Steam/issues/362
4. https://github.com/flathub/com.valvesoftware.Steam/issues/806

**Comment by LukeShortCloud** [comment]
A recent Reddit post says most of the major issues with the Steam Flatpak have been resolved. The only issues reported in the thread were (1) up to a 8% slowdown and (2) a few games don't work.

It was also mentioned that GE-Proton can easily be installed as a Flatpak for the Steam Flatpak. Otherwise, we can manually install it to: `/home/winesap/.var/app/com.valvesoftware.Steam/data/Steam/`

https://www.reddit.com/r/linux_gaming/comments/rp2ss9/is_there_any_real_disadvantages_to_using_the/

**Comment by soredake** [comment]
https://github.com/flatpak/flatpak/issues/4187 https://github.com/flathub/com.valvesoftware.Steam/issues/810

**Comment by LukeShortCloud** [comment]
Thanks for linking those Steam Flatpak issues! That's very helpful. Here are my thoughts on each issue, in order:

1. lib.so.6 not found = Fixed upstream a few years ago.
2. Performance issues with seccomp = Sounds like we can workaround the performance problem by modifying our desktop shortcut for Steam (which we already do). We'd have to run it with this argument:

```
flatpak run --allow=unconfined
```

3. Games packaged with AppImage do not work = That sucks. Definitely a blocker.
4. Mounted drives are not detected by default = We can install FlatSeal and provide documentation on how to workaround that.

**Comment by soredake** [comment]
1) Sorry i linked a wrong bugreport, correct link https://github.com/flathub/com.valvesoftware.Steam/issues/810

2) disabling secomp is not supported in flatpak, patched version is needed to do this

**Comment by LukeShortCloud** [comment]
Thanks for the clarification! Regarding seccomp, I originally read through that too fast. I see now that someone provides an RPM for it. Needing a patched Flatpak for to fix some performance issues is a big problem. If all of these issues are addressed, then we can move forward with adopting the Flatpak. That may take awhile and that's alright.

**Comment by soredake** [comment]
>Controllers do not work.

This will be solved in systemd in future https://github.com/systemd/systemd/pull/22860

**Comment by soredake** [comment]
> For controller support, I found this workaround and confirmed it works:
> 
> ```
> $ sudo flatpak override --filesystem=/run/udev com.valvesoftware.Steam
> ```

As noted in various issues mentioning this workaround, it's hack that can break after udev update on host/freedesktop-sdk, it's better not to rely on it.

> Controllers do not work.

To make controllers work in steam and other software that relying on sdl/hidraw it's better to ship https://aur.archlinux.org/packages/game-devices-udev

**Comment by LukeShortCloud** [comment]
Thanks for all of your valuable information and input!

My understanding of what you're saying is that short-term we should use https://aur.archlinux.org/packages/game-devices-udev and long-term we should wait for systemd to merge this https://github.com/systemd/systemd/pull/22860 . And we won't need the `flatpak override --filesystem=/run/udev` workaround. Is that correct? What all should we use or wait for to be able to switch to the Steam Flatpak?

**Comment by soredake** [comment]
>Remote play does not work.

I can't really test remote play fully, linux is right now is not my main os, but i tested streaming from fedora kinote vm with flatpak'ed steam to windows host and it worked fine (note: i've tested it briefly, without controller)

**Comment by soredake** [comment]
I've tested steam with `flatpak --user override --env=APPIMAGE_EXTRACT_AND_RUN=1 com.valvesoftware.Steam`.

Tested appimages:
1. WAKFU: crashes ([wakfu.txt](https://github.com/LukeShortCloud/winesapOS/files/9654370/wakfu.txt), can be fixed with `%command% --no-sandbox`
2. Exoblast: crashes ([exoblast.txt](https://github.com/LukeShortCloud/winesapOS/files/9654391/exoblast.txt), can be fixed with `env TMPDIR=$HOME/Downloads %command% --no-sandbox`
3. SuperTux: crashes in [x11.txt](https://github.com/LukeShortCloud/winesapOS/files/9654410/supertux.txt) works in wayland.

**Comment by LukeShortCloud** [comment]
Great to hear Steam Remote Play works! Even if it was only in a virtual machine.

I need to double check on controller support. It's been working for me on the Lutris Flatpak but I've never tried with the Steam Flatpak.

One other thing we can do regarding AppImage games in Steam is recommend that, if a user has problems, to use the Windows game with Steam Play instead of the native build. That sucks that most of those games crashed but I'm glad you've found a workaround for some that we can document. We're still on X11 for the time being, too.

**Comment by soredake** [comment]
The sad thing is, even/if [fuse portal](https://github.com/flatpak/xdg-desktop-portal/issues/695) will be implemented, electron games will still be broken in appimage or not, [CLONE_NEWUSER ](https://github.com/flatpak/flatpak/blob/1c32317841f2f77e69489e006648a0e58af247a1/common/flatpak-run.c#L3210-L3211) that required for electron to run with sandbox without using suid is can't be used inside flatpak. So, switching steam to flatpak will forever impact out-of-the-box 

More info:
https://github.com/electron/electron/issues/17972#issuecomment-516957971
https://github.com/flatpak/flatpak/issues/3044
https://github.com/flathub/com.valvesoftware.Steam/issues/897
https://github.com/malept/electron-installer-flatpak/pull/16
https://github.com/refi64/zypak

**Comment by soredake** [comment]
On a positive note, there is https://github.com/electron/electron/issues/27083 open, i doubt that electron implement this, but we can dream. As a more realistic workaround:

1) Install [com.valvesoftware.Steam.Utility.steamtinkerlaunch](https://github.com/frostworx/steamtinkerlaunch) by default
2) Ship tweaks for all affected appimages (like exoblast that requires unpacking to non-tmpfs) and electron games (wakfu)
3) Tell user to set `steamtinkerlaunch %command%` as launch options
4) Games works! (i've tested wakfu)

**Comment by soredake** [comment]
I've decided to send pr with this env to steam flatpak https://github.com/flathub/com.valvesoftware.Steam/pull/980

**Comment by LukeShortCloud** [comment]
Thanks, what a great idea to bake the environment variable straight into the Flatpak itself! Hopefully both Steam and Lutris will accept your changes.

**Comment by soredake** [comment]
Another blocker (i think) for switching steam to flatpak is https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/7

**Comment by soredake** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/924

**Comment by soredake** [comment]
Good news, IIUC [this pr](https://github.com/flatpak/flatpak/pull/5224) can be a workaround for https://github.com/flatpak/flatpak/issues/4187 and non-working electron games.

**Comment by LukeShortCloud** [comment]
This looks promising and sounds like it would help many tricker Flatpaks beyond Steam, too.

Thanks for sharing! I'll keep an eye on it.

**Comment by soredake** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/924#issuecomment-1364489602 unfortunately it seems that electron games will not be fixed with this new setting.

**Comment by LukeShortCloud** [comment]
Work seems to be resuming on the seccomp performance issues: `https://github.com/flatpak/flatpak/pull/5224`

**Comment by LukeShortCloud** [comment]
While testing the Steam Flatpak recently, I ran into this annoying issue with Forza Horizon 5:

"""
If you are using the Steam Flatpak from Flathub, Forza will complain that the default install directory Flathub Steam uses has "too long" of a path, as in, the game breaks if there are too many characters in the path to the install directory. To fix, I created a "Forza" folder in my home folder, changed the Flatpak permissions to give Steam access to it, added the folder as a game install location in Steam, and then moved the game files to that folder.
"""

https://www.protondb.com/users/1282116887

I have yet to find any other games complain about the long file path, at least.

**Comment by LukeShortCloud** [comment]
Gamescope not working with Proton running Steam Flatpak is still the biggest blocker. Especially now that we have the Steam Gamescope session to replicate the "Game Mode" from Steam Deck. There is a workaround, at least, and that is to use the GE-Proton Flatpak. Gamescope session is also untested with the Flatpak variants (and hardcoded to work with the native variants).

`https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/7`

Worst-case, perhaps the next big Flatpak update will switch all game launchers except Steam to Flatpaks.

**Comment by LukeShortCloud** [comment]
The Flatpak for Gamescope had its code moved to a different git repository. The new GitHub Issue to track for vanilla Proton support with Flatpak'ed Gamescope is this one:

`https://github.com/flathub/com.valvesoftware.Steam.Utility.gamescope/issues/7`

**Comment by LukeShortCloud** [comment]
I tested using `gamescope-session` with the Flatpak of Steam by using this:

```
$ sudo vim /usr/share/gamescope-session-plus/sessions.d/steam-flatpak
CLIENTCMD="flatpak run com.valvesoftware.Steam -gamepadui -steamos3 -steampal -steamdeck"
$ sudo vim /usr/share/wayland-sessions/gamescope-session-steam-flatpak.desktop
[Desktop Entry]
Encoding=UTF-8
Name=Steam Flatpak
Comment=A session to run Steam via Flatpak
Exec=gamescope-session-plus steam-flatpak
Type=Application
DesktopNames=gamescope
```

It instantly failed with a core dump. The Steam Flatpak has mostly been untested when it comes to `gamecope-session` and Valve developers recommend against using it like that.

It does not sound like support for this will come anytime soon. I will close this out for now. We can revisit using the Steam Flatpak a few years down the road. We have already been waiting 2 years and the features we need are not there yet.
