### ISSUE TITLE
Some questions about copmatibility with the Steam Deck

### ISSUE THREAD

**Issue by QushyQushy** [LukeShortCloud/winesapOS#340]
Hello, I just got my Steam Deck and I have some questions about what and does and doesn't work in Winesap as I think replacing SteamOS with this. Namely:

Does the on screen keyboard work in Desktop Mode?
Is there a Game Mode?

Just these two questions. Thanks in advance! :)

**Comment by LukeShortCloud** [comment]
Hey, @QushyQushy , congratulations! Hope you have fun with your shiny new Steam Deck! 😁

Unfortunately, no. I would not recommend completely replacing SteamOS right now. If anything, you may consider trying a dual-boot with winesapOS being on a microSD card.

Here are the two major blockers regarding running winesapOS on a Steam Deck:

1. No controller support for the Steam Deck itself: https://github.com/LukeShortCloud/winesapOS/issues/330
2. No SteamOS Game Mode support: https://github.com/LukeShortCloud/winesapOS/issues/241

Today I put up a new alpha release if you want to try it out. I'm on a road trip (my first one with my Steam Deck!) so I couldn't finish the release notes in time before I left. The highlights are: better support for Intel and NVIDIA graphics drivers, we have our own winesapOS repository (you can use it on any Arch Linux distro, too!), and most of our packages are now installed as Flatpaks.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.0-alpha.0

**Comment by LukeShortCloud** [comment]
Audio has recently been fixed: https://github.com/LukeShortCloud/winesapOS/issues/444

This'll be coming in our winesapOS 3.3.0 release.

**Comment by LukeShortCloud** [comment]
Using gamescope-session for GameMode will be coming in winesapOS 3.4.0. This work is being tracked here: https://github.com/LukeShortCloud/winesapOS/issues/241

**Comment by LukeShortCloud** [comment]
@QushyQushy winesapOS 3.4.0 is out now with full support for Game Mode!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0

**Comment by QushyQushy** [comment]
Does Winesap work on the OLED model as well? I gave the LCD model to my nephew and now waiting for the OLED one. :)

**Comment by LukeShortCloud** [comment]
Congratulations on your purchase of the OLED Steam Deck! I hope your nephew enjoys your old LCD Deck. :-)

Unfortunately, winesapOS does not support the OLED. 3.4.0 was feature complete two months ago right before the OLED came out. However, there were a lot of bugs I had to fix and the release was already very delayed. Our upcoming 4.0.0 release (this is the next release after 3.4.0) will support the OLED!
