### ISSUE TITLE
Support Raspberry Pi

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#356]
If we are going to support Arm Macs, it would make sense to also support the most popular Arm device in the world: the Raspberry Pi.

Related: https://github.com/LukeShortCloud/winesapOS/issues/319

**Comment by LukeShortCloud** [comment]
This would be based on Arch Linux ARM: https://archlinuxarm.org/

**Comment by LukeShortCloud** [comment]
Only the Raspberry Pi >= 4 supports Vulkan. We need this to support Vulkan 1.3 to work with the latest Proton. It currently only supports 1.2.

https://www.phoronix.com/news/V3DV-Exposes-Vulkan-1.2

**Comment by LukeShortCloud** [comment]
We may also want to wait until the Raspberry Pi 5 comes out which will presumably be more powerful.

**Comment by LukeShortCloud** [comment]
The new install script should be called: `winesapos-install-rpi.sh`.

**Comment by LukeShortCloud** [comment]
Or `winesapos-install-raspberry-pi.sh`.

**Comment by LukeShortCloud** [comment]
Our build will be 64-bit with multilib enabled.

**Comment by FabioLolix** [comment]
> Our build will be 64-bit with multilib enabled.

ALARM don't seem have multilib, if you go to https://archlinuxarm.org/packages and search `glibc` there is only for `armv7h` and `aarch64`

**Comment by LukeShortCloud** [comment]
Thank you for letting me know! You're very insightful @FabioLolix 🙂 That changes things slightly. We will really need to wait for Box64/Box86 and Wine WOW64 support to improve before we can seriously consider a Raspberry Pi build.

**Comment by LukeShortCloud** [comment]
Another thing to consider here is that VRAM uses shared memory. winesapOS requires a minimum of 2 GB of RAM to run. For having system RAM and also VRAM for games, an 8 GB Raspberry Pi is recommended.

**Comment by LukeShortCloud** [comment]
Similar to https://github.com/LukeShortCloud/winesapOS/issues/319#issuecomment-1986416487 , creating an Arm build of winesapOS would be recreating the project from scratch with little to no value add over existing Linux distributions.

Closing for now.
