### ISSUE TITLE
Install a simple text editor

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#361]
As it is now, opening up a text file launches LibreOffice which is (1) resource-intensive and (2) messes up plain-text formatting. We should consider installing Atom or something similar.

https://flathub.org/apps/details/io.atom.Atom

**Comment by FabioLolix** [comment]
I would not consider Atom a simple text editor (and probably not in very best shape, last stable release rely on Electron 9, last beta on Electron 11, current Electron is 18), I suggest **xed** for Cinnamon and **kate** for Plasma

**Comment by LukeShortCloud** [comment]
Hey @FabioLolix , you're absolutely right: Atom is not "simple." I was biased because I use it a lot and it provides good text editing functionality. That being said, it is bigger both in installation size and scope of what we should use as a default text editor. Thanks for the suggestions! We'll move forward with the use of xed and kate then.
