### ISSUE TITLE
Barebones install?

### ISSUE THREAD

**Issue by Frostyman758** [LukeShortCloud/winesapOS#362]
Would it be possible to have an iso Wich is a barebones install? My only usecase is steam and a lot of the preinstalled programs really aren't something I want to have around. 
I'd use holoiso to achieve this but it's so goshawfully frustrating and annoying to setup I just want something that works. 
Would it be possible?
Is it possible for me to make myself?

**Comment by LukeShortCloud** [comment]
Hey @Frostyman758 , thanks for your suggestion! This is a very popular request! We have a feature request open here to provide a new "minimal" image: https://github.com/LukeShortCloud/winesapOS/issues/254 . The goal is to have an 8 GB image with a basic SteamOS install. I have been doing a lot of preparation work towards this over the past few months. We should have this in an upcoming release in the next few months. 🙂

**Comment by LukeShortCloud** [comment]
@Frostyman758 We now have an alpha release of a minimal image if you'd like to help us test it!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.2.0-alpha.0
