### ISSUE TITLE
Updating packages bricks the system

### ISSUE THREAD

**Issue by tooelitepete** [LukeShortCloud/winesapOS#393]
1. I updated the packages as was asked of me during initial install. I then rebooted....and it hangs at the initial boot screen. So updates basically brick the system.
Any reason as to why or how I can fix this? On an Arch system updates are necessary.

3. Pressed Ctrl+2, took me into the performance overlay menu, but the toggle for enabling performance overlay cannot be enabled (grayed out) and there is no option for FSR.
How do I fix this?

**Comment by LukeShortCloud** [comment]
Let's keep one bug report per GitHub issue. I'll open a separate issue for FSR.

**Comment by LukeShortCloud** [comment]
The broken update is a known issue. The latest SteamOS 3.2 release provides a new `linux-firmware-neptune-rtw-debug` package that replaces `linux-firmware`. This only provides hardware support for the Steam Deck and no other devices.

More information about the original issue can be found here: https://github.com/LukeShortCloud/winesapOS/issues/372

I have just merged our release candidate branch into the "stable" branch which is used for upgrades. We now have a fix you can apply: run the "winesapOS Upgrade" desktop shortcut, do NOT upgrade system packages first, but upgrade winesapOS when prompted.

Regarding Arch Linux packages, SeamOS uses packages from Arch Linux that are over 5 months old. They likely will not update those any time soon. I'm about to release 3.1.0-rc.0 where we, in winesapOS, now use the latest upstream Ach Linux packages. The way the repositories are setup in this upcoming release will prevent new SteamOS packages from replacing existing packages. Once you do the winesapOS upgrade, all these changes will be applied to your system automatically.

**Comment by tooelitepete** [comment]
@LukeShortCloud I tried to run the WinesapOS Upgrade and doing as you said but it fails with the GPD keys.
gpg: error reading key: No data

On all of them.

**Comment by LukeShortCloud** [comment]
That is expected behavior. Those are not actually errors. It's updating the package keyrings to find which ones are old and adding new ones. Having outdated GPG keys from Pacman maintainers is a common issue with Arch Linux that we've addressed as part of our own upgrade path.

Run winesapOS Upgrade and wait for a pop-up that says the upgrade is complete. The terminal is only there for debugging/developer purposes. I'd like to improve the UI/UX with it.

**Comment by tooelitepete** [comment]
Your solution works. Excellent.

**Comment by LukeShortCloud** [comment]
I updated our upgrade script to check if the conflicting `linux-firmware-neptune-rtw-debug` package is installed. If so, we uninstall it and install the correct `linux-firmware` package.

Additional changes to how we handle and use package repositories have been made so this should not be an issue again in the future with other packages.
