### ISSUE TITLE
Steam Deck UI not running fullscreen (small windowed)

### ISSUE THREAD

**Issue by tooelitepete** [LukeShortCloud/winesapOS#401]
As the title says. I have to maximize it each time it starts up.
I want it to run fullscreen each time and upon bootup. Any way to achieve this?

**Comment by LukeShortCloud** [comment]
If you have an AMD or Intel GPU then you can use Gamescope. There are some hints in this article in how to get it to be fullscreen: https://ps4linux.com/steam-deck-ui-ps4-linux/

**Comment by tooelitepete** [comment]
It worked. Thanks
