### ISSUE TITLE
Winesap won't boot on the Deck after initial update with SteamOS installed

### ISSUE THREAD

**Issue by QushyQushy** [LukeShortCloud/winesapOS#424]
Hello I managed to break my SteamOS install yesterday trying to play Halo Infinite so I decided to put Winesap on my 512 GBs SD Card to  check if I can get the game working there. I flashed the card and boted just fine the first time. After the initial update that happens though I rebooted and Winesap wouldn't boot on any kernel or Snapshot. The moment I pressed Enter on an option in Grub I would go back to the Boot Manager of the Steam Deck.

I managed to circumvent this by installing Nobara on my Deck's M.2 and writing this from the same Winesap instalation that wouldn't boot before (I launched Winesap from Nobara's Bootlader). Also is there any way to launch Winesap in gaming mode?

EDIT: Just tried Winesap's bootloader after an upgrade. With Nobara installed things seem to be working fine there as well.
EDIT2: Apparently even the recovery image SteamOS won't boot if you have a bootloader with Winesap on it.

**Comment by LukeShortCloud** [comment]
Thanks for reporting this!

The SteamOS Game Mode is currently on our roadmap for our 3.5.0 release and currently does not work: https://github.com/LukeShortCloud/winesapOS/milestone/13 . Right now we only have desktop mode as that has been our target audience.

I last booted my Steam Deck into winesapOS 3.1.0-beta.1 and it worked. The only major problem for me was that the screen was not rotated correctly: https://github.com/LukeShortCloud/winesapOS/issues/366

Strange that there would be an issue with conflicting bootloaders. Also interesting that it works on the first boot but not after running through the first-time setup. I'll look more into this.

**Comment by QushyQushy** [comment]
> Thanks for reporting this!
> 
> The SteamOS Game Mode is currently on our roadmap for our 3.5.0 release and currently does not work: https://github.com/LukeShortCloud/winesapOS/milestone/13 . Right now we only have desktop mode as that has been our target audience.
> 
> I last booted my Steam Deck into winesapOS 3.1.0-beta.1 and it worked. The only major problem for me was that the screen was not rotated correctly: #366
> 
> Strange that there would be an issue with conflicting bootloaders. Also interesting that it works on the first boot but not after running through the first-time setup. I'll look more into this.

Oh, awesome! Definitely checking out when gaming mode is a thing then!
Yeah first boot went flawlessly, after the winesap script ran on first boot it wouldn't even try to boot. Just sent em straight to the Boot Selection screen.

**Comment by LukeShortCloud** [comment]
Somewhat related, I'm also very interested in getting Halo Infinite working. I've been keeping up with the Proton developers closely. I may soon ship the necessary modified drivers. The latest GE-Proton already includes the patches for vkd3d-proton, too.

https://github.com/LukeShortCloud/winesapOS/issues/365#issuecomment-1166591785

**Comment by QushyQushy** [comment]
> Somewhat related, I'm also very interested in getting Halo Infinite working. I've been keeping up with the Proton developers closely. I may soon ship the necessary modified drivers. The latest GE-Proton already includes the patches for vkd3d-proton, too.
> 
> [#365 (comment)](https://github.com/LukeShortCloud/winesapOS/issues/365#issuecomment-1166591785)

Awesome! Yeah if that happens let me know, I'll test it ASAP!

**Comment by LukeShortCloud** [comment]
@QushyQushy I could not replicate the issue on my Steam Deck using winesapOS 3.1.0 performance image.

Could you try two things?

(1) First, see if the GRUB theme is the issue. This sounds exactly like a problem we keep having with our Steam Big Picture theme for GRUB. Most recently, a problem similar to this was reported here: https://github.com/LukeShortCloud/winesapOS/issues/327 . After the first-time setup is complete and before you reboot, disable the GRUB theme by commenting it out. Then reboot when done.

```
$ sudo nano /etc/default/grub
#GRUB_THEME=/boot/grub/themes/SteamBP/theme.txt
$ sudo grub-mkconfig -o /boot/grub/grub.cfg
```

(2) If that works, try out a different theme such as Vimix. Take notice that this theme name uses an upper-case `V` in `Vimix` that is part of the `GRUB_THEME` path. If that still does not work for you, we will not use a GRUB theme anymore because it is not worth having unbootable systems.

```
$ sudo pacman -S grub-theme-vimix
$ sudo nano /etc/default/grub
GRUB_THEME=/usr/share/grub/themes/Vimix/theme.txt
$ sudo grub-mkconfig -o /boot/grub/grub.cfg
```

**Comment by LukeShortCloud** [comment]
@QushyQushy Can you try this fix below?

After doing a bunch of testing, I have narrowed down our boot issues to two things. (1) The Steam Big Picture mode theme for GRUB only works on certain graphics cards. We are going to switch themes to Vimix which is fully cross-platform. (2) We need to disable special graphics handling in GRUB themes to keep things simple and, by extension, more cross-platform as well.

```
$ sudo pacman -S grub-theme-vimix
$ sudo nano /etc/default/grub
GRUB_THEME=/usr/share/grub/themes/Vimix/theme.txt
GRUB_GFXPAYLOAD_LINUX=text
$ sudo grub-mkconfig -o /boot/grub/grub.cfg
```

**Comment by QushyQushy** [comment]
> @QushyQushy Can you try this fix below?
> 
> After doing a bunch of testing, I have narrowed down our boot issues to two things. (1) The Steam Big Picture mode theme for GRUB only works on certain graphics cards. We are going to switch themes to Vimix which is fully cross-platform. (2) We need to disable special graphics handling in GRUB themes to keep things simple and, by extension, more cross-platform as well.
> 
> ```
> $ sudo pacman -S grub-theme-vimix
> $ sudo nano /etc/default/grub
> GRUB_THEME=/usr/share/grub/themes/Vimix/theme.txt
> GRUB_GFXPAYLOAD_LINUX=text
> $ sudo grub-mkconfig -o /boot/grub/grub.cfg
> ```

I will need to reinstall. Give me some time and I'll get back to you.

**Comment by LukeShortCloud** [comment]
I was finally able to replicate the issue myself! I was originally testing winesapOS off of an external SSD, not the internal microSD card. Switching the GRUB theme to Vimix and setting the GFX payload definitely fixes it. I'll work on pushing a 3.1.1 patch release soon that addresses this.

**Comment by QushyQushy** [comment]
> I was finally able to replicate the issue myself! I was originally testing winesapOS off of an external SSD, not the internal microSD card. Switching the GRUB theme to Vimix and setting the GFX payload definitely fixes it. I'll work on pushing a 3.1.1 patch release soon that addresses this.

Ok thank you so much! :)

**Comment by LukeShortCloud** [comment]
@QushyQushy 3.1.1 is out now to address boot issues! https://github.com/LukeShortCloud/winesapOS/releases/tag/3.1.1
