### ISSUE TITLE
Use a Manjaro and SteamOS hybrid for build releases

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#429]
I am not comitting to overhauling our GitHub release images this but I do want to point out a few recent issues that do not exist with our Manjaro builds:

- KDE Plasma randomly crashes. Manjaro is using a slightly older and more tested version of the Plasma desktop environment.
- https://github.com/LukeShortCloud/winesapOS/issues/418 = Pamac is fully supported.
- https://github.com/LukeShortCloud/winesapOS/issues/427 = DKMS is a slightly older version that is known to work.
- Major upgrades from winesapOS 2 to 3 would be smoother since 2 was based on Manjaro. Related: https://github.com/LukeShortCloud/winesapOS/issues/229
- [arch-chroot and udev issues](https://github.com/LukeShortCloud/winesapOS/issues/435).
- Conflicting wireplumber packages causing upgrade issues with winesapOS 3.1.0 to 3.1.1: https://archlinux.org/news/undone-replacement-of-pipewire-media-session-with-wireplumber/

These issues are all reminders of why I personally switched from Arch Linux to Manjaro a few years ago. It was less of a headache.

Downsides:

- Possible issues with AUR builds.
    - There are currently no known issues today but this is a common problem with Manjaro having older packages than Arch Linux. At least they are a lot newer than what SteamOS ships.
- Possible issues mixing SteamOS packages
    - This is unlikely as we have successfully proven that out with Arch Linux.
- Minor upgrades from Arch Linux to Manjaro will be painful.
    - Alternatively, we can keep winesapOS 3.0 and 3.1 users on Arch Linux and have a parallel/separate upgrade path for Manjaro moving forward.

Related: https://github.com/LukeShortCloud/winesapOS/issues/281

**Comment by LukeShortCloud** [comment]
@Daasin You may have some thoughts on this. :-)

**Comment by LukeShortCloud** [comment]
Moving forward, I will offer stable hybrid Manjaro releases to for our top-tier Patreons. Anyone can build it and we have clear instructions for it in both our README.md and DEVELOPER.md documentation. It is a LOT of work to maintain so many types of winesapOS. For public/free builds, we will continue to use an Arch Linux hybrid.

@Daasin , you were the first to ask for this and you've been a big supporter of our project so I'll give you a download to our stable Manjaro release once it is available. 🙂

**Comment by Daasin** [comment]
> Moving forward, I will offer stable hybrid Manjaro releases to for our top-tier Patreons. Anyone can build it and we have clear instructions for it in both our README.md and DEVELOPER.md documentation. It is a LOT of work to maintain so many types of winesapOS. For public/free builds, we will continue to use an Arch Linux hybrid.
> 
> @Daasin , you were the first to ask for this and you've been a big supporter of our project so I'll give you a download to our stable Manjaro release once it is available. 🙂

Will definitely be looking forward to this! :D I suppose it would be a big shift as an upgrade and would probably involve running older versions of packages, but has benefits after it. Was a shame in SteamOS with a split between read-only and then user sections of the system, felt that Manjaro repo's could have addressed that by not touching anything that is handled by the Steam side and allowing users to get from more sources other than the limited options in SteamOS/Arch

**Comment by Daasin** [comment]
> Moving forward, I will offer stable hybrid Manjaro releases to for our top-tier Patreons. Anyone can build it and we have clear instructions for it in both our README.md and DEVELOPER.md documentation. It is a LOT of work to maintain so many types of winesapOS. For public/free builds, we will continue to use an Arch Linux hybrid.
> 
> @Daasin , you were the first to ask for this and you've been a big supporter of our project so I'll give you a download to our stable Manjaro release once it is available. 🙂
 
Will definitely be looking forward to this! :D I suppose it would be a big shift as an upgrade and would probably involve running older versions of packages, but has benefits after it. Was a shame in SteamOS with a split between read-only and then user sections of the system, felt that Manjaro repo's could have addressed that by not touching anything that is handled by the Steam side and allowing users to get from more sources other than the limited options in SteamOS/Arch

**Comment by Daasin** [comment]
> Moving forward, I will offer stable hybrid Manjaro releases to for our top-tier Patreons. Anyone can build it and we have clear instructions for it in both our README.md and DEVELOPER.md documentation. It is a LOT of work to maintain so many types of winesapOS. For public/free builds, we will continue to use an Arch Linux hybrid.
> 
> @Daasin , you were the first to ask for this and you've been a big supporter of our project so I'll give you a download to our stable Manjaro release once it is available. 🙂
 @LukeShortCloud  
  
 
Will definitely be looking forward to this! :D I suppose it would be a big shift as an upgrade and would probably involve running older versions of packages, but has benefits after it. Was a shame in SteamOS with a split between read-only and then user sections of the system, felt that Manjaro repo's could have addressed that by not touching anything that is handled by the Steam side and allowing users to get from more sources other than the limited options in SteamOS/Arch

**Comment by LukeShortCloud** [comment]
Yeah, upstream SteamOS today leaves a lot to be desired. Even Valve seems to be considered with the stability of Arch Linux as they have not updated their packages for 7 months now. They are providing some pre-built AUR packages which is interesting (for MangoHUD, GameMode, and a few others). I love Flatpak but some packages I need (file system drivers, Docker, etc.) cannot be installed safely on SteamOS. A system update would just wipe local changes!

I can't promise an upgrade path from our current variant of winesapOS to a Manjaro + SteamOS one. I've tried doing a switch like that on my own PC a few years ago and it failed horribly lol. I expect it will need to be a fresh install.

On the bright side, I've personally found Manjaro packages to be more stable overall and the Pamac package manager we provide was made and designed for/by the Manjaro project.
