### ISSUE TITLE
GPD WIN MAX DISPLAY ISSUE

### ISSUE THREAD

**Issue by Sparda333** [LukeShortCloud/winesapOS#441]
any one has fix for the double vision of the display? Or does anyone know how to create a custom aspect ratio? to get the correct display from the Win Max.

**Comment by LukeShortCloud** [comment]
This is something we want to address in our first-time setup. I've been doing some initial research about the Steam Deck, which has a similar problem with screen orientation, here: https://github.com/LukeShortCloud/winesapOS/issues/366

For the bootloader, these commands should fix the resolution for your device (copy and paste these into "Konsole" and then press enter):

```
sudo sed -i s'/GRUB_GFXMODE=.*/GRUB_GFXMODE=720x1280,auto/'g /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg
```

Once logged in, you can open up "System Settings" and go to "Display" to change the orientation of the screen.

I'm not sure what you mean by double vision. If that's still an issue, could you provide a picture?

Hopefully this information helps!

**Comment by Sparda333** [comment]
How do I bring up konsole is it in grub?
