### ISSUE TITLE
Error when launching Steam: OpenGL GLX Extension not supported by display

### ISSUE THREAD

**Issue by rkr87** [LukeShortCloud/winesapOS#447]
I'm receiving the above error when trying to launch Steam using any of the shortcuts created after running the first time setup script.

I assume this is something to do with the nVidia drivers/my graphics card but I don't really know where to start trying to debug this stuff on Linux.

I have a RTX 2070, if this is something I can fix myself I'd be happy to do the work, I just need pointing in the right direction.

**Comment by LukeShortCloud** [comment]
Thanks for reporting this!

Have you rebooted your computer after the first-time setup? That is required to load the correct NVIDIA drivers.

Also, could you open up the "Konsole" application, run these commands (copy and paste), and then provide the output here in this GitHub issue? This will tell us what graphics drivers are loaded.

```
lsmod | grep -P "nvidia|nouveau"
glxinfo | grep renderer
vulkaninfo | grep driverName
```

What version of winesapOS are you using?

Hopefully we can help get this fixed up!

**Comment by rkr87** [comment]
I've tried a fresh install and several reboots to no avail.

Below is the output of the commands:
`[winesap@winesapos ~]$ lsmod | grep -P "nvidia|nouveau"
[winesap@winesapos ~]$ glxinfo | grep renderer
Error: couldn't find RGB GLX visual or fbconfig
[winesap@winesapos ~]$ vulkaninfo | grep driverName
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
WARNING: [Loader Message] Code 0 : loader_scanned_icd_add: Driver /usr/lib/libvulkan_intel.so supports Vulkan 1.2, but only supports loader interface version 4. Interface version 5 or newer required to support this version of Vulkan (Policy #LDP_DRIVER_7)
ERROR: [Loader Message] Code 0 : libLLVM-13.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_radeon.so.Ignoring this JSON
ERROR: [Loader Message] Code 0 : libLLVM-13.so: cannot open shared object file: No such file or directory
ERROR: [Loader Message] Code 0 : loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib/libvulkan_lvp.so.Ignoring this JSON
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
ERROR: [Loader Message] Code 0 : loader_scanned_icd_add: Could not get 'vkCreateInstance' via 'vk_icdGetInstanceProcAddr' for ICD libGLX_nvidia.so.0
ERROR: [Loader Message] Code 0 : setup_loader_term_phys_devs:  Failed to detect any valid GPUs in the current config
ERROR at /build/vulkan-tools/src/Vulkan-Tools-1.3.217/vulkaninfo/vulkaninfo.h:231:vkEnumeratePhysicalDevices failed with ERROR_INITIALIZATION_FAILED
`
I'm using 3.1.1.

Thanks.

**Comment by LukeShortCloud** [comment]
Thanks for providing that information! This tells me that the first-time setup did try to install the proprietary NVIDIA driver but it failed.

What Linux kernel are you using? Linux LTS works best with NVIDIA graphics card. Linux Neptune has some known issues. We used to mention that in our release notes but stopped when we defaulted to the Linux LTS kernel instead. You can find the full version of your kernel by running this command:

```
uname -a
```

Could you also upload the first setup log as an attachment to this GitHub issue? Follow these example commands for getting that log. It will be slightly different depending on what the time stamp is. Grab the log at the top (which will be the oldest). It will be placed into your "Downloads" folder.

```
sudo ls -1 /etc/winesapos/
sudo cp /etc/winesapos/setup_2022-06-30T04:36:39+00:00.log ~/Downloads/
```

**Comment by LukeShortCloud** [comment]
I just bought a NVIDIA RTX 2080 card to test out support for the new open source graphics driver. I'll also see if I can replicate this issue.

**Comment by LukeShortCloud** [comment]
@rkr87 I could not replicate the issue with my RTX 2080. Are you on a laptop by chance?

The only other thing I can think of is that if you went through the first-time setup before networking was fully configured and up then the drivers would not be able to be downloaded and installed. Could you try running the "winesapOS First-Time Setup" application on the desktop again? Be sure that your Internet is up first. Open Firefox and browse to a website or ping google.com from the CLI. Once you get to the step after the graphics driver installation (where it asks you about swap) just ignore that and go ahead and reboot your computer.

**Comment by ellitedev** [comment]
I'm getting the same error on an Intel sytem (CPU: Intel Pentium N3700, GPU: Intel HD Graphics for Intel Celeron Processor N3000 Series)
Included is the entire error log. 

`Loaded SDL version 2.23.1-7331155
OpenGL GLX extension not supported by display
OpenGL GLX extension not supported by displaysrc/steamUI/Main.cpp (387) : Assertion Failed: Error: OpenGL GLX extension not supported by display
src/steamUI/Main.cpp (387) : Assertion Failed: Error: OpenGL GLX extension not supported by display
Installing breakpad exception handler for appid(steam)/version(1660688177)
assert_20220915131958_6.dmp[2058]: Uploading dump (out-of-process)
/tmp/dumps/assert_20220915131958_6.dmp
/usr/share/themes/Breeze/gtk-2.0/widgets/entry:70: error: unexpected identifier 'direction', expected character '}'

(steam:2013): Gtk-WARNING **: 13:19:58.957: Unable to locate theme engine in module_path: "adwaita",
/usr/share/themes/Breeze/gtk-2.0/widgets/styles:36: error: invalid string constant "combobox_entry", expected valid string constant
steamwebhelper.sh[2063]: Runtime for steamwebhelper: defaulting to /home/winesap/.local/share/Steam/ubuntu12_64/steam-runtime-heavy
Installing breakpad exception handler for appid(steam)/version(1660688177)
steamwebhelper.sh[2063]: glibc >= 2.34, partially disabling sandbox until CEF supports clone3()
glXChooseVisual failed
glXChooseVisual failedsrc/steamUI/Main.cpp (387) : Assertion Failed: Error: glXChooseVisual failed
src/steamUI/Main.cpp (387) : Assertion Failed: Error: glXChooseVisual failed
crash_20220915131959_8.dmp[2086]: Uploading dump (out-of-process)
/tmp/dumps/crash_20220915131959_8.dmp
assert_20220915131958_6.dmp[2058]: Finished uploading minidump (out-of-process): success = yes
assert_20220915131958_6.dmp[2058]: response: CrashID=bp-a8826975-7d42-4eb3-8e2c-f91f12220915
assert_20220915131958_6.dmp[2058]: file ''/tmp/dumps/assert_20220915131958_6.dmp'', upload yes: ''CrashID=bp-a8826975-7d42-4eb3-8e2c-f91f12220915''
crash_20220915131959_8.dmp[2086]: Finished uploading minidump (out-of-process): success = yes
crash_20220915131959_8.dmp[2086]: response: CrashID=bp-ecff4a09-2528-453b-a598-e9b5d2220915
crash_20220915131959_8.dmp[2086]: file ''/tmp/dumps/crash_20220915131959_8.dmp'', upload yes: ''CrashID=bp-ecff4a09-2528-453b-a598-e9b5d2220915''
/home/winesap/.local/share/Steam/steam.sh: line 796:  2013 Segmentation fault      (core dumped) "$STEAMROOT/$STEAMEXEPATH" "$@"`

**Comment by LukeShortCloud** [comment]
Thanks for your additional report @ellitedev ! I unfortunately have not been unable to reproduce this issue on my AMD, Intel, or NVIDIA graphics devices.

I believe your issue comes down to one of two things:

1. mesa-steamos requiring a special llvm-steamos package. We actually do not use that as a dependency right now because it is so old that it conflicts with many packages that are newer in our SteamOS + Arch Linux hybrid build.

2. mesa-steamos is built against SteamOS 3.0. Since winesapOS is targeting a much newer version of Arch Linux, we may need to build it against the exact library versions. Related to this, I was thinking of publishing additional Pacman repositories: `[winesapos-steamos]` (pure SteamOS), `[winesapos-arch]` (SteamOS + Arch Linux), and `[winesapos-manjaro]` (SteamOS + Manjaro). 

We are evaluating different paths forward for handling the open source Mesa drivers. Since we already provide never packages of everything that SteamOS does, we may even switch to a newer Mesa which also has the added benefit of being faster and better (especially for Intel graphics).

For the original report of NVIDIA driver issues, those do not even touch Mesa. That tells me that the NVIDIA driver failed to build during the first-time setup for some unknown reason.

We will continue to work on a solution for these problems for our upcoming 3.2.0 release.

**Comment by LukeShortCloud** [comment]
@ellitedev I have a third theory that this could simply be due to outdated mesa-steamos packages.

Could you try installing mesa-steamos from our testing repository to see if this fixes your original issue? It's a newer version from SteamOS 3.3. You can copy and paste these commands into Konsole or Terminator:

```
sudo sed -i s'/\[winesapos\]/\[winesapos-testing\]/'g /etc/pacman.conf
sudo pacman -S -y
sudo pacman -S \
  mesa-steamos \
  libva-mesa-driver-steamos \
  mesa-vdpau-steamos \
  opencl-mesa-steamos \
  vulkan-intel-steamos \
  vulkan-mesa-layers-steamos \
  vulkan-radeon-steamos \
  vulkan-swrast-steamos \
  lib32-mesa-steamos \
  lib32-libva-mesa-driver-steamos \
  lib32-mesa-vdpau-steamos \
  lib32-opencl-mesa-steamos \
  lib32-vulkan-intel-steamos \
  lib32-vulkan-mesa-layers-steamos \
  lib32-vulkan-radeon-steamos \
  lib32-vulkan-swrast-steamos
```

If you're no longer using winesapOS, you can grab and use the minimal image which is a small download: https://github.com/LukeShortCloud/winesapOS/releases/tag/3.2.0-alpha.0

**Comment by LukeShortCloud** [comment]
Here's a 4th theory: legacy Xorg drivers could be causing an issue for AMD and Intel graphics. I think this is the least likely problem but it's possible. Either way, in our next release we are dropping support for those.

https://github.com/LukeShortCloud/winesapOS/commit/5c9786efc192063f3710446403f51d81641199fd

**Comment by LukeShortCloud** [comment]
@rkr87 @ellitedev We have a new beta release out that should improve graphics compatibility across all platforms. Can you give this a try?

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.2.0-beta.0
