### ISSUE TITLE
[repo] Publish a SteamOS 3.4 container

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#460]
When SteamOS 3.4 is released. It will finally have new Arch Linux packages. Publish to `ekultails/steamos:3.4` and update `ekultails/steamos:latest`.

Then use that container in our repository build script.

**Comment by LukeShortCloud** [comment]
Related: https://github.com/LukeShortCloud/winesapOS/issues/461

**Comment by bowes332frank** [comment]
https://gist.github.com/red-dragon65/c7771a9347840fbcf5528f1528769836

**Comment by LukeShortCloud** [comment]
We could potentially use the container image provided by [holoiso](https://hub.docker.com/r/thevakhovske/holoiso) instead of continuing to maintain our own.

**Comment by LukeShortCloud** [comment]
HoloISO does not update their container.

**Comment by LukeShortCloud** [comment]
We do not have a need for a SteamOS container nor has the community had any demand for it.
