### ISSUE TITLE
[install] Balena Etcher fails to install

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#462]
When using the default Arch Linux + SteamOS installation type. We may need to tweak the installation step to be based on the detected operating system and not the target operating system.

```
+./winesapos-install.sh:462 [[steamos == steamos ]]
+./winesapos-install.sh:463> chroot /winesapos /usr/bin/pacman --noconfirm -S --needed balena-etcher
resolving dependencies...
warning: cannot resolve "electron12", a dependency of "balena-etcher"
```

**Comment by FabioLolix** [comment]
electron12 have been removed from Arch repo

**Comment by LukeShortCloud** [comment]
Yeah, looks like there's only Electron 17 through 20 packages as of right now.

https://archlinux.org/packages/?sort=&q=electron&maintainer=&flagged=

**Comment by LukeShortCloud** [comment]
I figured out the underlying issue. SteamOS provides its own build of balena-etcher but it's built using Arch Linux packages from 2022-01. It has Electron 9 through 16 available.

https://steamdeck-packages.steamos.cloud/archlinux-mirror/community/os/x86_64/

We need to just provide our own build of Balena Etcher in the winesapOS repository built with a newer Electron.

**Comment by LukeShortCloud** [comment]
I also tried installing `etcher-bin` (a rebuild of a Debian package) but it fails to run with a segfault. There is an AppImage from the official website (not on the AUR). Maybe we should ship that instead.

https://github.com/balena-io/etcher/releases/download/v1.7.9/balena-etcher-electron-1.7.9-linux-ia32.zip

**Comment by LukeShortCloud** [comment]
I believe their website has the wrong download link. This AppImage works properly:

https://github.com/balena-io/etcher/releases
https://github.com/balena-io/etcher/releases/download/v1.7.9/balenaEtcher-1.7.9-x64.AppImage
