### ISSUE TITLE
Failed to open archive: Multi-disk zip archives not supported

### ISSUE THREAD

**Issue by rockass14** [LukeShortCloud/winesapOS#463]
Hi there.
I'm new to Linux and I installed holoiso in order to use the steam deck ui.
But I had problems due to the NVIDIA 1050ti that I own so I wanted to try the WINEAPOS.
But when I download the files and try to extract them I get the message ''Failed to open archive: Multi-disk zip archives not supported''.
I have tried also other unzip applications.
Lastly the PeaZip does not get installed.

**Comment by LukeShortCloud** [comment]
Hey @rockass14 , thanks for letting us know. I'd be happy to help!

HoloISO is a great project but has historically had a lot of problems with NVIDIA dGPUs. I know they're trying to resolve that and are testing new builds of Mesa (the Linux graphics drivers) to address that.

We have taken the graphics drivers that the Steam Deck uses and re-enabled NVIDIA support. I daily drive winesapOS on a NVIDIA RTX 1080 in my gaming PC and now also have a 2080 in my build server so it definitely works on winesapOS!

What operating system are you using right now? What's the error you're getting when installing PeaZip? Using PeaZip would be the easiest option. If you're comfortable with the command line, you can use this command to extract the release image (assuming you have [7z](https://www.7-zip.org/download.html) installed):

```
7z x winesapos-performance-3.1.1.img.zip
```

**Comment by LukeShortCloud** [comment]
@rockass14 You can try using WinRAR as an alternative, too: https://www.isunshare.com/blog/extract-multi-volume-rar-zip-file-in-winrar/

**Comment by LukeShortCloud** [comment]
You can use 7z, Keka (macOS), PeaZip, or WinRAR to extract the zip files. Please let us know if you need any further assistance with this.
