### ISSUE TITLE
Blank/Transparent window when launching Steam Deck client

### ISSUE THREAD

**Issue by huhugh221** [LukeShortCloud/winesapOS#467]
I've looked if this is a duplicate, and it seems that I'm the first one who got the issue.
I have a Rx580 AMD gpu, with Vulkan support.

**Comment by huhugh221** [comment]
Nevermind, seems like using mesa instead of mesa-steamos did the job.

**Comment by LukeShortCloud** [comment]
Thanks for opening a bug report! That's interesting that `mesa-steamos` does not work. I maintain that package on the AUR and the source code is straight from Valve. The only difference is we build it to support more drivers than just AMD.

I wonder if they have removed source code for older generation AMD devices. It could also be a bug in that older Mesa version. I recently updated the package on the AUR from SteamOS 3.0 to 3.3. I'd be interested to see if that fixes your issue as winesapOS is not shipping it in our stable repository yet. You can either build it yourself from the AUR or tomorrow I can give you more details on how to use our testing repository which has a build of it. Ideally, we want the `mesa-steamos` package to work on all hardware.

**Comment by LukeShortCloud** [comment]
@huhugh221 Could you try installing `mesa-steamos` from our testing repository to see if this fixes your original issue? You can copy and paste these commands into Konsole or Terminator:

```
sudo sed -i s'/\[winesapos\]/\[winesapos-testing\]/'g /etc/pacman.conf
sudo pacman -S -y
sudo pacman -S \
  mesa-steamos \
  libva-mesa-driver-steamos \
  mesa-vdpau-steamos \
  opencl-mesa-steamos \
  vulkan-intel-steamos \
  vulkan-mesa-layers-steamos \
  vulkan-radeon-steamos \
  vulkan-swrast-steamos \
  lib32-mesa-steamos \
  lib32-libva-mesa-driver-steamos \
  lib32-mesa-vdpau-steamos \
  lib32-opencl-mesa-steamos \
  lib32-vulkan-intel-steamos \
  lib32-vulkan-mesa-layers-steamos \
  lib32-vulkan-radeon-steamos \
  lib32-vulkan-swrast-steamos
```
