### ISSUE TITLE
First-time setup does not properly rotate Steam Deck screen

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#469]
@Daasin you mentioned to me on Twitter that the screen rotation was not working on your Steam Deck using the 3.2.0-alpha.0 release. Do you remember if you had any external displays hooked up to your Steam Deck while going through the first-time setup?

**Comment by LukeShortCloud** [comment]
Apologies, it was actually @QushyQushy who messaged me about this issue on Twitter.

**Comment by QushyQushy** [comment]
> Apologies, it was actually @QushyQushy who messaged me about this issue on Twitter.

I think something might have gone wrong during setup after all. I can't use my root password, I'm using `winesap` as the password, I don't know if that's correct. I also don't have Firefox in the installation.

**Comment by LukeShortCloud** [comment]
The root password should be `root`. We aim to keep the password the same as the username.

We removed Firefox from the minimal image in this build but it should be installable via the first-time setup. We're probably going to add it back. One use case is a fresh setup of winesapOS may need to connect to public or hotel WiFi and that usually requires a web browser to login.

How big is your storage device? Are you using a microSD card or something else?

Could you also provide the output of the `xrandr` command? I can use that data to accurately simulate rotating the screen of your exact device.

**Comment by QushyQushy** [comment]
I'm using a 512 GBs SD Card yeah.

Here are the logs, the system still won't rotate even from the Settings:

[setup.log](https://github.com/LukeShortCloud/winesapOS/files/9524549/setup.log)

[xrandr.txt](https://github.com/LukeShortCloud/winesapOS/files/9524550/xrandr.txt)

**Comment by LukeShortCloud** [comment]
Thanks for providing that information, @QushyQushy ! I have been so busy moving that I had to put winesapOS on hold for a couple of weeks. I'm back now!

Good news, I found two problems I can fix.

1. Your internal display is reported differently during the first-time setup and after a reboot. Originally it is `eDP-1` and then it changes to `eDP`. I am not sure why this would happen but I may be able to workaround this now that I know that can happen.

    ```
    +/home/winesap/.winesapos/winesapos-setup.sh:31> export embedded_display_port=eDP-1
    ```
    ```
    eDP connected primary 800x1280+0+0 60mm x 60mm
    ```

2. During the first-time setup, we install the legacy Xorg driver for AMD graphics. This prevents `xrandr` from being able to rotate the screen. It needs a modesetting driver and this legacy driver does not support that. I need to remove this from the first-time setup.

    ```
    +/home/winesap/.winesapos/winesapos-setup.sh:47> sudo pacman -S --noconfirm extra/xf86-video-amdgpu
    ```

**Comment by QushyQushy** [comment]
Nice I'm glad you figured it out! :) Gonna test again on the next release! :)

**Comment by LukeShortCloud** [comment]
Thanks for being such a huge supporter of the project! :-) I hope to have a beta release sometime in October with fixes for this.

**Comment by QushyQushy** [comment]
Of course! This is probably what I'm using on my Deck after Gaming Mode is out. Thanks for making such a cool product! :)

**Comment by LukeShortCloud** [comment]
I can confirm that the legacy Xorg drivers haven been causing issues related to this. Here's what I observed after installing those drivers (which used to be pre-installed and, more recently, were instead installed during the first-time setup):

- The xrandr display name changes which breaks assumptions we have in our rotation logic.
- The resolutions and refresh rates become more limited.
- The legacy Xorg drivers do not support screen rotation with xrandr but, rather, it relies on custom resolutions that need to be defined.

The fix is to stop installing those drivers altogether. I already have that fix merged in. There are a few more bugs and features I want to address before shipping 3.2.0-beta.0 but I'll let you know when I do.

Also, since you mentioned Steam Deck's Game Mode, I do finally have some direction on how to implement that in winesapOS thanks to help from the PS4Linux project. From my initial research, it's fully supported on AMD graphics, somewhat supported on NVIDIA graphics, and completely broken on Intel graphics. Either way, we'll eventually have an option for Game Mode.

**Comment by LukeShortCloud** [comment]
@QushyQushy I believe that screen rotation on the Steam Deck has been fixed in our new beta release. Can you give it a try on your device?

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.2.0-beta.0

On a related note, could you boot into the `linux-steamos` kernel and then install this package to see if the speakers work on your Steam Deck? It doesn't seem to work on mine.

```
pacman -S --noconfirm jupiter-hw-support
```

https://github.com/LukeShortCloud/winesapOS/issues/444
