### ISSUE TITLE
[install] Use open source Broadcom Wi-Fi drivers

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#505]
For our 4.0.0 release. These work better on Apple Silicon.

https://lwn.net/Articles/879910/

In 3.2.0, we switched to the proprietary `broadcom-wl` driver.

We will basically need to revert this: https://github.com/LukeShortCloud/winesapOS/issues/494

**Comment by LukeShortCloud** [comment]
The open source driver also works better with T2 Macs but also requires copying firmware from macOS.

https://wiki.t2linux.org/guides/wifi-bluetooth/

**Comment by besanur** [comment]
I couldn't get the wifi to work with any of the instructions from t2linux. I got no output with the command `modinfo brcmfmac | grep 4387`  in winesapos. Then i tested this with the [older Wi-Fi guide](https://github.com/t2linux/wiki/blob/a4b46a7cfbe7efcbb6a0b6111e22172b0f5c4a77/docs/guides/wifi.md) and again no success.

how exactly do I have to proceed? Or is my Macbook not supported

I have an Macbook Pro 15 (2018) -> MacbookPro15,1

**Comment by LukeShortCloud** [comment]
@besanur Thanks for reporting your issue! Hopefully we can help you get to the bottom of this.

We currently force the proprietary driver `wl` from Broadcom. This causes conflicts with the open source driver that is required for Macs with the Apple T2 security chip. This seems to be more trouble than it's worth so we'll switch back to the open source driver in our next release.

Here is a possible workaround for your issue now:

```
sudo rm -f /etc/modprobe.d/winesapos.conf
sudo rm -f /etc/modules-load.d/winesapos-wifi.conf
sudo pacman -R -n -s --noconfirm broadcom-wl-dkms
sudo mkinitcpio -P
```

Then try following the instructions from the [t2linux wiki](https://wiki.t2linux.org/guides/wifi-bluetooth/) again. Let me know if that works or not.

**Comment by LukeShortCloud** [comment]
We will add an option to install the proprietary Broadcom drivers during the first-time setup but default to the open source driver in the release images in winesapOS 3.3.0.
