### ISSUE TITLE
Unable to install Steam Games, "Read-only file system"

### ISSUE THREAD

**Issue by sybenx** [LukeShortCloud/winesapOS#536]
I've flashed winesapOS 3.2.0 Performance to my [USB SSD](https://www.amazon.com/SSK-Super-Fast-Transfer-Adapter-Smartphone/dp/B09KG6QTYP) with balenaEtcher on Windows 11. After booting, I'm able to use pre-installed applications like Prism Launcher but after installing Steam through the Discover store I can't install Steam games. I get "DISK WRITE ERROR". Opening Applications (bauh) gives the error that I have a "Read-only file system" and to contact the system administrator.

**Comment by LukeShortCloud** [comment]
@sybenx Thanks for reporting your issue! Sorry to hear about the problems. I suspect this is an issue with resizing the root file system that happens automatically upon first boot.

Can you open Konsole, run these 3 commands, and then provide the output? Either a copy and paste of the output or a sreenshot.


```
df -h
lsblk
mount
```

**Comment by sybenx** [comment]
![20221228_150613](https://user-images.githubusercontent.com/2048087/209877319-32d65b6c-9637-4983-92d2-a3d6d644668c.jpg)

Unfortunately, can't get Firefox to open because of profile error.

**Comment by LukeShortCloud** [comment]
Thanks for providing that information, @sybenx ! The good news is that your root partition did resize properly. Your output also shows that the file system was writeable at that time.

I've seen this exact problem if the USB storage device was moved (even if very slightly). A quick disconnect causes Linux to stop using the local file system and only rely on what was left loaded in RAM. This leads to "Read-only filesystem" errors. The only solution is to reboot at that point.

**Comment by sybenx** [comment]
If this is the case, it is strange. I made 4 or 5 attempts wiping and reflashing two different ssd usb drives with two different desktop computers and did not move the drive while it was in the machines. Each attempt ended with this issue or with a Mac fan daemon error preventing boot. I've been running fedora since on the same drive without this issue. Happy to do more experimentation if it would be useful.

**Comment by sybenx** [comment]
Nevermind, i am wrong. I just had this issue on my fedora install

**Comment by sybenx** [comment]
> I've seen this exact problem if the USB storage device was moved (even if very slightly). A quick disconnect causes Linux to stop using the local file system and only rely on what was left loaded in RAM. This leads to "Read-only filesystem" errors. The only solution is to reboot at that point.

Are you aware of an upstream place I could track this bug?

**Comment by LukeShortCloud** [comment]
No, I'm not aware of any upstream bugs tracking this. It's more of a known (1) Linux behavior and (2) hardware problem (loose USB device, loose port, etc.). It's a complicated situation because if the operating system drive gets disconnected, there's no guarantee (in fact it's highly unlikely) for the system libraries and tools to be in-tact and loaded into RAM to remount the file system. I would expect Windows To Go to be a similar, if not worse, experience.

**Comment by sybenx** [comment]
I've tried Windows To Go and it failed with a "USB 3 ERROR" before booting to login with all usb ports on my PC.

I'm curious what setup is generally used by the winesapOS community to not face this issue as frequently as me.

With fedora, the usb ports directly on my motherboard have the Drive Not Writeable issue immediately after logging in. The ports on the usb hub on the front of my computer have lasted hours or days without the issue.

 It's an desktop machine built brand new only a few months ago with tight fitting ports. The USB drives are brand new and tight fitting. The machine is not getting bumped or moved as far as i can tell unless its something microscopic. 

It seems like a laptop or a steam deck would having this issue constantly...

**Comment by LukeShortCloud** [comment]
That is very strange that you're experiencing that on new hardware. I wish I could be more help but unfortunately I don't have much to share in terms of specific recommendations. It's such a generic issue, too, that looking for solutions online is almost impossible. Avoid adapters and use direct connections where possible is my best advice.

Both me and my friend have MacBook Pros with 4x USB-C ports. He has a 2017 model and I have a 2019 model. His has lots of random disconnect problems even when he swears he didn't move anything. Mine, on the other hand, works 9 out of 10 times. It only disconnects when I obviously moved my Mac around.

I always bring a Samsung Fit flash drive around with me with winesapOS installed when I'm traveling. That seems to work well. I also use a generic USB-A external SSD drive for testing winesapOS on various computers. The cable is extremely loose and I'm surprised it even works lol.

Most of our users on the Steam Deck and GPD Win Max devices use a microSD. For normal computers and laptops, a lot of folks are actually running it on the internal drive. My original goal for the project is for it to be highly portable and it is from a software perspective. If I ever find a magical solution, I'll definitely update our `README.md` file on the main GitHub page with details about it.
