### ISSUE TITLE
Trying to update or install anything through pacman fails. 

### ISSUE THREAD

**Issue by 99powerbreaker** [LukeShortCloud/winesapOS#537]
So I have been trying to download qemu through pacman. By using the command
sudo pacman -S qemu
And out comes:
```
error: could not register 'winesapos' database (database already registered)
warning: database file for 'jupiter' does not exist (use '-Sy' to download)
:: There are 3 providers available for qemu:
:: Repository extra
   1) qemu-base  2) qemu-desktop  3) qemu-full

Enter a number (default=1): 1
error: failed to prepare transaction (could not find database)

```
I then try to update pacman via: 
sudo pacman -Syu
and it looks like everything else updates but when I get to Jupiter:
```

--2022-12-26 13:06:09--  https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter/os/x86_64/jupiter.db
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving steamdeck-packages.steamos.cloud (steamdeck-packages.steamos.cloud)... 2600:1405:7000::684b:a3a3, 2600:1405:7000::684b:a38b, 104.75.163.163, ...
Connecting to steamdeck-packages.steamos.cloud (steamdeck-packages.steamos.cloud)|2600:1405:7000::684b:a3a3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-12-26 13:06:10 ERROR 404: Not Found.

```
I check to see and it seems the actual link would be to https://steamdeck-packages.steamos.cloud/archlinux-mirror/jupiter-main/os/x86_64/jupiter-main.db as the original jupiter is no long maintained it seems? Either way I'm not sure where it is pulling this file for updating, but looking around I do see that in /etc/pacman.conf it mentions jupiter as:

[jupiter]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch
SigLevel = Never

but I am not sure if this is an issue on my end that I can somehow fix, if it is an issue with winesapos, or if it is an issue with pacman, or what. Any help is much appreciated and thank you for making this amazing project as things have worked out well so far! If you need anything else that I can provide let me know.

This is bare metal running the performance image of winesapos 3.2.0 and I have tried doing the upgrade icon on the desktop which does not seem to help.

**Comment by LukeShortCloud** [comment]
@99powerbreaker Thank you for reporting this! This is a big problem that we will have to get a new minor release out soon to address.

SteamOS 3.0 through 3.3 had these repositories from most stable to least:

1. `jupiter`
2. `jupiter-beta`
3. `jupiter-main`

The same naming scheme goes for the Holo repository they host.

With the stable release of SteamOS 3.4, they renamed the (1) stable and (2) beta repositories. What they are using now, I'm not currently sure. I'll have to compare package versions and repos to what my Steam Deck is using.

**Comment by LukeShortCloud** [comment]
Okay, I did some digging and found that this is the new repository structure as of SteamOS 3.4:

- `[holo|jupiter]-rel` = Stable release.
- `[holo|jupiter]-staging` = Beta release.
- `[holo|jupiter]-main` = Unstable release.

https://steamdeck-packages.steamos.cloud/archlinux-mirror/

You can fix this by running these commands:

```
sudo sed -i s'/\[holo\]/\[holo-rel\]/'g /etc/pacman.conf
sudo sed -i s'/\[jupiter\]/\[jupiter-rel\]/'g /etc/pacman.conf
sudo pacman -S -y -y
```

Let me know if that works for you, @99powerbreaker !

**Comment by 99powerbreaker** [comment]
@LukeShortCloud It got further than before, and sudo pacman -Syu actually worked! (though it does have to update a lot of packages.) It seems everything went well, and qemu installed fine!
![Selection_004](https://user-images.githubusercontent.com/99379078/211114927-485d3213-5fd0-47bd-9ef5-99ef4ad1a1c1.png) it did say there were no modules but I think we're in business! 
I did notice one other thing. When I searched qemu in the search bar on the bottom left it did come up with "Virtual Machine manager" (aka virt manager) but failed to come up on the store. That might be for another reason though XD
it says: "Could not open appstream://virt-manager.desktop because it was not found available in any software repositories. Please report this issue to the packagers of your distribution. (can't screen shot it atm as discovery hides itself when using shutter to screenshot) This could be a steam os thing though. Thought I should report anyway.

**Comment by LukeShortCloud** [comment]
The no modules found is part of a different issue being tracked here: https://github.com/LukeShortCloud/winesapOS/issues/532

The second issue with not being able to install `virt-manager` is because SteamOS disables the use of installing Pacman applications through Discover (you can only install Flatpaks). A quick search online says that installing `packagekit-qt5` (or, preferably, the newer `packagekit-qt6`) will add that integration back in. I'll open a new/separate issue to track us adding that package in winesapOS.

With that being said, our recommended package manager is bauh. There is a "Applications (bauh)" desktop shortcut in winesapOS 3.2.0. It can install Pacman, AUR, Flatpak, and Snap packages.

**Comment by 99powerbreaker** [comment]
Alright sounds good, thanks for your help!
And got it, I actually didn't realize that there was another package manager! (I clicked on it and it reminded of a package install on Linux lite) but used discovered since the search function points you in the direction of discover. But now I know! Thanks for your hard work on this project, and I'm looking forward to the future of it!

**Comment by LukeShortCloud** [comment]
Either way, I'll definitely be adding improved support for the Discover package manager. A lot of folks are used to that from KDE Plasma / the Steam Deck.

Glad to help out and thank you for your support! I've seen a handful of people complain about things not working on winesapOS on various forums and Discord channels. Doesn't help me or the project at large if there's no bug report opened on GitHub about these things! Reporting these problems is really helpful so I can't thank you enough!

I'll go ahead and close this issue out. I have a fix tested and merged into the `main` branch regarding the new repository names. The release page for 3.2.0 has also been updated with this as a known issue along with the workaround.
