### ISSUE TITLE
Support dual-boot on the same storage device

### ISSUE THREAD

**Issue by ACCESSDENIIED** [LukeShortCloud/winesapOS#538]
I've just created a 63gb partition on my C drive in the hopes I would be able to install this on that partition but when at the flashing drive selection, it's telling me that i cannot use the partition without wiping the entire drive out first. Is there a way around this? I'd like to keep my windows install and create a dual boot for this.

Thanks!

**Comment by LukeShortCloud** [comment]
Hey @ACCESSDENIIED , thanks for your interest in winesapOS!

Currently, winesapOS only supports a single-boot setup that takes up the entire drive. I recommend using an external drive for now. We do have a future update planned to add a proper installer to deal with things such as dual-boot scenarios.

Related: https://github.com/LukeShortCloud/winesapOS/issues/370

**Comment by ACCESSDENIIED** [comment]
Great stuff! Can't wait! I'm currently on attempt number 2 on my SanDisk Flash USB 3.2 16gb for the minimal setup. First attempt seems to have been stuck at the starting arch screen (waited 10 minutes) after selecting linux-steamos.
Hopefully attempt number 2 is a success! :)

**Comment by LukeShortCloud** [comment]
The Linux LTS kernel will likely work better. Linux SteamOS is provided for Steam Deck hardware compatibility but it's old and insecure (Valve has yet to officially rebase it).

Upon first boot, winesapOS resizes the root file system to take up all available space. That make take a long time on a flash drive. I've switched to external SSDs for testing as the performance is a night and day difference!

Let me know if you get the minimal image working or if you need any other assistance. I'd be happy to help. 🙂

**Comment by ACCESSDENIIED** [comment]
Yeah that seems to have been the case, the SteamOS option did not work. Selecting LTS almost immediately booted into arch and  prompted for the first time setup. Unfortunately I wasn't able to get it working in the end despite multiple reformats and reinstalls. The most progress I was able to make was by opting out of swap and trim on my usb drive which seems to have prevented the black screen issues I was experiencing previously. The last installation I performed did run right through to the end, although I still wasn't able to launch steam. I did see the steam desktop shortcuts that the setup created but those only seemed to open with kate or kwrite as steam doesn't seem to have installed in the setup process despite me choosing to install it. Manually downloading steam from the discovery store did prompt for the root password which i entered but upon launch, it threw a few errors - lib c, org platform, etc.

Overall I had fun last night trying to set this all up! :) It's unfortunate that it didn't work for me though.

**Comment by LukeShortCloud** [comment]
It sounds like you may be running out of storage space. That is a common cause for random crashes like this. Depending on what you select during the first-time setup, it can easily exceed your 16 GB flash drive size. You can verify how much space is being used by running the `df -h`. Glad you're having fun, at least!

**Comment by LukeShortCloud** [comment]
@ACCESSDENIIED We just added initial support in winesapOS for dual-booting with Windows! I will have a 4.1.0-beta.0 release out soon with the needed changes. It requires an intermediate amount of knowledge to setup with Linux but we have documented all of the required steps. We may look into simplifying the process in the future.

**Comment by LukeShortCloud** [comment]
We have added a lot more improvements to hardware compatibility in winesapOS recently. I know you mentioned having trouble booting even the normal portable image. That should be fixed now, too!
