### ISSUE TITLE
Touch Bar issue on MacBook Pro 16" 2019

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#54]
The Touch Bar does not work.

This guide may provide some hints on how to fix it:

https://gist.github.com/gbrow004/096f845c8fe8d03ef9009fbb87b781a4

**Comment by ekultails** [comment]
This did not help:

```
$ sudo vim /etc/modprobe.d/apple-tb.conf
options apple-ib-tb fnmode=2
$ sudo mkinitcpio -p linux510
```

**Comment by ekultails** [comment]
I have never gotten this working on my own MacBook Pro 16" 2019 model. However, I do know that Mac Linux Gaming Stick 1 was reported working with MacBook Pro 2017 + Ubuntu 20.04 + Linux 5.4 + the touchbar driver. I will have access to that device again soon for further testing but it will not be until after the 2.1.0 release.

**Comment by ekultails** [comment]
This might be our problem:

```
$ sudo journalctl -a | less
touch-bar-usbmuxd-fix.service: Failed with result 'exit-code'.
Failed to start Re-enable MacBook Pro Touch Bar after the 'usbmuxd.service'.
```

**Comment by ekultails** [comment]
Try building and using this fork of the touchbar driver: https://github.com/PatrickVerner/macbook12-spi-driver

**Comment by ekultails** [comment]
I am at a loss for how to get this working on the last Intel MacBook Pros that have come out around 2019. I am removing the milestone for this fix and will leave it open until we can find a workaround or a solution.

**Comment by LukeShortCloud** [comment]
The Linux 5.18 kernel may fix this. Refer to: https://github.com/LukeShortCloud/winesapOS/issues/10

**Comment by LukeShortCloud** [comment]
Starting the Linux 5.18, here are the key bindings for MacBook Pros with Touch Bars. This is most useful for accessing function `f<NUMBER>` keys without using a Touch Bar by using the physical `fn` key.

There is one for models that has a dedicated `esc` (ESCAPE) key and a second for models that do not have an `esc` key.

```
+static const struct apple_key_translation macbookpro_no_esc_fn_keys[] = {
+	{ KEY_BACKSPACE, KEY_DELETE },
+	{ KEY_ENTER,	KEY_INSERT },
+	{ KEY_GRAVE,	KEY_ESC },
+	{ KEY_1,	KEY_F1 },
+	{ KEY_2,	KEY_F2 },
+	{ KEY_3,	KEY_F3 },
+	{ KEY_4,	KEY_F4 },
+	{ KEY_5,	KEY_F5 },
+	{ KEY_6,	KEY_F6 },
+	{ KEY_7,	KEY_F7 },
+	{ KEY_8,	KEY_F8 },
+	{ KEY_9,	KEY_F9 },
+	{ KEY_0,	KEY_F10 },
+	{ KEY_MINUS,	KEY_F11 },
+	{ KEY_EQUAL,	KEY_F12 },
+	{ KEY_UP,	KEY_PAGEUP },
+	{ KEY_DOWN,	KEY_PAGEDOWN },
+	{ KEY_LEFT,	KEY_HOME },
+	{ KEY_RIGHT,	KEY_END },
+	{ }
+};
+
+static const struct apple_key_translation macbookpro_dedicated_esc_fn_keys[] = {
+	{ KEY_BACKSPACE, KEY_DELETE },
+	{ KEY_ENTER,	KEY_INSERT },
+	{ KEY_1,	KEY_F1 },
+	{ KEY_2,	KEY_F2 },
+	{ KEY_3,	KEY_F3 },
+	{ KEY_4,	KEY_F4 },
+	{ KEY_5,	KEY_F5 },
+	{ KEY_6,	KEY_F6 },
+	{ KEY_7,	KEY_F7 },
+	{ KEY_8,	KEY_F8 },
+	{ KEY_9,	KEY_F9 },
+	{ KEY_0,	KEY_F10 },
+	{ KEY_MINUS,	KEY_F11 },
+	{ KEY_EQUAL,	KEY_F12 },
+	{ KEY_UP,	KEY_PAGEUP },
+	{ KEY_DOWN,	KEY_PAGEDOWN },
+	{ KEY_LEFT,	KEY_HOME },
+	{ KEY_RIGHT,	KEY_END },
+	{ }
+};
+
```

We should document this when we upgrade our Linux kernel.

https://patches.linaro.org/project/linux-input/patch/B17D84D1-F91C-4CF0-A931-C19D0278E329@live.com/
https://www.phoronix.com/scan.php?page=news_item&px=Linux-5.18-HID

**Comment by LukeShortCloud** [comment]
The touch bar driver was never upstreamed. The community is attempting to upstream it again.

https://www.phoronix.com/news/Apple-Touch-Bar-Linux-2023

**Comment by LukeShortCloud** [comment]
This is dependent on upstream work that is out of our hands. We'll continue to track the progress of improvements to the MacBook Pro Trouchbar driver via: https://github.com/LukeShortCloud/winesapOS/issues/10
