### ISSUE TITLE
System Freezes Every Few Seconds | Repository Links Return ERROR 404

### ISSUE THREAD

**Issue by singhdilveer1** [LukeShortCloud/winesapOS#540]
Since the first boot the system has been consistently freezing every few seconds. After some diagnostics, the culprit seems to be kswapd (swapper). I'm not sure if it's messing with some I/O stuff or overloading the CPU.

While trying to diagnose this, I came across another issue while trying to install linux tools; the repo config seems to have outdated links. I had to manually change the config for all repos on the stuttery mess. WineSap repo just returns forbidden error, there was no way for me to fix that so I just had to comment that out.

I'm not sure how to collect logs. Arch is really difficult to mess around with.

**Comment by LukeShortCloud** [comment]
Thanks for reporting these issues, @singhdilveer1 ! Hopefully I can help out.

- Swap = You are experiencing high swap usage from some program(s). Check `top -c` next time this is happening to see what program(s) are using an excess of memory. If you have not done the first-time setup, there is no swap. Have you done that? If so, how much swap do you have configured? In our next update we plan to lower the swappinness from 10% to 1% (the generic Linux kernel default is 60%, for reference). You can manually adjust that by editing the file `etc/sysctl.d/00-winesapos.conf` and then run the command `sysctl -p` or reboot.
- Repositories:
     - SteamOS = Less than a week after we released winesapOS 3.2.0, Valve released SteamOS 3.4 to the stable update channel. When they did that, they also renamed all the repository directories they use which broke old installations of SteamOS (in winesapOS 3.2.0, we use SteamOS 3.3). I will release a hotfix for everyone soon.
     - winesapOS = As for the winesapOS repository, that temporarily went down due to data enter maintenance from my hosting provider. I used to have a highly available repository but could no longer afford it. The server is back online now.

**Comment by LukeShortCloud** [comment]
We have officially released winesapOS 3.2.1 to address the repository issues: https://github.com/LukeShortCloud/winesapOS/releases/tag/3.2.1

@singhdilveer1 Were you able to run a `top -c` to see what process(es) are using the most amount of system resources?

**Comment by LukeShortCloud** [comment]
We've also deceased the swappinness level in our new release to improve performance (especially on slower storage mediums).

I'll go ahead and close this out. Feel free to re-open this GitHub issue if you still encounter any performance problems with winesapOS 3.2.1.
