### ISSUE TITLE
Failed to convert .img to parallel disk or iso

### ISSUE THREAD

**Issue by MikNewCal** [LukeShortCloud/winesapOS#559]
Hi All,
I have issues to convert .img to parralel readable disk

> Mac-mini:Downloads xiu$ qemu-img -h | grep Supported
Supported formats: blkdebug blklogwrites blkverify bochs cloop compress copy-before-write copy-on-read dmg file ftp ftps host_device http https luks nbd null-aio null-co parallels preallocate qcow qcow2 qed quorum raw replication snapshot-access ssh throttle vdi vhdx vmdk vpc vvfat

> Mac-mini:Downloads xiu$ file -s winesapos-minimal-3.2.1.img
winesapos-minimal-3.2.1.img: **DOS/MBR boot sector, extended partition table (last)**

> Mac-mini:Downloads xiu$ qemu-img info winesapos-minimal-3.2.1.img
image: winesapos-minimal-3.2.1.img
file format: raw
virtual size: 7 GiB (7516192768 bytes)
disk size: 7 GiB

> Mac-mini:Downloads xiu$ fdisk winesapos-minimal-3.2.1.img
Disk: winesapos-minimal-3.2.1.img	geometry: 913/255/63 [14680064 sectors]
Signature: 0xAA55
         Starting       Ending
 #: id  cyl  hd sec -  cyl  hd sec [     start -       size]
------------------------------------------------------------------------
 1: EE    0   0   2 - 1023 255  63 [         1 -   14680063] <Unknown ID>
 2: 00    0   0   0 -    0   0   0 [         0 -          0] unused
 3: 00    0   0   0 -    0   0   0 [         0 -          0] unused
 4: 00    0   0   0 -    0   0   0 [         0 -          0] unused

> 

I tried to convert to vmdk, but not readable by parralel

> Mac-mini:Downloads xiu$ qemu-img convert -f raw -O vmdk winesapos-minimal-3.2.1.img winesapos.vmdk
> 
> Mac-mini:Downloads xiu$ chmod -RN /Users/xiu/Downloads/winesapos.vmdk
> Mac-mini:Downloads xiu$ prl_convert /Users/xiu/Downloads/winesapos.vmdk --allow-no-os
> Conversion progress: 0 %
> The source virtual disk contains no operating system.

**Comment by LukeShortCloud** [comment]
This appears to be a known issue in Parallels 17 as it is reported as working in 16. [1][2] Try adding the `--stand-alone-disk` argument to the `prl_convert` command.

Alternatively, it looks like `qemu-img` supports converting directly to the `parallels` format.

```
qemu-img convert -f raw -O parallels winesapos-minimal-3.2.1.img winesapos-minimal-3.2.1.hdd
```

I do not have Parallels to test this with. Let me know if you get this working or if you continue to run into any issues. Once we get it sorted out, I will update the winesapOS documentation.

1. https://forum.parallels.com/threads/parallels-17-prl_convert-cannot-convert-vmdk.354906/
2. https://forum.parallels.com/threads/prl_convert-allow-no-os.359613/

**Comment by MikNewCal** [comment]
Hi @LukeShortCloud, thanks for your fast reply, still having issues and looking for the best solutions

Try #1  qemu-img converting directly to the parallels format / Fail

> Mac-mini:Downloads xiu$ qemu-img convert -f raw -O parallels winesapos-minimal-3.2.1.img winesapos-minimal-3.2.1.hdd 

![image](https://user-images.githubusercontent.com/126290702/221303823-6c1e2f97-fd51-4a86-b8da-7b5838815639.png)

Try #2  qemu-img converting to vmdk and prl_convert 

> Mac-mini:Downloads xiu$ prl_convert /Users/xiu/Downloads/winesapos.vmdk --allow-no-os --stand-alone-disk --dst=/Users/xiu/Downloads/vmdk
> Conversion progress: 100 %
> Estimated size: 6155763712 bytes
> Resulting VM boot firmware type: 0
> Resulting path: '/Users/xiu/Downloads/vmdk'
> The source third-party virtual disk was successfully converted to a Parallels virtual disk stored in /Users/xiu/Downloads/vmdk.

Importing to the vm config as a hard drive :
![image](https://user-images.githubusercontent.com/126290702/221304732-5ce45182-40a8-4fb2-ad15-c73de7b9bdab.png)

error : no os installed on this vm, secure boot disabled : 
![image](https://user-images.githubusercontent.com/126290702/221304903-04c8f98b-6fd5-4e2b-831a-e9b1dc54f970.png)

Still trying

**Comment by MikNewCal** [comment]
# test 3 , flash img with [balenaEtcher](https://www.balena.io/etcher/) to a flash drive and boot into flash drive

 booting fail, no os

**Comment by MikNewCal** [comment]
Maybe it's because Mac M1 ARM can't run x86/64 image.

**Comment by LukeShortCloud** [comment]
Yeah, traditional virtualization platforms such as Parallels and VMware Fusion can only run Arm operating systems on Apple Silicon. You can use QEMU to emulate a x86 system but there's a big performance hit and no GPU acceleration.

**Comment by MikNewCal** [comment]
Hardware limitation
