### ISSUE TITLE
Installing Gnome gives me dependency errors

### ISSUE THREAD

**Issue by Rapou7** [LukeShortCloud/winesapOS#574]
I tried to install Gnome using pacman and it cannot satisfy some dependencies.

Thanks beforehand.

**Comment by Rapou7** [comment]
Here is the error message i get:

`
error: failed to prepare transaction (could not satisfy dependencies)
:: installing libvpx (1.13.0-1) breaks dependency 'libvpx.so=7-64' required by ffmpeg4.4
:: installing gst-plugins-base-libs (1.22.1-2) breaks dependency 'gst-plugins-base-libs=1.22.0' required by gst-plugins-base
`

**Comment by LukeShortCloud** [comment]
Hey @Rapou7 , thanks for reporting your issue! Hopefully we can get to the bottom of it.

It sounds like winesapOS needs a full system update first. It is complaining that GNOME needs newer dependencies than what is currently installed.

Try running the "winesapOS Upgrade" desktop shortcut (this will take a long time to complete) and then install GNOME. Let me know if that works for you or not.

**Comment by Rapou7** [comment]
It works now, how could I not have thought of that.

Thanks for the help

**Comment by LukeShortCloud** [comment]
Glad it worked! I'll go ahead and close this GitHub issue as resolved.

**Comment by LukeShortCloud** [comment]
@Rapou7 On a somewhat related note, you may run into an issue with our graphics drivers (especially if you are not using a NVIDIA graphics device) in winesapOS 3.2.1. I built and published a new Mesa package to resolve this. If Steam or other applications are not launching, you can use this to fix it:

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

A reboot will be required after that.
