### ISSUE TITLE
Add warning before canceling upgrade 

### ISSUE THREAD

**Issue by Rapou7** [LukeShortCloud/winesapOS#575]
I think it would be a nice improvement to avoid hitting the cancel button by mistake.

**Comment by LukeShortCloud** [comment]
@Rapou7 Great suggestion! I believe the "Cancel" button in the upgrade is actually misleading as it is today. The upgrade still continues in the background.

We should (1) add a "Are you sure you want to cancel?" prompt and (2) actually cancel the upgrade.

**Comment by LukeShortCloud** [comment]
@Rapou7 winesapOS 3.4.0 is out now which addresses this problem. Thank you again for your report!
