### ISSUE TITLE
Steam can't launch on macos

### ISSUE THREAD

**Issue by zeff209** [LukeShortCloud/winesapOS#580]
Hello,
I installed Winesapos on an external SSD some weeks ago to use it with my PC on Windows and its working but today I tried to use it with my MacBook Air 2019 (Intel) and when I'm trying to launch Steam I get a tiny page with Xorg logo that stays 1 sec and then disappear with :

"Update of Steam..."
Loading bar
"Verification of installation"

Do you know what could be the cause ?

**Comment by LukeShortCloud** [comment]
Are you using winesapOS 3.2.1? There is a known issue with the graphics driver. You can open up the `Konsole` terminal and paste these two commands in:

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau-steamos lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

A reboot will be required after that. Let me know if that works or not!

**Comment by zeff209** [comment]
Hello,

Yes it worked thank you !

**Comment by LukeShortCloud** [comment]
@zeff209 Glad that worked! Feel free to open another GitHub Issue if you encounter any other issues or have any ideas for new features!

**Comment by LukeShortCloud** [comment]
@zeff209 winesapOS 3.3.0 has been released to address the issues you were encountering!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0
