### ISSUE TITLE
Steam crashes with error "opengl glx extension not supported by display"

### ISSUE THREAD

**Issue by thedirptastic** [LukeShortCloud/winesapOS#586]
Whenever I launch Steam it gets to "verifying update" and crashes. I decided to run the sh file instead of the desktop file and it gave me this error: "opengl glx extension not supported by display". I am running in VMware and have selected the correct drivers and settings. I have also tried in VirtualBox but the same error occurred. All other applications work, just not steam.

Dump is [Here](https://www.mediafire.com/file/5mrt2iz5uvgx206/crash_20230518103958_8.dmp/file)

**Comment by thedirptastic** [comment]
Update: Minecraft also is not working

**Comment by LukeShortCloud** [comment]
Thanks for reporting your issue! This is a known issue with the graphics drivers in winesapOS 3.2.1. Run these two commands from `Konsole` to manually update them:

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau-steamos lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

A reboot is required once the updates finish.

Let me know if that works or not!

**Comment by thedirptastic** [comment]
Yep! This seemed to do the trick! Thank you

**Comment by LukeShortCloud** [comment]
Great, thanks for confirming! Once SteamOS 3.5 comes out, I'll publish a new build of winesapOS with fixed and upgraded graphics drivers so the workaround won't be needed in the future.

If you ever run into any other issues or have any suggestions for new features, let us know! We're always open to feedback. :-)

**Comment by LukeShortCloud** [comment]
@thedirptastic winesapOS 3.3.0 has been released to address the issues you were encountering!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0
