### ISSUE TITLE
[install] vkbasalt fails to install

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#596]
Both the `vkbasalt` and `lib32-vkbasalt` packages fail to compile and install. This is an upstream bug.

https://aur.archlinux.org/packages/vkbasalt

**Comment by FabioLolix** [comment]
I have emailed the maintainer with the patch, in the meantime here there are fixed pkgbuilds

https://github.com/FabioLolix/AURFIX/tree/main/v/vkbasalt

https://github.com/FabioLolix/AURFIX/tree/main/l/lib32-vkbasalt

**Comment by FabioLolix** [comment]
Yes, the day after upstream released a new version so my work was no longer necessary

**Comment by LukeShortCloud** [comment]
I tested out a new build of `vkbasalt` from the AUR last night and it is now working as intended. Thanks for sending in that patch, FabioLolix!
