### ISSUE TITLE
Failed to start refresh pacman mirrorlist with reflector and a fan manager daemon for macbook pro

### ISSUE THREAD

**Issue by emilien-MT** [LukeShortCloud/winesapOS#604]
The first start of the distro works well, but after the configuration at the first reboot it's stuck at :
starting systemd-udevd version ...
FAILED failed to start a fan manager deamon for macbook pro
FAILED failed to start refresh pacman mirrorlist with reflector.

Thanks for your help !

**Comment by LukeShortCloud** [comment]
@emilien-MT Thanks for reporting this issue!

Those two service failures can safely be ignored. However, we are addressing them in our upcoming winesapOS 3.3.0 release:

- https://github.com/LukeShortCloud/winesapOS/issues/563
- https://github.com/LukeShortCloud/winesapOS/issues/605

As for why it gets stuck during the reboot, I believe this is related to a graphics driver issue in winesapOS 3.2.1. As a workaround, see if you can run these two commands:

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau-steamos lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

You can access a different TTY console by pressing `CTRL`, `ALT`, and `F4`. Then, log in as the `root` user (the password is also `root`). Run the commands from there. You will need Internet access for these packages to be downloaded. Alternatively, you can try running those commands with `Konsole` on a fresh install.

Let me know if that helps or not!

**Comment by LukeShortCloud** [comment]
@Haarolean You are right, the first-time setup is completely broken thanks to updates Valve made without telling the community about them.

I'm going to try to get an update out this weekend that should fix everything (and includes a ton of new features).

**Comment by LukeShortCloud** [comment]
@emilien-MT @Haarolean  winesapOS 3.3.0 has been released to address the issues you were encountering! :-)

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0
