### ISSUE TITLE
[install] Steam should not automatically start

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#608]
We removed a workaround we needed to delete the global Steam shortcut at `/etc/xdg/autostart/steam.desktop` but accidentally bundle that file still with our new `vapor-steamos-theme-kde` package that replaces `steamdeck-kde-presets`. This is present in `vapor-steamos-theme-kde` version 0.16-1. That shortcut should not be packaged as it always starts Steam when you login which not everyone wants.

Related: https://github.com/LukeShortCloud/winesapOS/issues/590

**Comment by Equ1no0x** [comment]
Could that be causing Steam to no install and instead 2 shortcuts are just placed on the Desktop?
I just finished a fresh install and that happened to me.

**Comment by LukeShortCloud** [comment]
@Equ1no0x No, that would be unrelated. Something similar to what you're describing has happened in the past due to Valve randomly deciding to change their repository names without telling the community. That should be addressed in winesapOS 3.2.1. What version are you using?

If Steam isn't launching, it could also be an issue with the graphics driver which is a known issue in winesapOS 3.2.1. Open up `Konsole` and then run these two commands to ensure you have the updated driver:

```
sudo pacman -S -y -y
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau-steamos lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

Let me know if that works or not!

**Comment by Equ1no0x** [comment]
> Something similar to what you're describing has happened in the past due to Valve randomly deciding to change their repository names without telling the community. That should be addressed in winesapOS 3.2.1. What version are you using?

I'm using winesapOS 3.2.1
The problem is not that it doesn't start. It didn't even get installed by the First Time Setup :(

**Comment by LukeShortCloud** [comment]
Thanks for the details! I just remembered that Arch Linux removed their `[community]` package repository and, instead, merged it into the `[extra]` package repository. This would cause Steam and a few other applications to fail to install during the first-time setup. I've already fixed this problem and hope to get a stable release out in the next month or so. I'll see if I can get you a workaround in the meantime.

**Comment by Equ1no0x** [comment]
Much appreciated!

**Comment by LukeShortCloud** [comment]
@Equ1no0x As a workaround, try running these three commands to deal with the removable of the `[community]` repository:

```
sudo crudini --del community /etc/pacman.conf
sudo pacman -S -y
sudo pacman -S pacman
```

Then run this command to update the graphics driver:

```
sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau-steamos lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
```

Finally, reboot, delete the Steam shortcuts, and select the "winesapOS First-Time Setup" desktop shortcut to go through that again.

Let me know if that helps!

**Comment by Equ1no0x** [comment]
> ```
> sudo crudini --del community /etc/pacman.conf
> sudo pacman -S -y
> sudo pacman -S pacman
> ```
> 
> Then run this command to update the graphics driver:
> 
> ```
> sudo pacman -S mesa-steamos mesa-vdpau-steamos opencl-mesa-steamos vulkan-intel-steamos vulkan-mesa-layers-steamos vulkan-radeon-steamos vulkan-swrast-steamos lib32-libva-mesa-driver-steamos lib32-mesa-steamos lib32-mesa-vdpau-steamos lib32-opencl-mesa-steamos lib32-vulkan-intel-steamos lib32-vulkan-mesa-layers-steamos lib32-vulkan-radeon-steamos lib32-vulkan-swrast-steamos libva-mesa-driver-steamos
> ```
> 
> Finally, reboot, delete the Steam shortcuts, and select the "winesapOS First-Time Setup" desktop shortcut to go through that again.


Thank you for your reply!
I actually also managed to get it installed, but on a completely different route, please do let me know if this could cause any kind of conflicts and I will do it as you suggested!

PD: I literally started using Linux for the 1st time ever with this, so I could be very wrong with what I did.

I made a mirrorlist from artix:
`sudo wget https://github.com/archlinux/svntogit-packages/raw/packages/pacman-mirrorlist/trunk/mirrorlist -O /etc/pacman.d/mirrorlist-arch`

Then ran
`sudo pacman -S archlinux-keyring`

Added the mirrorlist to pacman.conf
```sudo nano /etc/pacman.conf
[extra]
Include = /etc/pacman.d/mirrorlist-arch
```

Saved and ran
`sudo pacman -Sy`

I had not entered the password to even start the First Time Setup by this point, so I started that process (I made a fresh install again, since I was testing) and it installed!

**Comment by LukeShortCloud** [comment]
Glad you got it working and welcome to the Linux gaming community! :-)

The steps you followed look good. I would just double check your `/etc/pacman.conf` file and make sure that these `[<REPOSITORY_NAME>]` repositories are all there (including the removable of the `[community]` block, if it's present). If you use "Server" or "Include" doesn't matter too much but I've found that Rackspace has the fastest mirrors (meaning faster updates).

```
[core]
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch

[extra]
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch

[multilib]
Server = https://mirror.rackspace.com/archlinux/$repo/os/$arch

[winesapos]
Server = https://winesapos.lukeshort.cloud/repo/$repo/$arch
SigLevel = Never

[jupiter-rel]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch
SigLevel = Never

[holo-rel]
Server = https://steamdeck-packages.steamos.cloud/archlinux-mirror/$repo/os/$arch
SigLevel = Never
```

**Comment by LukeShortCloud** [comment]
I fixed the theme package to no longer include the file that makes Steam launch upon logging in. Testing on my local system appears to work. I'll also build and push a repository update to `[winesapos-testing]` to make sure it works on the latest winesapOS dev build.

https://aur.archlinux.org/cgit/aur.git/commit/PKGBUILD?h=vapor-steamos-theme-kde&id=25bd2c29c8b960e2017eeaae71d82d33c54efe99

**Comment by LukeShortCloud** [comment]
I tested this last night. The new package works as intended.

**Comment by LukeShortCloud** [comment]
@Equ1no0x winesapOS 3.3.0 has been released to address the issues you were encountering!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0

**Comment by Equ1no0x** [comment]
> @Equ1no0x winesapOS 3.3.0 has been released to address the issues you were encountering!
> 
> https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0

OMG, and it was just released! I appreciate the tag! Will try it as soon as I can 💯

**Comment by LukeShortCloud** [comment]
Enjoy! :-) Let me know if you run into any issues or have any feedback. I try to add things in that my users want (not just me).

I have a very slow upload speed. Right now, only the minimal image is up. In the next 24 hours, the performance and secure images will also be available for you.

**Comment by Equ1no0x** [comment]
> Enjoy! :-) Let me know if you run into any issues or have any feedback. I try to add things in that my users want (not just me).
> 
> I have a very slow upload speed. Right now, only the minimal image is up. In the next 24 hours, the performance and secure images will also be available for you.

Awesome stuff, don't worry about it too much. There is no rush!
