### ISSUE TITLE
Less Bloated version

### ISSUE THREAD

**Issue by massatt212** [LukeShortCloud/winesapOS#613]
Do you have a Version with a look alike to steamos3 ?

**Comment by LukeShortCloud** [comment]
Hey @massatt212 , thanks for reaching out! We now have a minimal image that removes a lot of the "bloat" compared to the performance and secure images. As for looking like SteamOS 3, I've got a few GitHub issues tracking this:

- https://github.com/LukeShortCloud/winesapOS/issues/240
- https://github.com/LukeShortCloud/winesapOS/issues/241

The biggest blocker has been NVIDIA support. I've been seeing if there was anything we can do in winesapOS to improve it but it's really up to other upstream projects and the NVIDIA driver itself. The good news is that the last lingering problems should be solved soon.

- https://github.com/LukeShortCloud/winesapOS/issues/237

**Comment by massatt212** [comment]
I'm looking for a steamos image with mesa 23.1 without bloat, you should focus on AMD, until Nvidia get there act together.

**Comment by LukeShortCloud** [comment]
Reported half an hour ago, even Intel support is experimental: https://github.com/ChimeraOS/gamescope-session/blob/9a2d5ebb328dc9cb15484203774b7dff7045a9f7/usr/share/gamescope-session/device-quirks#L15

I completely agree, for Linux gaming it's AMD or nothing for the best experience. I hope to have more progress and updates on this feature in the coming weeks.
