### ISSUE TITLE
Error 0x80004005 when extracting the zip

### ISSUE THREAD

**Issue by EthanTheFrancaboo** [LukeShortCloud/winesapOS#617]
This happens with Windows's extractor, 7-ZIP, and PeaZip. It will not extract, and if I press "try again", it says that the same volume cannot be used for the source and destination.

Windows 11.
I also tried on Linux (Neon KDE/Ubuntu) and it didn't work there either. Are the zips corrupted?

**Comment by EthanTheFrancaboo** [comment]
Readme covers part of this and told me to use certutil, this is the hash it made: 236a9e7b7894b83bb6e526b99ee2a84ffdbb4f0f05cd7f4a3f693e62569834aceb1d37b46a19972a32d7d586493c85befc81bf1646ea8fb36ee54085679c9056

**Comment by LukeShortCloud** [comment]
Hey @EthanTheFrancaboo , thanks for reporting your issue! You can cross-check those checksums with the text checksums file provided with the release.

What version (3.2.1?) and variant (minimal?) are you using? Just want to confirm.

**Comment by EthanTheFrancaboo** [comment]
> Hey @EthanTheFrancaboo , thanks for reporting your issue! You can cross-check those checksums with the text checksums file provided with the release.
> 
> What version (3.2.1?) and variant (minimal?) are you using? Just want to confirm.

3.21, minimal (16gb flash drive)

**Comment by EthanTheFrancaboo** [comment]
7-Zip
![image](https://github.com/LukeShortCloud/winesapOS/assets/114692858/f1cb0bf7-c1df-4c62-aa41-ff6c0473d028)

PeaZip
![image](https://github.com/LukeShortCloud/winesapOS/assets/114692858/33adf98f-f90e-4414-8e91-d6b65d27a26e)

Windows
![image](https://github.com/LukeShortCloud/winesapOS/assets/114692858/0f9d16c2-f5e9-4884-a961-9285120dc7a0)
![image](https://github.com/LukeShortCloud/winesapOS/assets/114692858/536b155b-a6fb-4689-b79a-c103e5480aa6)
![image](https://github.com/LukeShortCloud/winesapOS/assets/114692858/8ed85a68-4c2b-4215-848b-b25d69d78766)

75gb free space

**Comment by EthanTheFrancaboo** [comment]
never downloaded the .zo1 and .zo2 lol that was the problem

**Comment by LukeShortCloud** [comment]
Glad you figured it out! Feel free to open up another GitHub Issue if you run into any other problems or have ideas for new features!
