### ISSUE TITLE
Black screen when attempting to boot

### ISSUE THREAD

**Issue by EthanTheFrancaboo** [LukeShortCloud/winesapOS#619]
When booting, this appears, as expected. 
![IMG_0461-min](https://github.com/LukeShortCloud/winesapOS/assets/114692858/d4ba5e22-4d62-4049-9cbc-1f51915f7449)

However, after booting into linux-steamos, it just gets stuck here.
![IMG_0462](https://github.com/LukeShortCloud/winesapOS/assets/114692858/085a90dc-4d56-4d7f-8bfc-c25c2f45eda2)

If I try and boot into linux-lts, it does this before booting into a login screen for a few seconds (interacting with it does nothing), before going to a black screen with the default KDE cursor, and doing nothing from there.
![IMG_0463](https://github.com/LukeShortCloud/winesapOS/assets/114692858/7c2e44bd-5bdc-4a3e-8dae-9732a42fe91a)

Doing ctrl+alt+f2 brings me to a terminal, as normal, and logging in there works. `ls` brings up directories, so it's working, but something's definitely going wrong.

**Comment by EthanTheFrancaboo** [comment]
Thought I'd leave some info and specs here.

3.2.1 Minimal
AMD Ryzen 7 5800H (CPU)
AMD Radeon(TM) Graphics (GPU #1, integrated, I think?)
AMD Radeon RX 6600M (GPU #2, dedicated)
16gb RAM

**Comment by LukeShortCloud** [comment]
@EthanTheFrancaboo Thank you for reporting this and for all of the details (they're very useful!). Your system should be fully supported. It sounds like you're running into a known graphics driver issue. You can find the fix here: https://github.com/LukeShortCloud/winesapOS/issues/598#issuecomment-1563452562

This issue is related to SteamOS packages being so old that I constantly need to rebase them on-top of the latest Arch Linux. I'm thinking in our next release to make SteamOS packages (specifically Linux SteamOS and Mesa SteamOS) optional as most of their features have already been upstreamed into the relevant projects now.

**Comment by EthanTheFrancaboo** [comment]
> @EthanTheFrancaboo Thank you for reporting this and for all of the details (they're very useful!). Your system should be fully supported. It sounds like you're running into a known graphics driver issue. You can find the fix here: [#598 (comment)](https://github.com/LukeShortCloud/winesapOS/issues/598#issuecomment-1563452562)
> 
> This issue is related to SteamOS packages being so old that I constantly need to rebase them on-top of the latest Arch Linux. I'm thinking in our next release to make SteamOS packages (specifically Linux SteamOS and Mesa SteamOS) optional as most of their features have already been upstreamed into the relevant projects now.

Alright, I'll do that. By the way, how do I install this onto my internal drive? I want to use it as my primary linux distro (and possibly just replace windows)

**Comment by LukeShortCloud** [comment]
The recommended way is to boot into the minimal image and then use Balena Etcher to install the image of your choice to the internal drive. Search for "setup winesapOS using winesapOS" in our README.md file for some hints.

https://github.com/LukeShortCloud/winesapOS/tree/3.2.1#release-builds

**Comment by EthanTheFrancaboo** [comment]
> The recommended way is to boot into the minimal image and then use Balena Etcher to install the image of your choice to the internal drive. Search for "setup winesapOS using winesapOS" in our README.md file for some hints.
> 
> https://github.com/LukeShortCloud/winesapOS/tree/3.2.1#release-builds

I want to dualboot it though

**Comment by LukeShortCloud** [comment]
Dual-boot is, surprisingly, very hard to automate. Arch Linux lacks standardized tools to do this compared to other Linux distributions. I do want to implement this feature and will be tracking development of that feature here: https://github.com/LukeShortCloud/winesapOS/issues/538

What existing operating system are you currently using and want to dual-boot with? The requires are a bit different depending on if its Linux, macOS, or Windows.

**Comment by LukeShortCloud** [comment]
@EthanTheFrancaboo winesapOS 3.3.0 has been release to address the issues you were encountering.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0

I'll go ahead and close this issue out. You can continue to track dual-boot progress here: https://github.com/LukeShortCloud/winesapOS/issues/538
