### ISSUE TITLE
WiFi not working (Intel Wireless 8265)

### ISSUE THREAD

**Issue by Moukrea** [LukeShortCloud/winesapOS#621]
Hi,

I've installed WinesapOS on an external enclosure but I'm unable to proceed to the initial setup, the WiFi is card is not detected (but I guess it does half the job, my bluetooth appear to be active), there might be an issue there, haven't encountered this issue on many other distros (Endeavour OS, ChimeraOS, Ubuntu, KDE Neon, PopOS...)

Here, it's not even listed in my network devices list, even though it appears on the list of PCI devices, if I can be of any help, let me know!

**Comment by LukeShortCloud** [comment]
Hey @Moukrea , thanks for reporting your issue! Hopefully we can help you get to the bottom of this. Do you have an Ethernet port or adapter available? The first thing I would do is to try and update the firmware files which requires (1) an Internet connection, ironically, and (2) running these two commands:

```
sudo pacman -S -y -y
sudo pacman -S linux-firmware
```

**Comment by LukeShortCloud** [comment]
@Moukrea When booting, also try using "Linux LTS" instead of "Linux SteamOS". It has better hardware support.

Let me know if any of these help.

**Comment by Moukrea** [comment]
As it turns out, after dozen of reboots, trying all boot options... I set WinesapOS as the first boot device in my BIOS and the WiFi became detected right away, maybe this trick could be documented somewhere? Like "If you encounter issues with some of your hardware not being properly detected, especially network device, please try to make the drive holding WinesapOS your primary boot device, it has been reported as fixing hardware detection issues in some instances"

We can close the issue now, thanks a million!

**Comment by LukeShortCloud** [comment]
@Moukrea Thanks for reporting back your fix! I'll be sure to document that. I've also been reading that this could be related to Windows not being fully shutdown (you need to hold down the "SHIFT" click while shutting down or do a reboot, you can use the Task Manager to see how long before a full shutdown has been done). I'll mention that as another possible fix, too.
