### ISSUE TITLE
Can i install it?

### ISSUE THREAD

**Issue by rasphan-123** [LukeShortCloud/winesapOS#625]
im trying to use one of my old laptops as a console but i want to install it. how can i do that?

**Comment by LukeShortCloud** [comment]
One thing we do not support yet is dual-boot. That is being tracked here: https://github.com/LukeShortCloud/winesapOS/issues/538

**Comment by LukeShortCloud** [comment]
@retrocountry We just added initial support in winesapOS for dual-booting with Windows! I will have a 4.1.0-beta.0 release out soon with the needed changes. It requires an intermediate amount of knowledge to setup with Linux but we have documented all of the required steps. We may look into simplifying the process in the future.
