### ISSUE TITLE
Can't extract the zip for whatever reason

### ISSUE THREAD

**Issue by rasphan-123** [LukeShortCloud/winesapOS#626]
it gives me a error and then says insert a disk

**Comment by LukeShortCloud** [comment]
@rasphan-123 have a look at this troubleshooting guide for the archive files. Let me know if any of those suggestions help: https://github.com/LukeShortCloud/winesapOS/tree/3.2.1#release-image-zip-files

**Comment by LukeShortCloud** [comment]
@rasphan-123 winesapOS 3.3.0 came out recently. Let me know if that zip files for this work for you.

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.3.0

https://github.com/LukeShortCloud/winesapOS/tree/3.3.0#release-image-zip-files

**Comment by LukeShortCloud** [comment]
I uploaded the winesapOS 3.3.0 release images to our server so it will be easier to download (you don't need to worry about extracting a lot of different split zip files): http://winesapos.lukeshort.cloud/repo/iso/

**Comment by LukeShortCloud** [comment]
@rasphan-123 winesapOS 3.4.0 is out now and includes a single zip file that is much easier to extract. Let me know if you have any further issues!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
