### ISSUE TITLE
Can't Unzip the Contents of Any File Type Available, Windows Extracting or 7Zip.

### ISSUE THREAD

**Issue by ItsJohnGit** [LukeShortCloud/winesapOS#628]
Repeated data error with every version available...

**Comment by LukeShortCloud** [comment]
Hey @ItsJohnGit , thanks for reporting your issue! Have a look at this troubleshooting guide for the archive files. Let me know if any of those suggestions help: https://github.com/LukeShortCloud/winesapOS/tree/3.2.1#release-image-zip-files

**Comment by ItsJohnGit** [comment]
I did now but It still didn't fix the issue

**Comment by LukeShortCloud** [comment]
Can you provide me the exact steps to replicate the issue on my end?

**Comment by LukeShortCloud** [comment]
I uploaded the winesapOS 3.3.0 release images to our server so it will be easier to download (you don't need to worry about extracting a lot of different split zip files): http://winesapos.lukeshort.cloud/repo/iso/

**Comment by LukeShortCloud** [comment]
@ItsJohnGit winesapOS 3.4.0 is out now and is the first release to launch with a single zip file that is much easier to extract. Let me know if you have any further issues!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
