### ISSUE TITLE
Cant Install. 

### ISSUE THREAD

**Issue by DKRacingFan** [LukeShortCloud/winesapOS#633]
Hello! I noticed there are only 3 of the minimal images and 2 of the performance images, and no secure images. When I tried to extract the performance images, I got an error saying they are corrupt. I noticed earlier builds had a lot more files. I'm not sure if I'm missing something or doing something wrong. 
![issue](https://github.com/LukeShortCloud/winesapOS/assets/57995082/63c5fc6c-9a94-443d-8bb9-21c94599c39a)

**Comment by LukeShortCloud** [comment]
Hey @DKRacingFan , thanks for reaching out! That was my bad, I should have explained the release situation better. I'm basically doing a soft launch of winesapOS 3.3.0 this weekend.

Only the minimal image is fully uploaded right now. I'm in the process of uploading the performance and secure images but my Internet upload speed is very slow. Everything needed for the performance image will be there in the next few hours. The secure image will be available tomorrow.

The two missing parts you will need for the performance image are:

- `winesapos-3.3.0-performance.img.z03`
- `winesapos-3.3.0-performance.img.zip`

No need to re-downloaded the part 01 and 02 again.

Hope this helps to clarify the situation!

**Comment by LukeShortCloud** [comment]
@DKRacingFan The performance image files just finished uploading. :-)

**Comment by LukeShortCloud** [comment]
Okay, all of the images are uploaded now. I'll go ahead and close this out.
