### ISSUE TITLE
After finishing "First-Time Setup", various screen glitches appear

### ISSUE THREAD

**Issue by vyktorjonas** [LukeShortCloud/winesapOS#634]
![IMG_3092](https://github.com/LukeShortCloud/winesapOS/assets/57778484/b8232514-085a-4edf-a7b0-f3d6309b593d)
![IMG_3093](https://github.com/LukeShortCloud/winesapOS/assets/57778484/74923ba3-963f-46eb-9b0a-e7f0287e13a7)

not sure how to describe it, I hope those images help
AMD Ryzen 9 7940HS
Radeon 780M Graphics
4K TV

**Comment by LukeShortCloud** [comment]
Hey @vyktorjonas thanks for reporting this issue! Yes, thank you, the pictures are useful. Did you select to install SteamOS packages? It can have corrupt graphics like that on devices that are not the Steam Deck. Open up `Konsole` and then run this command to return to upstream graphics. Let me know if that helps or not.

```
sudo pacman -S \
      mesa \
      libva-mesa-driver \
      mesa-vdpau \
      opencl-mesa \
      vulkan-intel \
      vulkan-mesa-layers \
      vulkan-radeon \
      vulkan-swrast \
      lib32-mesa \
      lib32-libva-mesa-driver \
      lib32-mesa-vdpau \
      lib32-opencl-mesa \
      lib32-vulkan-intel \
      lib32-vulkan-mesa-layers \
      lib32-vulkan-radeon \
      lib32-vulkan-swrast
```

**Comment by LukeShortCloud** [comment]
Glad you got it working! I switched to upstream Arch Linux packages in winesapOS 3.3.0 because of various problems like that but the option is still there for folks who want to try it out and see if it works.

winesapOS 3.4.0 will have the gamescope-session functionality you're talking about it. It's not implemented yet. We simply launch the new Big Picture Mode within the desktop environment right now.

**Comment by LukeShortCloud** [comment]
I'm going to close this Issue out. What we've talked about can be tracked in these other GitHub Issues:

- https://github.com/LukeShortCloud/winesapOS/issues/561 = Just waiting on Valve Time(TM) for them to release SteamOS 3.5. This will hopefully fix the graphical glitches.
- https://github.com/LukeShortCloud/winesapOS/issues/241 = gamescope-session support for Steam to allow not having the full desktop environment loaded when gaming.

**Comment by LukeShortCloud** [comment]
@vyktorjonas winesapOS 3.4.0 is out now to address various graphical issues. Let me know if you run into any other issues!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
