### ISSUE TITLE
NVIDIA Kepler Driver Issues

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#638]
i might have a similar issue

i flashed the os (the latest performance version as of today which is 3.3) and try to run the installation using USB.

the OS runs (showing the "arch Linux, with Linux linu" screen) and then after loading ramdisk my screen just goes black.

i do suspect it to be a graphics driver, but i don't know what can i do to solve it

i own a gtx 660 (old one...)

nvidia.modeset=0 doesn't work
nomodeset and removing the quite shows that the last line that is running is "Started Accounts Service"
but then it stuck on flickering "_"

i change the tty then i get shell, but no GUI...

_Originally posted by @Frostswing in https://github.com/LukeShortCloud/winesapOS/issues/627#issuecomment-1648600709_

**Comment by LukeShortCloud** [comment]
Hey @Frostswing , thanks for reporting your issue! That sounds like it's related to the graphics driver. Do other boot options (besides the "Arch Linux, with Linux linu") work? Try all of them. Some include more kernel drivers than others (at the expense of a longer boot time). The bottom ones are also an older kernel that may work better with your older hardware.

If/when you get to the GUI, the first-time setup will walk you through installing the correct NVIDIA drivers for your device. You want the second option of NVIDIA Kepler and newer. You can try plugging in the USB to another computer, install the appropriate drivers, and then you can use it on your NVIDIA GTX 660.

NVIDIA has stated that they are working on making their driver easier to redistribute by relaxing their redistribution and licensing agreements. I'm hoping to have perfected out-of-the-box NVIDIA support by winesapOS 3.4.0 if they follow-through with that.

**Comment by Frostswing** [comment]
hey
well i think i fixed it in some sort of way

it was multiple issues

first i managed geting to the shell
then i updated the os
then i installed nvidia drivers
then sudo pacman -S xf86-video-vesa xf86-video-fbdev
then activated plasma "echo "exec startplasma-x11" > ~/.xinitrc"
then startx worked

from then i ran the shell and lastly i ran the desktop.sh of your os

now it installs stuff. seems promising

**Comment by Frostswing** [comment]
Well update.
Even after setup and everything I still get the flickering "_" display.
I have on startup to manually change to tty2 and startx

And then the display doesn't allow me moving past the 1080 resolution... As If I don't have drivers (but if I had no drivers I would have needed to use nomodeset which isn't the case)

So I can't use this OS :(

**Comment by LukeShortCloud** [comment]
Thanks for the update. The flickering usually means there's an issue with the graphics driver. But if `startx` is working in another TTY it could also be an issue with LightDM. I'm not sure.

Sorry to hear it's not working as intended. I just bought a Kepler card so I can also test it out myself. So far, only community members have been testing Kepler cards (with success in most cases, except this one).

**Comment by LukeShortCloud** [comment]
This thread seems to suggest that `xf86-video-nouveau` needs to be installed for the first-time boot. Then, during our first-time setup, we can switch from that open source driver to the proprietary one for better performance and more features.

https://www.reddit.com/r/archlinux/comments/8m10yi/blinking_cursor_on_nvidia390xx/

**Comment by LukeShortCloud** [comment]
The Arch Wiki also suggests to not use `nvidia.modeset=0` (or `nvidia.nomodeset=1`) with the open source driver.

https://wiki.archlinux.org/title/nouveau

**Comment by LukeShortCloud** [comment]
@rostswing @pcking99 Try installing these extra Nouveau driver packages to see if this helps:

```
sudo pacman -S lib32-nouveau-dri nouveau-dri xf86-video-nouveau
```

**Comment by LukeShortCloud** [comment]
I added additional Nouveau packages and tested a development build with my new NVIDIA 780 Ti. It worked perfectly out-of-the-box. This change will be part of the upcoming winesapOS 3.4.0 release.

**Comment by pcking99** [comment]
> @rostswing @pcking99 Try installing these extra Nouveau driver packages to see if this helps:
> 
> ```
> sudo pacman -S lib32-nouveau-dri nouveau-dri xf86-video-nouveau
> ```

I am trying to install it now. Takes a bit of time as if the install fails or i get stuck at the blinking underscore i have to uninstall the HDD and copy the install iso again to it with rufus.



> I added additional Nouveau packages and tested a development build with my new NVIDIA 780 Ti. It worked perfectly out-of-the-box. This change will be part of the upcoming winesapOS 3.4.0 release.

Awsome hopefully that will help a lot of legacy devices :)

**Comment by LukeShortCloud** [comment]
@pcking99 winesapOS 3.4.0 is out now with improved support for legacy NVIDIA graphics cards. Thanks again for your report!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
