### ISSUE TITLE
[install] Build runs out of space

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#665]
At the minimum, the image size in the GitHub Actions workflow may need to be increased. At most, we may need to actually slim down the packages we install.

```
+/workdir/scripts/winesapos-install.sh:872> flatpak_install_chroot com.obsproject.Studio
+flatpak_install_chroot:1> chroot /winesapos flatpak install -y --noninteractive com.obsproject.Studio
Info: org.kde.Platform is end-of-life, with reason: We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: org.kde.Platform.Locale is end-of-life, with reason: We strongly recommend moving to the latest stable version of the Plaform and SDK
Installing runtime/com.obsproject.Studio.Locale/x86_64/stable
Installing runtime/org.kde.KStyle.Adwaita/x86_64/6.4
Installing runtime/org.kde.Platform.Locale/x86_64/6.4
Installing runtime/org.kde.Platform/x86_64/6.4
Installing app/com.obsproject.Studio/x86_64/stable
Error: Failed to install com.obsproject.Studio: Not enough disk space to complete this operation
```

https://github.com/LukeShortCloud/winesapOS/actions/runs/6413440705/job/17412348285

**Comment by ohaiibuzzle** [comment]
There are options for the `easimon/maximize-build-space@master` step that I think we can easily take advantage of
ie. `remove-{dotnet,android,codeql,haskell}`

**Comment by LukeShortCloud** [comment]
Hey @ohaiibuzzle , thanks for the suggestion! We may need that eventually.

My apologies for wording the bug report a bit wrong. I first noticed the issue in GitHub Actions but the issue is not with how much space we have in GitHub Actions. It is actually how much space we use inside our images. I can  confirm that GitHub Actions has enough space since our `fallocate` command from [here](https://github.com/LukeShortCloud/winesapOS/blob/3.4.0-beta.0/scripts/winesapos-install.sh#L78) does not fail.

```
+/workdir/scripts/winesapos-install.sh:78> fallocate -l 14GiB winesapos.img
```

winesapOS has always struggled with storage. Usually our builds have a few hundred megabytes of space left by the end. More recently, it has been 100 megabytes. Now it is zero (again). It is a constant struggle of figuring out how to best optimize space on these images. It is harder with the performance and secure images because we try to include everything and the kitchen sink. With the minimal image, we defer all of the package installations (mostly Flatpaks, which are more reliable to install than Pacman and especially AUR packages), to be part of the first-time setup which helps a lot (users can pick exactly what software they want to install).

For historical context, using Flatpaks have been the biggest increase to our space usage. We have KDE Plasma installed both natively and as a Flatpak runtime. Then there is the GNOME Flatpak runtime. Then there are many different versions of those runtimes. That is where most of our storage goes these days. In other situations, dependencies grow for some applications or they themselves simply get bigger. It is a balancing act of what to pre-install or not.

I'm open to any suggestions you might have. For this or anything else. I'm thankful for everything you've done already and value your input! :-)

**Comment by LukeShortCloud** [comment]
I was originally recommending to increase our 14 GB size image for GitHub Actions as a short-term hack. That was actually a bad suggestion, I admit, as it does not fix the real issue: we need to optimize our storage usage in the image. Otherwise, our release images will get bigger and they are already too big!

**Comment by LukeShortCloud** [comment]
Here are some observations from a recent minimal image build I did (note: the issue here affects the performance and secure images but this information may still be insight):

- Gwenview is our photo gallery app. We install it as a Flatpak. It is the only Flatpak on the minimal image. It uses 2.1 GiB because  of the KDE Plasma runtime. If we were to install it with Pacman instead, it would only use 15 MiB.
- The minimal image build starts with 7 GiB and ends up with only 127 MiB of free space on the root partition when  it is done.

More related to this issue and OBS (which is the specific app that fails to install due to lack of space right now):

- The Flatpak is 200 MiB by itself. With all of the runtime dependencies for KDE Plasma including locales, it totals 800 MiB. Those runtimes are probably required by other Flatpaks, too, so they will get installed one way or another.

**Comment by LukeShortCloud** [comment]
Okay, I switched Gwenview to be a native package. The minimal image will now have over 2 GiB more of free space from that one small change alone!

GitHub Actions is now working, too, but a did a build of the performance image locally (which the root partition size is slightly smaller than what is used in CI) and it fails to install OBS due to lack of space.

```
Warning: Failed to install org.kde.Platform.Locale: While pulling runtime/org.kde.Platform.Locale/x86_64/6.4 from remote flathub: Delta requires 654.5 MB free space, but only 526.6 MB available
```

I noticed this was not the first time that OBS has lead to space issues: https://github.com/LukeShortCloud/winesapOS/issues/556

I've come to realize that OBS does not used a shared runtime of "latest". Instead, it uses pinned versions (6.4 right now). That means it takes almost a full gigabyte to install that sucker. Wow! For that native package, it is only 120 MiB for `obs-studio` and all of its dependencies. Either (1) we install the native package or (2) defer the Flatpak install to be part of the first-time setup on the performance and secure images.

**Comment by LukeShortCloud** [comment]
I did a test build of the performance image and a lot of Flatpaks fail to install.

Since we have never had any issues installing Flatpaks (besides not having enough space), perhaps we should have a first-time setup task to ask if the user wants to install recommended Flatpaks. If not, show the minimal image package installation options (the user can pick and choose).

ClamTk anti-virus is the only package I think should definitely be pre-installed. I've found the Flatpak to be unreliable so the native package would be better and easier to use anyways.

**Comment by LukeShortCloud** [comment]
I refactored our scripts so that Flatpaks are only installed during the first-time setup. GitHub Actions runs now are up to 50% faster and we have 8.2 GiB free on the root partition. Now I can re-add things like additional firmware (about 1 GiB) and more pre-installed Mesa graphics drivers (a few hundred MiB) for better hardware support out-of-the-box. Plus, we can shrink the size of all of our release images.

**Comment by LukeShortCloud** [comment]
A release build of the performance image with all of the Linux firmware installed and without Flatpaks has 6.4 GB free. We can probably trim at least 5 GB off the performance and secure images then 1 GB off the minimal image.

Related: https://github.com/LukeShortCloud/winesapOS/issues/673
