### ISSUE TITLE
[install][upgrade] Install JFS

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#683]
The Journaled File System.

https://www.phoronix.com/news/JFS-Linux-6.7-Improvements
https://wiki.archlinux.org/title/JFS

**Comment by FabioLolix** [comment]
> IBM's journaled file system technology, currently used in IBM enterprise servers

> and IBM hasn't been endorsing its use for over a decade and a half

Honest why add it?

**Comment by LukeShortCloud** [comment]
Good question. There were plans to remove it from the kernel but apparently a few people still use it. Now they're fixing bugs for it still, too. It's a single small package for the client utilities. winesapOS is great for recovery and if a user has the right adapter for their old drive(a) with JFS, they can access the data.
