### ISSUE TITLE
Winesap OS is Borked out of the box

### ISSUE THREAD

**Issue by oblende** [LukeShortCloud/winesapOS#688]
**Describe the bug or feature**
Garbled text in the application menu before updating the OS through the Winesap OS Upgrade application. After using the application and rebooting the task bar is missing and nearly all icons are missing their labels.

**Issue Type**
- [x] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1. Boot the USB Stick
2. Use Winsap OS Upgrade

**Expected behavior**
To Boot to a Desktop without garbled text, and for update to improve the situation

**Screenshots**
![IMG_20231114_112729620](https://github.com/LukeShortCloud/winesapOS/assets/47158765/8ec1e03c-0d23-4e75-8eec-82aef2117409)
![Uploading IMG_20231114_111527969.jpg…]()

**Versions (please complete the following information):**
 - Version: [ex., 3.3.0]
 - Image type: Performance
 - Computer type: [PC]
 - Graphics vendor: [AMD]
 - Graphics card: [Radeon Rx580 2048SP]

**Additional context**

**Comment by oblende** [comment]
Here's a second image for more context.
![Uploading IMG_20231114_111527969.jpg…]()

**Comment by oblende** [comment]
Additional image for added context.

![IMG_20231114_111527969](https://github.com/LukeShortCloud/winesapOS/assets/47158765/98378cf7-2246-48df-9cec-9a1577a06a31)

**Comment by LukeShortCloud** [comment]
Hey @oblende , thank you so much for the detailed report! Did you happen to go through the first-time setup and select to install SteamOS packages? The old Mesa driver from SteamOS is known to have some issues. We're waiting for SteamOS 3.5 to be promoted to the stable update branch before updating that driver stack. With the OLED Steam Deck coming out in a couple of days, I suspect that will happen soon.

Our new winesapOS 3.4.0 release is ready to go otherwise. I can get you a beta build (it is more like a release candidate at this point, actually) to test with. We have lots of new features and bug fixes that might address this problem.

**Comment by LukeShortCloud** [comment]
Here is a beta build from a few weeks ago: http://winesapos.lukeshort.cloud/repo/iso/winesapos-3.4.0/_test/winesapos-3.4.0-beta.1-minimal.img.zip Does that work any better for you? I'm also planning a new stable release for next weekend which will include even more features and bug fixes on-top of that.

**Comment by LukeShortCloud** [comment]
I'm working out some last minute upgrade enhancements before making a public announcement but the stable winesapOS 3.4.0 images are available to download here: https://winesapos.lukeshort.cloud/repo/iso/winesapos-3.4.0/ . The graphics drivers should work better out-of-the-box.

@oblende Let me know if you ever get a chance to try it out!

**Comment by LukeShortCloud** [comment]
There have have been a few other updates that may help prevent this issue in the future:

- Mesa 23.3 is now used which is much more stable than the Mesa 23.2 series that you likely upgraded to.
    - https://github.com/LukeShortCloud/winesapOS/issues/714
- winesapOS will no longer upgrade at all if there is not a winesapOS upgrade available. This will prevent unexpected issues.
    - https://github.com/LukeShortCloud/winesapOS/issues/699

I will go ahead and close this out for now. Please feel free to let me know if you need any further help or if you notice any other issues. Thank you again for reporting your issue!

**Comment by LukeShortCloud** [comment]
@oblende winesapOS 3.4.0 is out to address these graphical issues. Thanks again for your report!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
