### ISSUE TITLE
Intel Arc support

### ISSUE THREAD

**Issue by DealsBeam** [LukeShortCloud/winesapOS#712]
Will winesapOS work fine with a system that has Intel Arc dGPU?

**Comment by LukeShortCloud** [comment]
Yes, we have enabled the Intel Arc drivers in winesapOS! In winesapOS 3.3.0, it is considered experimental still. In winesapOS 3.4.0 (coming out this weekend), it will finally be stable thanks to the updated graphics driver an updated Linux kernel.

**Comment by LukeShortCloud** [comment]
I will be adding a note about this in our release notes for winesapOS 3.4.0: https://github.com/LukeShortCloud/winesapOS/issues/720

**Comment by LukeShortCloud** [comment]
@DealsBeam wineaspOS 3.4.0 is out now with stable support for Intel Arc graphics!

https://github.com/LukeShortCloud/winesapOS/releases/tag/3.4.0
