### ISSUE TITLE
Apple M1

### ISSUE THREAD

**Issue by 1Rashoodi1** [LukeShortCloud/winesapOS#735]
Hello @LukeShortCloud ...

I have installed Asahi Linux and I was wondering on how to install Steam on here in you don't mind so that I can try helping winesapOS's Project to get to M1....

Thanks and regards
Rashid Janahi 
(Please contact me on [janahistudios@icloud.com](mailto:janahistudios@icloud.com))

**Comment by LukeShortCloud** [comment]
Thanks for your interest in in winesapOS! I'll close this GitHub Issue out as a duplicate and then we can discuss in the original Issue I opened.
