### ISSUE TITLE
[install][setup] Use Wayland by default

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#751]
Now that Wayland is maturing, 2024 seems like a good year to enable it by default.

Related:
- https://github.com/LukeShortCloud/winesapOS/issues/495
- https://github.com/LukeShortCloud/winesapOS/issues/742
    - Fedora 40 is going to have KDE Plasma 6 and Wayland enabled by default but Xorg will be support removed. winesapOS will keep Xorg installed by default but use Wayland instead.
    - https://fedoraproject.org/wiki/Changes/KDE_Plasma_6
- https://github.com/LukeShortCloud/winesapOS/issues/750
    - NVK should have native Wayland support (unlike the proprietary NVIDIA and NVIDIA-Open drivers).

**Comment by LukeShortCloud** [comment]
Screen rotation with Wayland does not work with `xrandr`. Another tool such as  `kscreen-doctor` needs to be used during the first-time setup.

https://www.reddit.com/r/wayland/comments/kuiqcl/xrandr_equivalent_on_wayland/

**Comment by wallentx** [comment]
Might be worth noting that some updates that just came through adds Xwayland to lightdm session login, and set it as default, which made lots of stuff not work.

**Comment by LukeShortCloud** [comment]
Thanks for the heads up! Based on some quick research, it seems that LightDM's support matrix is something like:

- Xorg = Works
- Xwayland = "Supported" but currently broken
- Wayland = Does not work

According to the Debian Wiki, it seems that LightDM can run with Xorg and still start a Wayland session. That might be fine for now as we will provide Xorg and Wayland+Xwayland for KDE Plasma session options.

https://wiki.debian.org/Wayland

The ArchWiki says that these are the only display managers that fully support Wayland (something to consider moving to if we ever remove Xorg in the coming years):

- GDM = Too GNOME specific. There was a reported issue (4 years ago, to be fair) where using GDM to launch KDE Plasma would not result in a smooth transition like it does with GNOME.
    - https://reddit.com/r/linuxquestions/comments/dd49ym/plasma_desktop_with_gdm_as_login_manager/
- greetd = The way it "supports" Wayland is by using its CLI-based mode.
    - https://wiki.archlinux.org/title/Greetd
- SDDM = Wayland support is still experimental.
    - https://wiki.archlinux.org/title/SDDM

https://wiki.archlinux.org/title/wayland#Display_managers

Or maybe we just wait for Xwayland support with LightDM to mature.

This is a much bigger rabbit hole than I was expecting lol. I wonder what other Linux distributions are using for a display manager in a Wayland-only world.

**Comment by LukeShortCloud** [comment]
Apparently SDDM is developed by KDE. Combine that with the fact that it supports Wayland, we should switch to that. I bet with Plasma 6 out, their Wayland support in SDDM is no longer experimental.

https://invent.kde.org/plasma/plasma-desktop/-/issues/91

**Comment by wallentx** [comment]
> Apparently SDDM is developed by KDE. Combine that with the fact that it supports Wayland, we should switch to that. I bet with Plasma 6 out, their Wayland support in SDDM is no longer experimental.
> 
> https://invent.kde.org/plasma/plasma-desktop/-/issues/91

That is indeed what the deck uses

**Comment by LukeShortCloud** [comment]
Thanks, that's good to know!
