### ISSUE TITLE
installations script fails upon install

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#829]
**Describe the bug or feature**
i couldn't install it after it said Winesapos install finished reboot to make changes I rebooted then it rebooted to nothing

**Issue Type**
- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1. install winesapos on seperate partition
2. after install reboot

**Expected behavior**
for it to install and boot.

**Screenshots**
N/A

**System information (please complete the following information):**
- Version: [4.10]
- Image type: [Minimal]
- Computer type: [PC]
- Graphics vendor: [Intel]
- Graphics card: [Haswell]
- Drive type: [Nvme SSD]
- Drive connection to PC: [USB 3.0 32 GB]

**Additional context**
I think it might be an error in the code.

**Comment by GuestSneezeOSDev** [comment]
it fails

**Comment by LukeShortCloud** [comment]
The original issue here might have been a missing partition flag for EFI.

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.0/scripts/winesapos-install.sh#L125

Thinking on this more, the `winesapos-install.sh` script was designed to handle this exact scenario. There are two problems: (1) there are various upstream bugs in Pacman right now and (2) the winesapOS installer always uses 100% of available space.

I can add workarounds for the Pacman bugs and look into adding support for defining the root file system size.

**Comment by GuestSneezeOSDev** [comment]
I have only made the usb from Balena Etcher for windows might have caused the bug but using Balena Etcher for Linux it seems to have worked

**Comment by LukeShortCloud** [comment]
Glad to hear you got that working!
