### ISSUE TITLE
[setup] Allow hiding the GRUB boot menu

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#849]
The GRUB boot menu is confusing for new users. It is unclear if the fsync or lts kernel should be select.

Related: https://github.com/LukeShortCloud/winesapOS/discussions/847

**Comment by GuestSneezeOSDev** [comment]
This may sound a little bad but could you make an image type that uses `systemd` because I am more used to that

**Comment by LukeShortCloud** [comment]
`systemd-boot`? I can add a build option for that. I looked into it recently. I don't want to default to it because it doesn't have a replacement for `os-prober` which makes dual-booting a lot nicer.
