### ISSUE TITLE
[setup] Do not prompt for password on non-secure images

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#850]
On the minimal and performance images (not the secure image), there should not be a prompt for the password. `sudo` is already configured to be passwordless for those image types.

**Comment by GuestSneezeOSDev** [comment]
Arch Linux based systems should probably have a file in this directory called `autologin.conf`which can be located here `/etc/systemd/system/getty@tty1.service.d/autologin.conf` edit it with this line of code 
```
[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin winesap --noclear %I 38400 linux
```
change the kernel to your liking ^
if there is no directory with those files try creating a directory `/etc/systemd/system/serial-getty@ttyS0.service.d/autologin.conf` with this content instead
```
[Service]
ExecStart=
ExecStart=-/sbin/agetty -o '-p -- \\u' --noclear --autologin root --keep-baud 115200,57600,38400,9600 - $TERM
```
if it helps maybe edit the `/etc/passwd` file and set the `winesap` to be something like this `winesap::14871::::::`
note i got this this information from the [Arch Linux wiki](https://wiki.archlinux.org/title/Archiso#Changing_automatic_login)

**Comment by LukeShortCloud** [comment]
Thanks for the suggestions and hints! That's for automatic login on the console.

This GitHub Issue was about the first-time setup script prompting for a `sudo` password. Since `sudo` does not require a password on our minimal and performance image types, it's not necessary.

However, this brings up a good point that we used to allow autologin when we were using the Light Display Manager (LightDM). We've switched to Simple Desktop Display Manager (SDDM) which does support autologin but then you lose the ability to select the session (for example, you can no longer switch from KDE Plasma to Steam Deck Game Mode).

**Comment by GuestSneezeOSDev** [comment]
an easier way for this if you mean when installed on hard drive you can instead use the calamares installer which i left a custom config for archiso and other arch linux isos. Calamares has a feature where you can select log in automatically without password 
[calamares.tar.gz](https://github.com/user-attachments/files/16192602/calamares.tar.gz)

**Comment by GuestSneezeOSDev** [comment]
if asked i can implement this to my PR

**Comment by LukeShortCloud** [comment]
I can add this feature. It should be easy now that we have the `/usr/lib/os-release-winesapos` file for reference and it is world readable.

Related: https://github.com/LukeShortCloud/winesapOS/issues/882

Regarding auto login, it's an option during our first-time setup. The first login requires authentication but does not after that.
