### ISSUE TITLE
winesapOS 3.4.0 dualbooted with debian

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#852]
**Describe the bug or feature**
A clear and concise description of what the bug or feature is.

**Issue Type**
- [x] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

Today i encountered something strange  I had an `.img` of the `minimal` image of winesapOS 3.4.0  i had Debian 12.0 on my main drive (`sda`) after installing it i saw debian 12 was still on my drive and winesapos on the same drive but it couldn't boot properly it put me in the user `rootfs` so i thought it was just an issue with the version so i ran the upgrade script and it downgraded it to 3.1.0
**To Reproduce**`
1. install winesapos

**Expected behavior**
Would erase my entire disk
**Screenshots**

**System information (please complete the following information):**
- Version:3.4.0
- Image type: [Minima]
- Computer type: [PC]
- Graphics vendor: [Intel]
- Graphics card: [Intel Haswell]
- Drive type: [NVMe]
- Drive connection to PC: [USB]

**Additional context**

**Comment by LukeShortCloud** [comment]
Let me make sure I understand. There are two issues:

- **Primary issue:** Debian was installed on your drive. Then you installed winesapOS. But Debian still appears.
    - You might need to wipe your drive with `dd` first. You can follow this example except you can use 8000 instead of 25000.
        - https://github.com/LukeShortCloud/winesapOS/tree/4.1.0-beta.1?tab=readme-ov-file#reinstalling-winesapos
- **Secondary issue:** winesapOS upgrade script downgraded you to 3.1.0.
    - That should not be possible at all.
    - Have you ever had that old version of winesapOS installed?
    - Do you have two winesapOS drives plugged in at the same time?
        - If so, you need to change some labels around. Otherwise, Linux gets confused about which partition label to mount if there are duplicates.
            - https://github.com/LukeShortCloud/winesapOS/tree/4.1.0-beta.1?tab=readme-ov-file#two-or-more-set-ups-of-winesapos-cause-an-unbootable-system
    - What is the output of these two commands?
        ```
        cat /etc/winesapos/UPGRADED
        cat /etc/winesapos/VERSION
        ```

I'm traveling for work over the next few weeks so I apologize in advance if I'm slow to respond.

**Comment by GuestSneezeOSDev** [comment]
the first one worked, Thank You for solving my issue

**Comment by LukeShortCloud** [comment]
Glad to hear that worked!
