### ISSUE TITLE
[install] ONEXPLAYER Drivers

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#854]
**Describe the bug or feature**
A clear and concise description of what the bug or feature is.

**Issue Type**
- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1. N/A Not an issue

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
- Version: [4.1.0 or 4.2.0]
- Image type: [All]
- Computer type: [PC]
- Graphics vendor: [AMD]
- Graphics card: [AMD Radean 680M graphics / RDNA 2 graphics]
- Drive type: [NVME]
- Drive connection to PC: [USB]

**Additional context**

**Comment by GuestSneezeOSDev** [comment]
I Was hoping you could implement this to the AUR so I can add it to my OS GuestSneezeOS and run winesapOS on my ONEXPLAYER https://github.com/GuestSneezeOS/GuestSneezeOS/issues/73

**Comment by LukeShortCloud** [comment]
@GuestSneezeOSDev I'd be happy to help add OneXPlayer support in GuestSneezeOS and winesapOS. :-) I work at Playtron and have a lot of handheld gaming devices to test with but not a OneXPlayer. Have you tried Linux on it? What works and what does not work?

**Comment by GuestSneezeOSDev** [comment]
i have tried some Linux distro's such as Debian but i have not tried Arch Linux or GuestSneezeOS, Debian does not work that well for me since the touchscreen is not working i had to search for a long time for drivers but i could not find them

**Comment by GuestSneezeOSDev** [comment]
the only driver for ONEXPLAYER in the AUR is just for the sensors https://aur.archlinux.org/packages/oxp-sensors-dkms-git

**Comment by LukeShortCloud** [comment]
I can include the `oxp-sensors-dkms-git` package in the winesapOS repository and also install it in winesapOS.

`xf86-input-*` drivers only work on Xorg. We are moving towards Wayland.

I wonder how well a modern Linux distribution would work.

**Comment by GuestSneezeOSDev** [comment]
I Think i could find wayland drivers for Arch Linux

**Comment by LukeShortCloud** [comment]
I'm not an expert in Wayland but my understanding is that all of the input drivers are handled within Wayland itself (no external packages needed).

**Comment by GuestSneezeOSDev** [comment]
Manjaro (KDE) has Touchscreen support but it uses `xwayland`

**Comment by LukeShortCloud** [comment]
I did a quick test of winesapOS 4.1.0-beta.1 with KDE Plasma using Wayland on a (1) Steam Deck (AMD) and (2) MSI Claw (Intel). Both have great touchscreen support. But that doesn't necessarily mean that the OneXPlayer would work perfectly.

**Comment by GuestSneezeOSDev** [comment]
I Do not use ONEXPLAYER 2 i use the OXP Mini i heard that ChimeraOS Has drivers

**Comment by GuestSneezeOSDev** [comment]
I installed ChimeraOS and touchscreen works

**Comment by LukeShortCloud** [comment]
That's great! The experience between ChimeraOS and PlaytronOS should be mostly similar. The only thing missing is that ChimeraOS ships `oxp-sensors-dkms-git` and winesapOS does not. I'll go ahead and add that.

**Comment by GuestSneezeOSDev** [comment]
thank you i just want to know is it in the winesapOS repo since GuestSneezeOS uses it

**Comment by LukeShortCloud** [comment]
@GuestSneezeOSDev No problem, glad to help. :-) Additional packages for AYANEO and OneXPlayer devices have been added to the winesapOS testing repository. They will be part of the winesapOS stable repository along with the 4.1.0 stable release.

AYANEO:

- [ayaneo-platform-dkms-git](https://aur.archlinux.org/packages/ayaneo-platform-dkms-git) = LED kernel driver
- [ayaled-updated](https://aur.archlinux.org/packages/ayaled-updated) = LED user-space utility
- [aw87559-firmware](https://aur.archlinux.org/packages/aw87559-firmware) = Linux firmware for audio from the AYANEO AIR 1S

OneXPlayer:

- [oxp-sensors-dkms-git](https://aur.archlinux.org/packages/oxp-sensors-dkms-git) = Fan control

https://winesapos.lukeshort.cloud/repo/winesapos-testing/x86_64/

**Comment by GuestSneezeOSDev** [comment]
Thank you
