### ISSUE TITLE
[install] AYANEO support

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#855]
These packages provide support full for AYANEO handheld devices:

- [ayaneo-platform-dkms-git](https://aur.archlinux.org/packages/ayaneo-platform-dkms-git) = LED kernel driver
- [ayaled-updated](https://aur.archlinux.org/packages/ayaled-updated) = LED user-space utility
- [aw87559-firmware](https://aur.archlinux.org/packages/aw87559-firmware) = Linux firmware for audio from the AYANEO AIR 1S

https://aur.archlinux.org/packages?O=0&K=ayaneo

**Comment by LukeShortCloud** [comment]
I tested the audio on my AYANEO 2S and it works perfectly. The AYANEO AIR 1S probably still needs additional firmware considering that the AUR package was recently updated a couple of months ago.

**Comment by GuestSneezeOSDev** [comment]
The AYANEO gets very hot while using linux (I do not own a AYANEO but i have heard)

**Comment by LukeShortCloud** [comment]
From what I've heard, that's a hardware limitation. The only difference between my AYANEO 2S and the original AYANEO 2 is an improved heatsink for cooling. A BIOS update (requires Windows) can help improve it a little bit on older devices.

**Comment by GuestSneezeOSDev** [comment]
why not use a fan controller? https://wiki.archlinux.org/title/Fan_speed_control

**Comment by GuestSneezeOSDev** [comment]
The Arch wiki says that everything is supported https://wiki.archlinux.org/title/AYA_NEO_2021

**Comment by LukeShortCloud** [comment]
That's a good idea to use a fan controller. Best-case scenario, `fancontrol` works. However, I've found that most devices do not work and require a very specific fan controller implementation. Even if that worked, I'm not sure what kind of profile to use as I'm not affected by overheating issues.

Somewhat related to this, winesapOS sets a custom fan curve for MacBooks. These are based on community suggestions and have worked well on my Intel Macs.

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-install.sh#L979

**Comment by LukeShortCloud** [comment]
I tested with my device set to 100% fan speed. The touchscreen was still too hot. I can confirm it is a hardware issue.

**Comment by LukeShortCloud** [comment]
The underlying issue with the hot touchscreen was because I was testing the device at 100% brightness (and it's one of the brightest devices I've seen!). In real-world usage, I use a much lower brightness setting and it's actually fine.
