### ISSUE TITLE
[install] Add support for KDE Connect

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#857]
KDE Connect allows connecting a phone for seamless integration between that and the KDE Plasma desktop environment. Originally suggested by @GuestSneezeOSDev to add.

Related: https://github.com/LukeShortCloud/winesapOS/pull/853#issuecomment-2241282746

**Comment by GuestSneezeOSDev** [comment]
Package [`kdeconnect`](https://archlinux.org/packages/extra/x86_64/kdeconnect/)

**Comment by GuestSneezeOSDev** [comment]
i could add this package to my PR

**Comment by LukeShortCloud** [comment]
Sounds good, yes and thank you!

**Comment by GuestSneezeOSDev** [comment]
i will see what i can do

**Comment by GuestSneezeOSDev** [comment]
https://aur.archlinux.org/packages/kdeconnect-git

**Comment by GuestSneezeOSDev** [comment]
i think with this package we can implement this to the repo
`repo-add winesapos.db.tar.gz .pkg.zst`

**Comment by GuestSneezeOSDev** [comment]
i added the package in the winesapos-build-repo

**Comment by GuestSneezeOSDev** [comment]
I think the issue can be closed

**Comment by GuestSneezeOSDev** [comment]
I Have added 3 Lines of codes which will install KDE-Connect which will install KDE-Connect making it supported but i still need the firefox extension for KDE-Connect

**Comment by GuestSneezeOSDev** [comment]
Fixed in https://github.com/LukeShortCloud/winesapOS/pull/853/commits/3de6af9c46218652b20370d9544414b18681d123

**Comment by LukeShortCloud** [comment]
Thanks for your contribution! I finished the KDE Connect implementation by adding a test, having it only install as part of the KDE Plasma desktop environment (it's very complicated to run on other DEs), and added your name to the list of contributor's via this commit: https://github.com/LukeShortCloud/winesapOS/pull/898/commits/294f6a9f34eec3abca32537b03835bf01046c1d1

**Comment by GuestSneezeOSDev** [comment]
Your welcome @LukeShortCloud I am glad to help the winesapOS project move forward
