### ISSUE TITLE
Release winesapOS 4.1.0 on our 4th anniversary

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#861]
August 18th, 2024 will be our 4th anniversary. We're waiting on a bunch of different upstream changes that should all finally be in by then.

ChimeraOS 46 was just released today on their 5th anniversary and I'm inspired to do the same!

https://github.com/ChimeraOS/chimeraos/wiki/Release-Notes#chimeraos-46-2024-07-23

**Comment by LukeShortCloud** [comment]
I've updated the 4.1.0 milestone accordingly with this due date.

**Comment by LukeShortCloud** [comment]
Hey @GuestSneezeOSDev , I wanted to give you a heads up that the stable winesapOS 4.1.0 release will be coming out in less than two weeks!

Here are the current issues left that I'm working on: https://github.com/LukeShortCloud/winesapOS/milestone/17

Is there anything else you'd potentially want to get into this release to help with GueestSneezeOS? Or anything else?

I made some big changes to your dual-boot script to make it work more automatically and with more logging. I did some initial testing of that with Windows 10 and it worked great. I'm going to test Windows 11 and macOS, too. If you want to try it out, I can share with you the necessary files and documentation.

**Comment by GuestSneezeOSDev** [comment]
I Might test it out in macOS (Hackintosh) and Other Linux Distros (Debian,Arch Linux and Fedora) I will make a new comment if it worked or did not work

**Comment by GuestSneezeOSDev** [comment]
It worked extremely well with Hackintosh and other Distros

**Comment by LukeShortCloud** [comment]
Thanks for helping test! I'll mention all of the tested operating systems with dual-boot in our release notes.

I haven't merged the new code yet but there are modified steps for the dual-boot guide. In particular, there is a new "Semi-automated steps:" section.

https://github.com/LukeShortCloud/winesapOS/tree/test?tab=readme-ov-file#dual-boot
https://github.com/LukeShortCloud/winesapOS/tree/test?tab=readme-ov-file#winesapos-dual-boot-install-guide

The stable 4.1.0 release tarball is not ready yet but, for now, you can download the older rootfs. The dual-boot installer will automatically search for it in a few different directories. As the `winesap` user, download the rootfs first.

```
cd ~/Downloads/
wget https://winesapos.lukeshort.cloud/repo/iso/winesapos-4.1.0/_test/winesapos-4.1.0-beta.0-minimal-rootfs.tar.zst
```

Then you can try out the new script as the `winesap` user. It assumes that the partitions have already been created and labelled (ex., `winesapos-root0`, `winesapos-boot0`, and (optionally) `WOS-EFI0`).

```
curl https://raw.githubusercontent.com/LukeShortCloud/winesapOS/test/scripts/winesapos-dual-boot.sh | bash
```

**Comment by GuestSneezeOSDev** [comment]
Thanks it works well for dualbooting windows with winesapOS, I just have one question how could i edit the Pacman.conf of winesapOS

**Comment by LukeShortCloud** [comment]
Nice, thanks for confirming that the updated script works!

For the `/etc/pacman.conf`, we used to have a file we would copy over. I stopped doing that because there were a few times that Pacman updated its configuration file and we missed those changes. Now we dynamically add the configuration during the build. If you search for "pacman.conf" in the `winesapos-install.sh` script, you'll see many `sed` lines to cleverly modify the configuration file.

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-install.sh

For the upgrade, we have `crudini` available to modify the configuration. You may find this interesting as this part of the code recreates our `/etc/pacman.conf`:

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-upgrade.sh#L188
https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-upgrade.sh#L254
https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-upgrade.sh#L323

**Comment by GuestSneezeOSDev** [comment]
Thanks for the information it was very helpful since I am currently making a package repository for GuestSneezeOS
