### ISSUE TITLE
Create GitHub Issues for winesapOS Next tasks

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#864]
There are various features I have been privately planning for upcoming winesapOS 4.Y.0 and 5.Y.0 releases. Something I've been called "winesapOS Next". I will make this publicly available so users and developers can better understand our future plans.

**Comment by LukeShortCloud** [comment]
@GuestSneezeOSDev You may be interested to know that I just finished adding GitHub Issues for all of the features I have planned for winesapOS over the coming year or two. :-)

**Comment by GuestSneezeOSDev** [comment]
@LukeShortCloud Thanks for informing me
