### ISSUE TITLE
[install][setup] Support Xbox Game Pass streaming

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#865]
By providing a desktop shortcut to it.

https://support.microsoft.com/en-us/topic/xbox-cloud-gaming-in-microsoft-edge-with-steam-deck-43dd011b-0ce8-4810-8302-965be6d53296 

Xbox Game Pass streaming used to only work with Microsoft Edge but it now works with Google Chrome (the changes were merged upstream).

https://www.reddit.com/r/SteamDeck/comments/xmub88/xbox_streaming_on_google_chrome/

**Comment by GuestSneezeOSDev** [comment]
Xbox xCloud is a browser-based gaming service : https://www.xbox.com/en-US/play

**Comment by LukeShortCloud** [comment]
Yes, you're right. We'd basically create a desktop shortcut to launch Google Chrome in full-screen mode and to open up that website by default.

**Comment by GuestSneezeOSDev** [comment]
Why not firefox it would be easier `firefox https://www.xbox.com/en-US/play`

**Comment by LukeShortCloud** [comment]
Firefox is my favorite web browser and it does need more users. :-) I'll have to test this out. Officially speaking, Microsoft only lists official support for Google Chrome, Microsoft Edge, and Safari.

https://support.xbox.com/en-US/help/games-apps/cloud-gaming/supported_browsers

**Comment by GuestSneezeOSDev** [comment]
I Tested it and it seems to work on chromium

**Comment by GuestSneezeOSDev** [comment]
Done you can find [Xbox Game Pass/xCloud here](https://github.com/GuestSneezeOSDev/winesapOS/blob/main/files/xcloud.desktop)

**Comment by GuestSneezeOSDev** [comment]
You may close this
