### ISSUE TITLE
[install][setup] Support NVIDIA GeForce NOW streaming

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#866]
We might be able to re-use the script created to install it for the Steam Deck.

https://www.nvidia.com/en-us/geforce-now/download/
https://www.gamingonlinux.com/2024/05/nvidia-make-it-easier-to-get-geforce-now-on-steam-deck/

**Comment by GuestSneezeOSDev** [comment]
Done it will be in my new pull request
[Nvidia GFN can be found here](https://github.com/GuestSneezeOSDev/winesapOS/blob/main/files/gfn.desktop)

**Comment by GuestSneezeOSDev** [comment]
You may close this
