### ISSUE TITLE
[install] Create an /etc/os-release-winesapos file

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#882]
Do not override the `/etc/os-release` as this can easily break things so create a new file at `/etc/os-release-winesapos`. Instead of using a weird non-standard path of `/etc/winesapos/VERSION` (recently changed to `/var/winesapos/VERSION`), use a standardized `os-release` file. Something like:

```
NAME="winesapOS"
ID_LIKE="arch"
VERSION="<WINESAPOS_VERSION>"
```

**Comment by GuestSneezeOSDev** [comment]
I Already made a file similar to that but i found out it was useless since we already have `/etc/winesapos/VERSION`

**Comment by LukeShortCloud** [comment]
Yes, thank you! I'll keep `/etc/winesapos/VERSION` around for legacy purposes but we'll migrate to the file you made:

```
NAME="winesapOS"
PRETTY_NAME="winesapOS"
ID=winesapos
ID_LIKE=arch
VERSION="4.1.0_beta"
VERSION_ID="4.1.0_beta"
HOME_URL="https://github.com/LukeShortCloud/winesapOS"
SUPPORT_URL="https://github.com/LukeShortCloud/winesapOS/issues"
BUG_REPORT_URL="https://github.com/LukeShortCloud/winesapOS/issues"
```

https://github.com/LukeShortCloud/winesapOS/pull/853/commits/985a6b96cd2caa81cc1b158df5d00c2388e2c163

**Comment by GuestSneezeOSDev** [comment]
Your welcome
