### ISSUE TITLE
[contributing] Allow using Docker or Podman for builds

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#887]
Although we require elevated privileges to build winesapOS, I use Podman for work and personal life due to not needing a daemon or root access by default. Podman can also be easily installed onto any Linux distribution making it more accessible. I'd like to push for Podman in our builds but Docker will still work, too.

**Comment by GuestSneezeOSDev** [comment]
Maybe add support for both Docker and Podman?

**Comment by LukeShortCloud** [comment]
You're right, we should support both. No reason why we can't.

**Comment by GuestSneezeOSDev** [comment]
I am making a pull request where podman will be implemented ([Take a look](https://github.com/GuestSneezeOSDev/winesapOS/tree/main))

**Comment by GuestSneezeOSDev** [comment]
My Pull request is coming very soon,
[Docker](https://github.com/GuestSneezeOSDev/winesapOS/blob/main/scripts/winesapos-install.sh#L586) Can be found here
[Podman](https://github.com/GuestSneezeOSDev/winesapOS/blob/main/scripts/repo/winesapos-build-repo.sh#L81) Can be found here

**Comment by GuestSneezeOSDev** [comment]
You may close this issue
