### ISSUE TITLE
Use SteamOS 3 instead of Manjaro

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#89]
Steam just announced SteamOS 3 which is based on Arch Linux. We were going to originally ship both Arch Linux and Manjaro images. It makes much more sense to focus only on one image and have it be based on SteamOS instead.

**Comment by ekultails** [comment]
Optionally provide support to build Arch Linux, Manjaro or Steam OS based on an environment variable: `MLGS_OS={arch,manjaro,steam}`. We likely would only ship Steam OS.

**Comment by LukeShortCloud** [comment]
Add a section to the README that explains differences between Steam OS 3 and winesapOS such as how we have a writeable file system by default.

**Comment by LukeShortCloud** [comment]
Here is the SteamOS 3.0 repository: https://steamdeck-packages.steamos.cloud/archlinux-mirror/

https://www.reddit.com/r/linux_gaming/comments/t5lt40/some_discoveries_from_investigating_the_steamos/

**Comment by LukeShortCloud** [comment]
There is only one mirror listed for SteamOS 3. They also have two custom repositories in that mirror: `jupiter` and `holo`.
