### ISSUE TITLE
[install] Add i3 and Sway support

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#892]
Add the ability to use `WINESAPOS_DE=i3` to build winesapOS with the Sway compositor and i3 tiling window manager.

https://wiki.archlinux.org/title/Sway
https://wiki.archlinux.org/title/I3

**Comment by GuestSneezeOSDev** [comment]
I will add this in my pull request

**Comment by LukeShortCloud** [comment]
That would be awesome, thank you!

Here are some hints. It should go in the code somewhere around here:

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-install.sh#L779

and look something like this:

```
elif [[ "${WINESAPOS_DE}" == "sway" ]]; then
    echo "Installing the Sway tiling manager..."
    pacman_install_chroot swaylock swayidle swaybg
    echo "Installing the Sway tiling manager. complete"
```

I believe there are some other required configuration files but I'm not too familiar with Sway. Our community has been requesting this for awhile now. The full path to the user directory is `${WINESAPOS_INSTALL_DIR}/home/${WINESAPOS_USER_NAME}` or otherwise just use `${WINESAPOS_INSTALL_DIR}` for the root directory of the winesapOS build.

https://wiki.archlinux.org/title/Sway

If you have any questions or need help with anything, let me know!

**Comment by GuestSneezeOSDev** [comment]
I will be adding sway immediately

**Comment by GuestSneezeOSDev** [comment]
Done i will now be figuring out KDE Phone's DE

**Comment by GuestSneezeOSDev** [comment]
Once the PR has been merged you may close this issue

**Comment by LukeShortCloud** [comment]
Will do! I'll close out all relevant tickets you worked on once the code is merged. Thanks again for all of your contributions. :-)

**Comment by GuestSneezeOSDev** [comment]
Your welcome

**Comment by GuestSneezeOSDev** [comment]
You may close this
