### ISSUE TITLE
[install] Install CoolerControl

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#894]
@GuestSneezeOSDev and I were just talking about fan controls recently. Then a news article came out talking about a solution trying to work for all motherboards and fans types: CoolerControl. Cool!

https://www.gamingonlinux.com/2024/07/control-your-cooling-on-linux-with-coolercontrol-v1-4-brings-amd-gpu-rdna-3-fan-support/
https://gitlab.com/coolercontrol/coolercontrol#aur

It appears to already be packaged by the Chaotic AUR, too.

`https://github.com/chaotic-aur/packages/issues/3075`

**Comment by GuestSneezeOSDev** [comment]
Adding it to the buildrepo may solve this issue

**Comment by LukeShortCloud** [comment]
The package is already in the Chaotic AUR repository. I'd probably add the package to be installed into winesapOS here:

```
    echo "Installing additional packages from the AUR..."
    yay_install_chroot coolercontrol qdirstat
    echo "Installing additional packages from the AUR complete."
```

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-install.sh#L573

and then add a related test to make sure it actually got installed:

```
echo "\tChecking that all the packages from the AUR have been installed by yay..."
pacman_search_loop \
    appimagelauncher \
    appimagepool-appimage \
    auto-cpufreq \
    bauh \
    cloud-guest-utils \
    coolercontrol \
    crudini \
    firefox-esr \
    hfsprogs \
    mbpfan-git \
    oh-my-zsh-git \
    pacman-static \
    paru \
    python-iniparse-git \
    python-tests \
    snapd
```

https://github.com/LukeShortCloud/winesapOS/blob/4.1.0-beta.2/scripts/winesapos-tests.sh#L995

**Comment by LukeShortCloud** [comment]
I'll finish adding the rest of what's needed so we can have this in the 4.1.0 release.
