### ISSUE TITLE
[install][setup][tests][upgrade] Add optional systemd-boot support

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#899]
**Describe the bug or feature**
An image type which uses `systemd`

**Issue Type**
- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1.  Not an issue

**Expected behavior**
Not an issue

**Screenshots**

**System information (please complete the following information):**
- Version: [4.2.0/5.0.0]
- Image type: [Preformance]
- Computer type: [PC]
- Graphics vendor: [Intel]
- Graphics card: [Intel Haswell]
- Drive type: [NVMe]
- Drive connection to PC: [USB]

**Additional context**

**Comment by LukeShortCloud** [comment]
Do you mean to use `systemd-boot` instead of `grub` for the bootloader? We use `systemd` for managing our services already.

**Comment by GuestSneezeOSDev** [comment]
I meant for the bootloader I am more used to Arch Linux than other Linux Distro's

**Comment by LukeShortCloud** [comment]
I'll look into adding it. I'm thinking it'll be configured by a new environment variable: `WINESAPOS_BOOTLOADER=grub` (default) or `WINESAPOS_BOOTLOADER=systemd-boot`.

**Comment by GuestSneezeOSDev** [comment]
Thanks

**Comment by GuestSneezeOSDev** [comment]
Use `bootctl`

**Comment by GuestSneezeOSDev** [comment]
I think i can implement it in my latest PR
