### ISSUE TITLE
Add other linux subsystems

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#901]
I Think it will be pretty cool to run many distros on one system similar to vanillaOS it should probably use `Docker`,`Podman` or lillypod (this idea was mainly because I want to fastfetch as many systems i can)

**Comment by LukeShortCloud** [comment]
It sounds like what you want is `distrobox`. This is already installed and configured on winesapOS. Here are my personal notes on how to use it. Skip the installation part and start with "Create a new container".

https://rootpages.lukeshort.cloud/virtualization/containers.html#distrobox

Here are some example container images you can use (the versions here are slightly outdated but the names are the same).

https://rootpages.lukeshort.cloud/virtualization/containers.html#images

**Comment by GuestSneezeOSDev** [comment]
I Did not know that was already in winesapOS thanks
