### ISSUE TITLE
Add KDE Mobile support

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#906]
**Describe the bug or feature**
Mobile support
**Issue Type**
- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [ ] Question
- [ ] Other [Please specify]

**To Reproduce**
1.  not an issue

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
- Version: [4.2.0]
- Image type: [All]
- Computer type: [Mobile]
- Graphics vendor: [Unknown https://github.com/LukeShortCloud/winesapOS/discussions/905]
- Graphics card: [Unkown https://github.com/LukeShortCloud/winesapOS/discussions/905]
- Drive type: [SSD]
- Drive connection to PC: [Not specified]

**Additional context**
This issue was from https://github.com/LukeShortCloud/winesapOS/discussions/905

**Comment by GuestSneezeOSDev** [comment]
https://github.com/LukeShortCloud/winesapOS/discussions/905 related

**Comment by LukeShortCloud** [comment]
KDE Mobile will not get us Android or Arm support but it could be useful for x86 gaming handhelds.

**Comment by GuestSneezeOSDev** [comment]
I realized that since WinesapOS DE is not designed for mobile devices, it may not display correctly. Therefore, I thought KDE Mobile's DE might be a more suitable option.

**Comment by LukeShortCloud** [comment]
That makes perfect sense. I recently ran the full KDE Plasma desktop environment on my phone using the Arch Linux Arm project and, I can confirm, it was really tiny and hard to use lol.

The difference in CPU architecture is the biggest challenge for us. I originally wanted to support Arm with winesapOS but it is a ton of work. There is also not much of a competitive advantage I can provide compared to other Linux distributions designed for Arm. Most of our x86 apps do not work on Arm.

**Comment by GuestSneezeOSDev** [comment]
I recommend creating a new image called "winesapOS Arm" designed specifically for mobile devices. This image would be lightweight, suitable for the limited storage available on mobile phones (typically 64-128 GB). Here is a list of software that supports Arm CPUs, which could be included in the image:
```
ClamAV
Clamtk
QDirStat
AppImagePool
BalenaEtcher
bauh
Blueman
Bottles
Calibre
Cheese
CoolerControl
Discord
Discover
Distrobox
Dolphin (KDE Plasma)
Nemo (Cinnamon)
Nautilus (GNOME)
FileZilla
Firefox ESR
Firewall
Flatseal
Google Chrome
GParted
Gwenview (KDE Plasma)
Pix (Cinnamon)
Eye of GNOME
KeePassXC
LibreOffice
Modem Manager GUI
OBS Studio
PeaZip
qBittorrent
Spectacle
usbmuxd
Waydroid
VeraCrypt
VLC
ZeroTier GUI
DOSBox
Steam
Heroic Games Launcher
Lutris
Open Gamepad UI
Prism Launcher
EmuDeck
Proton
GE-Proton
GameMode
Gamescope
MangoHud
GOverlay
Ludusavi
ProtonUp-Qt
ZeroTier VPN
AntiMicroX
game-devices-udev
OpenRazer
Polychromatic
Oversteer
Gamescope Session
```

**Comment by LukeShortCloud** [comment]
@GuestSneezeOSDev Some programs on that list do not natively run on Arm such as:

- EmuDeck
- Google Chrome (only has a macOS and Windows Arm build - but there is Chromium for Linux Arm)
- Heroic Games Launcher (only has a macOS Arm build)
- Open Gamepad UI
- Proton and GE-Proton
- Steam

I'm sure I'm missing more.

Do you have an Arm device? Unlike x86, we have to specifically make a build for a certain device. It does not work on every device like x86 does.

Long-term, I'd be interested in making an Arm image but it's very complicated and time consuming. My current recommendation is: for tinkerers to wait for an Asahi Linux update for Macs that will include gaming packages later this year, for gamers to wait for PlaytronOS on select devices.

Short-term, we can add KDE Plasma Mobile. It works on x86 and Arm.

**Comment by GuestSneezeOSDev** [comment]
I Do not have an Arm Device (Not counting my mobile phone) maybe instead of making an ARM image we can make an x86 image instead?

**Comment by LukeShortCloud** [comment]
It's possible we could create a KDE Plasma Mobile image for x86, sure. I wonder how much extra space it would take if we installed it alongside the traditional KDE Plasma desktop environment. We might be able to bundle both. You can pick which session / desktop environment to use on the login screen.

**Comment by LukeShortCloud** [comment]
By x86 I generically mean AMD and Intel CPU architectures (including 32-bit and 64-bit). I don't want to support 32-bit only systems.

Another problem with Arm is that their latest processors only support 64-bit. So AMD/Intel apps and 32-bit Arm apps won't work. Things like Steam require both. There are solutions in the works but they are complicated.

Yeah, we could potentially have both of those sessions available in the same images we have today just by installing the KDE Mobile packages.

Does that make sense?

**Comment by GuestSneezeOSDev** [comment]
Perhaps instead of focusing on 32-bit support right now (which we can add at a later date), we could prioritize using KDE Mobile for devices like tablets or other small-screen devices.

**Comment by LukeShortCloud** [comment]
Yeah, we can add KDE Mobile now and worry about other CPU architectures later.

**Comment by GuestSneezeOSDev** [comment]
Thanks mate, That'll help a ton

**Comment by GuestSneezeOSDev** [comment]
I Have added them in my latest pull request
