### ISSUE TITLE
[readme] Document the dual-boot script

### ISSUE THREAD

**Issue by LukeShortCloud** [LukeShortCloud/winesapOS#909]
Once the dual-boot script can do more than the documentation, we should document how to use it.

Related: https://github.com/LukeShortCloud/winesapOS/issues/907
Related: https://github.com/LukeShortCloud/winesapOS/issues/908

**Comment by GuestSneezeOSDev** [comment]
The `Dual-boot script` automates the process of setting up a dual-boot configuration on a system, allowing two operating systems to be installed and selected at boot time
