### ISSUE TITLE
why is winesapOS images so big?

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#913]
**Describe the bug or feature**
why are the images so big, I Recreated winesapOS in `archiso` and the iso was only 4 GB on avg
**Issue Type**
- [ ] Bug Report
- [ ] Feature Request
- [ ] Documentation
- [x] Question
- [ ] Other [Please specify]

**To Reproduce**
1.  Not an issue

**Expected behavior**

**Screenshots**

**System information (please complete the following information):**
- Version: [4.1.0]
- Image type: [Minimal]
- Computer type: [PC]
- Graphics vendor: [Intel]
- Graphics card: [Intel Haswell ULT]
- Drive type: [NVMe]
- Drive connection to PC: [USB]

**Additional context**

**Comment by LukeShortCloud** [comment]
Good question!

Looking at the minimal winesapOS 4.0.0 image type, here is the current usage:

- `/` = 3.9 GiB / 5.5 GiB
- `/boot/` = 265 MiB / 974 MiB
- `/boot/efi/` = 160 KiB / 510 MiB

Comparing that to your `archiso`, if you combine all of that space into a single partition then it is about 4.0 GiB like you are seeing.

One problem with that is that Btrfs is not a supported file system with GRUB. It technically works but there are limitations. For example, GRUB on Btrfs cannot write to the bootloader partition (required to change the Linux kernel selection).

Our minimal image is 7 GiB in size to fit on a 8 GB (7.45 GiB) flash drive. I've changed the size of the image types a few times but it usually grows as we add more features. Most recently, KDE Plasma 6 is a lot bigger than 5.

The EFI partition is seemingly the most wasted space at less than 1% usage. However, it's needed for using `fwupd` to upgrade BIOS and other hardware firmware. In fact, the current recommendation from both Arch Linux and Fedora is to increase that to 1 GiB.

Related: https://github.com/LukeShortCloud/winesapOS/issues/888

I would like to make the image even smaller but it's a difficult balancing act.

**Comment by LukeShortCloud** [comment]
For the performance and secure image types, we include a 16 GB (14.9 GiB) exFAT partition. The purpose is to be able to copy files between Linux, macOS, and Windows (assuming you have winesapOS installed on a USB drive).

**Comment by GuestSneezeOSDev** [comment]
Hello thanks for the response this really helped with my question

**Comment by LukeShortCloud** [comment]
Glad to help explain it!
