### ISSUE TITLE
Add PPSSPP Emulator in winesapOS

### ISSUE THREAD

**Issue by GuestSneezeOSDev** [LukeShortCloud/winesapOS#914]
**Describe the bug or feature**
[i found the package inside the chaotic AUR so this is possible](https://builds.garudalinux.org/repos/chaotic-aur/x86_64/ppsspp-git-1.17.1.r966.g1c5512a-1-x86_64.pkg.tar.zst) if you want to know what this package is it is a PSP emulator
**Issue Type**
- [ ] Bug Report
- [x] Feature Request
- [ ] Documentation
- [x] Question
- [ ] Other [Please specify]

**To Reproduce**
1.  not an issue

**Expected behavior**
Not an Issue
**Screenshots**

**System information (please complete the following information):**
- Version: [4.1.0]
- Image type: [Minimal]
- Computer type: [PC]
- Graphics vendor: [Intel]
- Graphics card: [Intel Haswell ULT]
- Drive type: [NVMe]
- Drive connection to PC: [USB]

**Additional context**

**Comment by LukeShortCloud** [comment]
I don't want to directly add any emulators due to it being a legal gray area. However, we do provide EmuDeck which helps to install emulators such as PPSSPP.

**Comment by GuestSneezeOSDev** [comment]
Thanks anyway
